(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["index"],{

/***/ "./src/routes/index.svelte":
/*!*********************************!*\
  !*** ./src/routes/index.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal.mjs");
/* src/routes/index.svelte generated by Svelte v3.2.0 */


const file = "src/routes/index.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = 'svelte-1s8z3aw-style';
	style.textContent = "h1.svelte-1s8z3aw,figure.svelte-1s8z3aw,div.svelte-1s8z3aw,p.svelte-1s8z3aw{text-align:center;margin:0 auto}.caption.svelte-1s8z3aw{margin:0 auto;padding-top:200px;width:70%}.btnPush.svelte-1s8z3aw:hover{margin-top:15px;margin-bottom:5px}.btnBlueGreen.btnPush.svelte-1s8z3aw:hover{box-shadow:0px 0px 0px 0px #007144}a.svelte-1s8z3aw,a.svelte-1s8z3aw:visited{text-decoration:none;color:#00ae68}a.button.svelte-1s8z3aw{width:120px;padding:10px 50px 10px 50px;font-weight:600;text-align:center;line-height:50px;color:#fff;border-radius:5px;transition:all 0.2s}.btnBlueGreen.btnPush.svelte-1s8z3aw{box-shadow:0px 5px 0px 0px #007144}.btnBlueGreen.svelte-1s8z3aw{background:#00ae68}.btnBlueGreen.btnPush.svelte-1s8z3aw:hover{box-shadow:0px 0px 0px 0px #007144}.btnPush.svelte-1s8z3aw:hover{margin-top:15px;margin-bottom:5px}h1.svelte-1s8z3aw{font-size:2.8em;font-weight:700;margin:0 0 0.5em 0}figure.svelte-1s8z3aw{margin:0 0 1em 0}img.svelte-1s8z3aw{width:100%;max-width:180px;margin:0 0 1em 0}@media(min-width: 480px){h1.svelte-1s8z3aw{font-size:4em}}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguc3ZlbHRlIiwic291cmNlcyI6WyJpbmRleC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgbGV0IGNvdW50ID0gMDtcbiAgbGV0IHF1b3RlID0gXCJcIjtcbiAgbGV0IGNlbGVicml0eSA9IFwiXCI7XG5cbiAgYXN5bmMgZnVuY3Rpb24gZ2V0UXVvdGUoKSB7XG4gICAgY291bnQgKz0gMTtcbiAgICB2YXIgdXJseSA9IFwiaHR0cDovL2xvY2FsaG9zdDozMzMzL3F1b3RlXCI7XG4gICAgbGV0IHJlc3BvbnNlID0gYXdhaXQgZmV0Y2godXJseSk7XG4gICAgbGV0IGRhdGEgPSBhd2FpdCByZXNwb25zZS5qc29uKCk7XG4gICAgY29uc29sZS5sb2coZGF0YSk7XG4gICAgcXVvdGUgPSBkYXRhO1xuICAgIC8vIHJldHVybiB7IHF1b3RlOiBkYXRhIH07IC8vIDwhLS0gYW5kIHdlJ3JlIHJldHVybmluZyB0aGUgcmVzdWx0LCByYXRoZXIgdGhhbiB0aGlzLnNldCguLi4pXG4gIH1cbiAgYXN5bmMgZnVuY3Rpb24gZ2V0Q2VsZWJyaXR5KCkge1xuICAgIHZhciB1cmx5ID0gXCJodHRwOi8vbG9jYWxob3N0OjMzMzMvY2VsZWJyaXR5XCI7XG4gICAgbGV0IHJlc3BvbnNlID0gYXdhaXQgZmV0Y2godXJseSk7XG4gICAgbGV0IGRhdGEgPSBhd2FpdCByZXNwb25zZS5qc29uKCk7XG4gICAgY29uc29sZS5sb2coZGF0YSk7XG4gICAgY2VsZWJyaXR5ID0gZGF0YTtcbiAgICAvLyByZXR1cm4geyBjZWxlYnJpdHk6IHJlc3BvbnNlIH07XG4gIH1cbiAgYXN5bmMgZnVuY3Rpb24gaGFuZGxlQ2xpY2soZXZlbnQpIHtcbiAgICBnZXRRdW90ZSgpO1xuICAgIGdldENlbGVicml0eSgpO1xuICB9XG5cbiAgZnVuY3Rpb24gcHJlbG9hZCh7IHBhcmFtcywgcXVlcnkgfSkge1xuICAgIC8vIG5vdGhpbmcgdG9kb1xuICB9XG48L3NjcmlwdD5cblxuPHN0eWxlPlxuICBoMSxcbiAgZmlndXJlLFxuICBkaXYsXG4gIHAge1xuICAgIHRleHQtYWxpZ246IGNlbnRlcjtcbiAgICBtYXJnaW46IDAgYXV0bztcbiAgfVxuXG4gIC5jYXB0aW9uIHtcbiAgICBtYXJnaW46IDAgYXV0bztcbiAgICBwYWRkaW5nLXRvcDogMjAwcHg7XG4gICAgd2lkdGg6IDcwJTtcbiAgfVxuXG4gIC5xdW90ZSB7XG4gICAgZm9udC1mYW1pbHk6IFwiTGlicmUgQmFza2VydmlsbGVcIiwgR2VvcmdpYSwgc2VyaWY7XG4gIH1cblxuICAuYnRuUHVzaDpob3ZlciB7XG4gICAgbWFyZ2luLXRvcDogMTVweDtcbiAgICBtYXJnaW4tYm90dG9tOiA1cHg7XG4gIH1cblxuICAuYnRuQmx1ZUdyZWVuLmJ0blB1c2g6aG92ZXIge1xuICAgIGJveC1zaGFkb3c6IDBweCAwcHggMHB4IDBweCAjMDA3MTQ0O1xuICB9XG5cbiAgYSxcbiAgYTp2aXNpdGVkIHtcbiAgICB0ZXh0LWRlY29yYXRpb246IG5vbmU7XG4gICAgY29sb3I6ICMwMGFlNjg7XG4gIH1cblxuICBhLmJ1dHRvbiB7XG4gICAgLyogZGlzcGxheTogYmxvY2s7XG4gICAgcG9zaXRpb246IHJlbGF0aXZlOyBcbiAgICBmbG9hdDogbGVmdDsqL1xuICAgIHdpZHRoOiAxMjBweDtcbiAgICBwYWRkaW5nOiAxMHB4IDUwcHggMTBweCA1MHB4O1xuICAgIGZvbnQtd2VpZ2h0OiA2MDA7XG4gICAgdGV4dC1hbGlnbjogY2VudGVyO1xuICAgIGxpbmUtaGVpZ2h0OiA1MHB4O1xuICAgIGNvbG9yOiAjZmZmO1xuICAgIGJvcmRlci1yYWRpdXM6IDVweDtcbiAgICB0cmFuc2l0aW9uOiBhbGwgMC4ycztcbiAgfVxuXG4gIC5idG5CbHVlR3JlZW4uYnRuUHVzaCB7XG4gICAgYm94LXNoYWRvdzogMHB4IDVweCAwcHggMHB4ICMwMDcxNDQ7XG4gIH1cblxuICAuYnRuQmx1ZUdyZWVuIHtcbiAgICBiYWNrZ3JvdW5kOiAjMDBhZTY4O1xuICB9XG5cbiAgLmJ0bkJsdWVHcmVlbi5idG5QdXNoOmhvdmVyIHtcbiAgICBib3gtc2hhZG93OiAwcHggMHB4IDBweCAwcHggIzAwNzE0NDtcbiAgfVxuXG4gIC5idG5QdXNoOmhvdmVyIHtcbiAgICBtYXJnaW4tdG9wOiAxNXB4O1xuICAgIG1hcmdpbi1ib3R0b206IDVweDtcbiAgfVxuXG4gIGgxIHtcbiAgICBmb250LXNpemU6IDIuOGVtO1xuICAgIGZvbnQtd2VpZ2h0OiA3MDA7XG4gICAgbWFyZ2luOiAwIDAgMC41ZW0gMDtcbiAgfVxuXG4gIGZpZ3VyZSB7XG4gICAgbWFyZ2luOiAwIDAgMWVtIDA7XG4gIH1cblxuICBpbWcge1xuICAgIHdpZHRoOiAxMDAlO1xuICAgIG1heC13aWR0aDogMTgwcHg7XG4gICAgbWFyZ2luOiAwIDAgMWVtIDA7XG4gIH1cblxuICBAbWVkaWEgKG1pbi13aWR0aDogNDgwcHgpIHtcbiAgICBoMSB7XG4gICAgICBmb250LXNpemU6IDRlbTtcbiAgICB9XG4gIH1cbjwvc3R5bGU+XG5cbjxzdmVsdGU6aGVhZD5cbiAgPHRpdGxlPlNhcHBlciBwcm9qZWN0IHRlbXBsYXRlPC90aXRsZT5cbjwvc3ZlbHRlOmhlYWQ+XG48ZGl2IGNsYXNzPVwiY2FwdGlvblwiPlxuICA8aDE+ZmFsc2UgcXVvdGVzIGdlbmVyYXRvcjwvaDE+XG48L2Rpdj5cblxuPGRpdj5cbiAgPGZpZ3VyZT5cbiAgICA8aW1nIGFsdD1cIkJvcmF0XCIgc3JjPVwicXVvdGUucG5nXCIgLz5cbiAgICA8ZmlnY2FwdGlvbj48cD57cXVvdGV9PC9wPjxwPntjZWxlYnJpdHl9PC9wPjwvZmlnY2FwdGlvbj5cbiAgPC9maWd1cmU+XG4gIDxzcGFuPlxuICAgIDxhXG4gICAgICBvbjpjbGljaz17aGFuZGxlQ2xpY2t9XG4gICAgICBocmVmPVwiXCJcbiAgICAgIHRpdGxlPVwiQnV0dG9uIHB1c2ggYmx1ZS9ncmVlblwiXG4gICAgICBjbGFzcz1cImJ1dHRvbiBidG5QdXNoIGJ0bkJsdWVHcmVlblwiPlxuICAgICAgR08hXG4gICAgPC9hPlxuICA8L3NwYW4+XG48L2Rpdj5cbiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFpQ0UsaUJBQUUsQ0FDRixxQkFBTSxDQUNOLGtCQUFHLENBQ0gsQ0FBQyxlQUFDLENBQUMsQUFDRCxVQUFVLENBQUUsTUFBTSxDQUNsQixNQUFNLENBQUUsQ0FBQyxDQUFDLElBQUksQUFDaEIsQ0FBQyxBQUVELFFBQVEsZUFBQyxDQUFDLEFBQ1IsTUFBTSxDQUFFLENBQUMsQ0FBQyxJQUFJLENBQ2QsV0FBVyxDQUFFLEtBQUssQ0FDbEIsS0FBSyxDQUFFLEdBQUcsQUFDWixDQUFDLEFBTUQsdUJBQVEsTUFBTSxBQUFDLENBQUMsQUFDZCxVQUFVLENBQUUsSUFBSSxDQUNoQixhQUFhLENBQUUsR0FBRyxBQUNwQixDQUFDLEFBRUQsYUFBYSx1QkFBUSxNQUFNLEFBQUMsQ0FBQyxBQUMzQixVQUFVLENBQUUsR0FBRyxDQUFDLEdBQUcsQ0FBQyxHQUFHLENBQUMsR0FBRyxDQUFDLE9BQU8sQUFDckMsQ0FBQyxBQUVELGdCQUFDLENBQ0QsZ0JBQUMsUUFBUSxBQUFDLENBQUMsQUFDVCxlQUFlLENBQUUsSUFBSSxDQUNyQixLQUFLLENBQUUsT0FBTyxBQUNoQixDQUFDLEFBRUQsQ0FBQyxPQUFPLGVBQUMsQ0FBQyxBQUlSLEtBQUssQ0FBRSxLQUFLLENBQ1osT0FBTyxDQUFFLElBQUksQ0FBQyxJQUFJLENBQUMsSUFBSSxDQUFDLElBQUksQ0FDNUIsV0FBVyxDQUFFLEdBQUcsQ0FDaEIsVUFBVSxDQUFFLE1BQU0sQ0FDbEIsV0FBVyxDQUFFLElBQUksQ0FDakIsS0FBSyxDQUFFLElBQUksQ0FDWCxhQUFhLENBQUUsR0FBRyxDQUNsQixVQUFVLENBQUUsR0FBRyxDQUFDLElBQUksQUFDdEIsQ0FBQyxBQUVELGFBQWEsUUFBUSxlQUFDLENBQUMsQUFDckIsVUFBVSxDQUFFLEdBQUcsQ0FBQyxHQUFHLENBQUMsR0FBRyxDQUFDLEdBQUcsQ0FBQyxPQUFPLEFBQ3JDLENBQUMsQUFFRCxhQUFhLGVBQUMsQ0FBQyxBQUNiLFVBQVUsQ0FBRSxPQUFPLEFBQ3JCLENBQUMsQUFFRCxhQUFhLHVCQUFRLE1BQU0sQUFBQyxDQUFDLEFBQzNCLFVBQVUsQ0FBRSxHQUFHLENBQUMsR0FBRyxDQUFDLEdBQUcsQ0FBQyxHQUFHLENBQUMsT0FBTyxBQUNyQyxDQUFDLEFBRUQsdUJBQVEsTUFBTSxBQUFDLENBQUMsQUFDZCxVQUFVLENBQUUsSUFBSSxDQUNoQixhQUFhLENBQUUsR0FBRyxBQUNwQixDQUFDLEFBRUQsRUFBRSxlQUFDLENBQUMsQUFDRixTQUFTLENBQUUsS0FBSyxDQUNoQixXQUFXLENBQUUsR0FBRyxDQUNoQixNQUFNLENBQUUsQ0FBQyxDQUFDLENBQUMsQ0FBQyxLQUFLLENBQUMsQ0FBQyxBQUNyQixDQUFDLEFBRUQsTUFBTSxlQUFDLENBQUMsQUFDTixNQUFNLENBQUUsQ0FBQyxDQUFDLENBQUMsQ0FBQyxHQUFHLENBQUMsQ0FBQyxBQUNuQixDQUFDLEFBRUQsR0FBRyxlQUFDLENBQUMsQUFDSCxLQUFLLENBQUUsSUFBSSxDQUNYLFNBQVMsQ0FBRSxLQUFLLENBQ2hCLE1BQU0sQ0FBRSxDQUFDLENBQUMsQ0FBQyxDQUFDLEdBQUcsQ0FBQyxDQUFDLEFBQ25CLENBQUMsQUFFRCxNQUFNLEFBQUMsWUFBWSxLQUFLLENBQUMsQUFBQyxDQUFDLEFBQ3pCLEVBQUUsZUFBQyxDQUFDLEFBQ0YsU0FBUyxDQUFFLEdBQUcsQUFDaEIsQ0FBQyxBQUNILENBQUMifQ== */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(document.head, style);
}

function create_fragment(ctx) {
	var t0, div0, h1, t1, t2, div1, figure, img, t3, figcaption, p0, t4, p1, t5, t6, span, a, t7, dispose;

	return {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h1");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("false quotes generator");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			figure = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("figure");
			img = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			figcaption = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("figcaption");
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(ctx.quote);
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(ctx.celebrity);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("GO!");
			this.h()
		},

		l: function claim(nodes) {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n");

			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true }, false);
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);

			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div0_nodes, "H1", { class: true }, false);
			var h1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h1);

			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h1_nodes, "false quotes generator");
			h1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n\n");

			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true }, false);
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);

			figure = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "FIGURE", { class: true }, false);
			var figure_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(figure);

			img = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(figure_nodes, "IMG", { alt: true, src: true, class: true }, false);
			var img_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(img);

			img_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(figure_nodes, "\n    ");

			figcaption = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(figure_nodes, "FIGCAPTION", {}, false);
			var figcaption_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(figcaption);

			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(figcaption_nodes, "P", { class: true }, false);
			var p0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p0);

			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, ctx.quote);
			p0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(figcaption_nodes, "P", { class: true }, false);
			var p1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p1);

			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, ctx.celebrity);
			p1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			figcaption_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			figure_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div1_nodes, "\n  ");

			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "SPAN", {}, false);
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);

			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span_nodes, "A", { href: true, title: true, class: true }, false);
			var a_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a);

			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a_nodes, "GO!");
			a_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			document.title = "Sapper project template";
			h1.className = "svelte-1s8z3aw";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h1, file, 124, 2, 2143);
			div0.className = "caption svelte-1s8z3aw";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 123, 0, 2119);
			img.alt = "Borat";
			img.src = "quote.png";
			img.className = "svelte-1s8z3aw";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img, file, 129, 4, 2204);
			p0.className = "svelte-1s8z3aw";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p0, file, 130, 16, 2256);
			p1.className = "svelte-1s8z3aw";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p1, file, 130, 30, 2270);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(figcaption, file, 130, 4, 2244);
			figure.className = "svelte-1s8z3aw";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(figure, file, 128, 2, 2191);
			a.href = "";
			a.title = "Button push blue/green";
			a.className = "button btnPush btnBlueGreen svelte-1s8z3aw";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a, file, 133, 4, 2327);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 132, 2, 2316);
			div1.className = "svelte-1s8z3aw";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 127, 0, 2183);
			dispose = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen"])(a, "click", ctx.handleClick);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, div0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div0, h1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(h1, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t2, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, div1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, figure);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figure, img);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figure, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figure, figcaption);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figcaption, p0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p0, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figcaption, p1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, span);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span, a);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(a, t7);
		},

		p: function update(changed, ctx) {
			if (changed.quote) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t4, ctx.quote);
			}

			if (changed.celebrity) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t5, ctx.celebrity);
			}
		},

		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t0);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(div0);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t2);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(div1);
			}

			dispose();
		}
	};
}

function preload({ params, query }) {
  // nothing todo
}

function instance($$self, $$props, $$invalidate) {
	let count = 0;
  let quote = "";
  let celebrity = "";

  async function getQuote() {
    $$invalidate('count', count += 1);
    var urly = "http://localhost:3333/quote";
    let response = await fetch(urly);
    let data = await response.json();
    console.log(data);
    $$invalidate('quote', quote = data);
    // return { quote: data }; // <!-- and we're returning the result, rather than this.set(...)
  }
  async function getCelebrity() {
    var urly = "http://localhost:3333/celebrity";
    let response = await fetch(urly);
    let data = await response.json();
    console.log(data);
    $$invalidate('celebrity', celebrity = data);
    // return { celebrity: response };
  }
  async function handleClick(event) {
    getQuote();
    getCelebrity();
  }

	return { quote, celebrity, handleClick };
}

class Routes extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-1s8z3aw-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], []);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Routes);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvcm91dGVzL2luZGV4LnN2ZWx0ZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3lFQWtJb0IsS0FBSzs7eUVBQVMsU0FBUzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt5RkFBdkIsS0FBSzs7Ozs7O3lGQUFTLFNBQVM7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7NEZBSTNCLFdBQVc7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzZFQUpQLEtBQUs7Ozs7NkVBQVMsU0FBUzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUF2R3pDLFNBQVMsT0FBTyxDQUFDLEVBQUUsTUFBTSxFQUFFLEtBQUssRUFBRSxFQUFFO0FBQ3BDO0FBQ0EsQ0FBQzs7O0NBNUJELElBQUksS0FBSyxHQUFHLENBQUMsQ0FBQztFQUNkLElBQUksS0FBSyxHQUFHLEVBQUUsQ0FBQztFQUNmLElBQUksU0FBUyxHQUFHLEVBQUUsQ0FBQzs7RUFFbkIsZUFBZSxRQUFRLEdBQUc7MEJBQ3hCLEtBQUssSUFBSSxFQUFDLENBQUM7SUFDWCxJQUFJLElBQUksR0FBRyw2QkFBNkIsQ0FBQztJQUN6QyxJQUFJLFFBQVEsR0FBRyxNQUFNLEtBQUssQ0FBQyxJQUFJLENBQUMsQ0FBQztJQUNqQyxJQUFJLElBQUksR0FBRyxNQUFNLFFBQVEsQ0FBQyxJQUFJLEVBQUUsQ0FBQztJQUNqQyxPQUFPLENBQUMsR0FBRyxDQUFDLElBQUksQ0FBQyxDQUFDOzBCQUNsQixLQUFLLEdBQUcsS0FBSSxDQUFDOztHQUVkO0VBQ0QsZUFBZSxZQUFZLEdBQUc7SUFDNUIsSUFBSSxJQUFJLEdBQUcsaUNBQWlDLENBQUM7SUFDN0MsSUFBSSxRQUFRLEdBQUcsTUFBTSxLQUFLLENBQUMsSUFBSSxDQUFDLENBQUM7SUFDakMsSUFBSSxJQUFJLEdBQUcsTUFBTSxRQUFRLENBQUMsSUFBSSxFQUFFLENBQUM7SUFDakMsT0FBTyxDQUFDLEdBQUcsQ0FBQyxJQUFJLENBQUMsQ0FBQzs4QkFDbEIsU0FBUyxHQUFHLEtBQUksQ0FBQzs7R0FFbEI7RUFDRCxlQUFlLFdBQVcsQ0FBQyxLQUFLLEVBQUU7SUFDaEMsUUFBUSxFQUFFLENBQUM7SUFDWCxZQUFZLEVBQUUsQ0FBQztHQUNoQiIsImZpbGUiOiJmNDBjOTIxMzc2MWUxNDZkYTc5Ni9pbmRleC5pbmRleC5qcyIsInNvdXJjZXNDb250ZW50IjpbIjxzY3JpcHQ+XG4gIGxldCBjb3VudCA9IDA7XG4gIGxldCBxdW90ZSA9IFwiXCI7XG4gIGxldCBjZWxlYnJpdHkgPSBcIlwiO1xuXG4gIGFzeW5jIGZ1bmN0aW9uIGdldFF1b3RlKCkge1xuICAgIGNvdW50ICs9IDE7XG4gICAgdmFyIHVybHkgPSBcImh0dHA6Ly9sb2NhbGhvc3Q6MzMzMy9xdW90ZVwiO1xuICAgIGxldCByZXNwb25zZSA9IGF3YWl0IGZldGNoKHVybHkpO1xuICAgIGxldCBkYXRhID0gYXdhaXQgcmVzcG9uc2UuanNvbigpO1xuICAgIGNvbnNvbGUubG9nKGRhdGEpO1xuICAgIHF1b3RlID0gZGF0YTtcbiAgICAvLyByZXR1cm4geyBxdW90ZTogZGF0YSB9OyAvLyA8IS0tIGFuZCB3ZSdyZSByZXR1cm5pbmcgdGhlIHJlc3VsdCwgcmF0aGVyIHRoYW4gdGhpcy5zZXQoLi4uKVxuICB9XG4gIGFzeW5jIGZ1bmN0aW9uIGdldENlbGVicml0eSgpIHtcbiAgICB2YXIgdXJseSA9IFwiaHR0cDovL2xvY2FsaG9zdDozMzMzL2NlbGVicml0eVwiO1xuICAgIGxldCByZXNwb25zZSA9IGF3YWl0IGZldGNoKHVybHkpO1xuICAgIGxldCBkYXRhID0gYXdhaXQgcmVzcG9uc2UuanNvbigpO1xuICAgIGNvbnNvbGUubG9nKGRhdGEpO1xuICAgIGNlbGVicml0eSA9IGRhdGE7XG4gICAgLy8gcmV0dXJuIHsgY2VsZWJyaXR5OiByZXNwb25zZSB9O1xuICB9XG4gIGFzeW5jIGZ1bmN0aW9uIGhhbmRsZUNsaWNrKGV2ZW50KSB7XG4gICAgZ2V0UXVvdGUoKTtcbiAgICBnZXRDZWxlYnJpdHkoKTtcbiAgfVxuXG4gIGZ1bmN0aW9uIHByZWxvYWQoeyBwYXJhbXMsIHF1ZXJ5IH0pIHtcbiAgICAvLyBub3RoaW5nIHRvZG9cbiAgfVxuPC9zY3JpcHQ+XG5cbjxzdHlsZT5cbiAgaDEsXG4gIGZpZ3VyZSxcbiAgZGl2LFxuICBwIHtcbiAgICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gICAgbWFyZ2luOiAwIGF1dG87XG4gIH1cblxuICAuY2FwdGlvbiB7XG4gICAgbWFyZ2luOiAwIGF1dG87XG4gICAgcGFkZGluZy10b3A6IDIwMHB4O1xuICAgIHdpZHRoOiA3MCU7XG4gIH1cblxuICAucXVvdGUge1xuICAgIGZvbnQtZmFtaWx5OiBcIkxpYnJlIEJhc2tlcnZpbGxlXCIsIEdlb3JnaWEsIHNlcmlmO1xuICB9XG5cbiAgLmJ0blB1c2g6aG92ZXIge1xuICAgIG1hcmdpbi10b3A6IDE1cHg7XG4gICAgbWFyZ2luLWJvdHRvbTogNXB4O1xuICB9XG5cbiAgLmJ0bkJsdWVHcmVlbi5idG5QdXNoOmhvdmVyIHtcbiAgICBib3gtc2hhZG93OiAwcHggMHB4IDBweCAwcHggIzAwNzE0NDtcbiAgfVxuXG4gIGEsXG4gIGE6dmlzaXRlZCB7XG4gICAgdGV4dC1kZWNvcmF0aW9uOiBub25lO1xuICAgIGNvbG9yOiAjMDBhZTY4O1xuICB9XG5cbiAgYS5idXR0b24ge1xuICAgIC8qIGRpc3BsYXk6IGJsb2NrO1xuICAgIHBvc2l0aW9uOiByZWxhdGl2ZTsgXG4gICAgZmxvYXQ6IGxlZnQ7Ki9cbiAgICB3aWR0aDogMTIwcHg7XG4gICAgcGFkZGluZzogMTBweCA1MHB4IDEwcHggNTBweDtcbiAgICBmb250LXdlaWdodDogNjAwO1xuICAgIHRleHQtYWxpZ246IGNlbnRlcjtcbiAgICBsaW5lLWhlaWdodDogNTBweDtcbiAgICBjb2xvcjogI2ZmZjtcbiAgICBib3JkZXItcmFkaXVzOiA1cHg7XG4gICAgdHJhbnNpdGlvbjogYWxsIDAuMnM7XG4gIH1cblxuICAuYnRuQmx1ZUdyZWVuLmJ0blB1c2gge1xuICAgIGJveC1zaGFkb3c6IDBweCA1cHggMHB4IDBweCAjMDA3MTQ0O1xuICB9XG5cbiAgLmJ0bkJsdWVHcmVlbiB7XG4gICAgYmFja2dyb3VuZDogIzAwYWU2ODtcbiAgfVxuXG4gIC5idG5CbHVlR3JlZW4uYnRuUHVzaDpob3ZlciB7XG4gICAgYm94LXNoYWRvdzogMHB4IDBweCAwcHggMHB4ICMwMDcxNDQ7XG4gIH1cblxuICAuYnRuUHVzaDpob3ZlciB7XG4gICAgbWFyZ2luLXRvcDogMTVweDtcbiAgICBtYXJnaW4tYm90dG9tOiA1cHg7XG4gIH1cblxuICBoMSB7XG4gICAgZm9udC1zaXplOiAyLjhlbTtcbiAgICBmb250LXdlaWdodDogNzAwO1xuICAgIG1hcmdpbjogMCAwIDAuNWVtIDA7XG4gIH1cblxuICBmaWd1cmUge1xuICAgIG1hcmdpbjogMCAwIDFlbSAwO1xuICB9XG5cbiAgaW1nIHtcbiAgICB3aWR0aDogMTAwJTtcbiAgICBtYXgtd2lkdGg6IDE4MHB4O1xuICAgIG1hcmdpbjogMCAwIDFlbSAwO1xuICB9XG5cbiAgQG1lZGlhIChtaW4td2lkdGg6IDQ4MHB4KSB7XG4gICAgaDEge1xuICAgICAgZm9udC1zaXplOiA0ZW07XG4gICAgfVxuICB9XG48L3N0eWxlPlxuXG48c3ZlbHRlOmhlYWQ+XG4gIDx0aXRsZT5TYXBwZXIgcHJvamVjdCB0ZW1wbGF0ZTwvdGl0bGU+XG48L3N2ZWx0ZTpoZWFkPlxuPGRpdiBjbGFzcz1cImNhcHRpb25cIj5cbiAgPGgxPmZhbHNlIHF1b3RlcyBnZW5lcmF0b3I8L2gxPlxuPC9kaXY+XG5cbjxkaXY+XG4gIDxmaWd1cmU+XG4gICAgPGltZyBhbHQ9XCJCb3JhdFwiIHNyYz1cInF1b3RlLnBuZ1wiIC8+XG4gICAgPGZpZ2NhcHRpb24+PHA+e3F1b3RlfTwvcD48cD57Y2VsZWJyaXR5fTwvcD48L2ZpZ2NhcHRpb24+XG4gIDwvZmlndXJlPlxuICA8c3Bhbj5cbiAgICA8YVxuICAgICAgb246Y2xpY2s9e2hhbmRsZUNsaWNrfVxuICAgICAgaHJlZj1cIlwiXG4gICAgICB0aXRsZT1cIkJ1dHRvbiBwdXNoIGJsdWUvZ3JlZW5cIlxuICAgICAgY2xhc3M9XCJidXR0b24gYnRuUHVzaCBidG5CbHVlR3JlZW5cIj5cbiAgICAgIEdPIVxuICAgIDwvYT5cbiAgPC9zcGFuPlxuPC9kaXY+XG4iXSwic291cmNlUm9vdCI6IiJ9