(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["index"],{

/***/ "./src/helpers.js":
/*!************************!*\
  !*** ./src/helpers.js ***!
  \************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "default", function() { return timeoutPromise; });
function timeoutPromise(ms, promise) {
    return new Promise((resolve, reject) => {
      const timeoutId = setTimeout(() => {
        reject(new Error("promise timeout"))
      }, ms);
      promise.then(
        (res) => {
          clearTimeout(timeoutId);
          resolve(res);
        },
        (err) => {
          clearTimeout(timeoutId);
          reject(err);
        }
      );
    })
  }

/***/ }),

/***/ "./src/routes/index.svelte":
/*!*********************************!*\
  !*** ./src/routes/index.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal.mjs");
/* harmony import */ var _helpers__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../helpers */ "./src/helpers.js");
/* src/routes/index.svelte generated by Svelte v3.2.0 */



const file = "src/routes/index.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = 'svelte-10zejvu-style';
	style.textContent = "h1.svelte-10zejvu,figure.svelte-10zejvu,div.svelte-10zejvu,p.svelte-10zejvu{text-align:center;margin:0 auto}.caption.svelte-10zejvu{margin:0 auto;padding-top:2.5em;width:70%}.quote.svelte-10zejvu{width:70%;font-size:1.8em;font-family:\"Libre Baskerville\", Georgia, serif;font-style:italic}.celebrity.svelte-10zejvu{width:70%;text-align:right !important}.btnPush.svelte-10zejvu:hover{margin-top:15px;margin-bottom:5px}.btnBlueGreen.btnPush.svelte-10zejvu:hover{box-shadow:0px 0px 0px 0px #007144}a.svelte-10zejvu,a.svelte-10zejvu:visited{text-decoration:none;color:#00ae68}a.button.svelte-10zejvu{width:120px;padding:10px 50px 10px 50px;font-weight:600;text-align:center;line-height:50px;color:#fff;border-radius:5px;transition:all 0.2s}.btnBlueGreen.btnPush.svelte-10zejvu{box-shadow:0px 5px 0px 0px #007144}.btnBlueGreen.svelte-10zejvu{background:#00ae68}.btnBlueGreen.btnPush.svelte-10zejvu:hover{box-shadow:0px 0px 0px 0px #007144}.btnPush.svelte-10zejvu:hover{margin-top:15px;margin-bottom:5px}h1.svelte-10zejvu{font-size:2.8em;font-weight:700;margin:0 0 0.5em 0}figure.svelte-10zejvu{margin:0 0 1em 0}.quote-img.svelte-10zejvu{width:100%;max-width:80px;margin:0 0 1em 0}.load-img.svelte-10zejvu{width:100%;max-width:30px;margin:0 0 1em 0}@media(min-width: 480px){h1.svelte-10zejvu{font-size:4em}}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguc3ZlbHRlIiwic291cmNlcyI6WyJpbmRleC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgaW1wb3J0IHRpbWVvdXRQcm9taXNlIGZyb20gXCIuLi9oZWxwZXJzXCI7XG5cbiAgbGV0IHF1b3RlID0gXCJcIjtcbiAgbGV0IGNlbGVicml0eSA9IFwiXCI7XG4gIGxldCBsb2FkaW5nID0gZmFsc2U7XG4gIGxldCBlcnJvciA9IFwiXCI7XG5cbiAgYXN5bmMgZnVuY3Rpb24gZ2V0UXVvdGUoKSB7XG4gICAgcXVvdGUgPSBcIlwiO1xuICAgIGNlbGVicml0eSA9IFwiXCI7XG4gICAgZXJyb3IgPSBcIlwiO1xuICAgIHZhciB1cmx5ID0gXCJodHRwOi8vbG9jYWxob3N0OjMzMzMvcXVvdGVcIjtcbiAgICB0cnkge1xuICAgICAgbGV0IHJlc3BvbnNlID0gYXdhaXQgdGltZW91dFByb21pc2UoMTAgKiA2MCAqIDEwMDAsIGZldGNoKHVybHkpKTtcbiAgICAgIGxldCBkYXRhID0gYXdhaXQgcmVzcG9uc2UuanNvbigpO1xuICAgICAgY29uc29sZS5sb2coZGF0YSk7XG4gICAgICBxdW90ZSA9IGRhdGE7XG4gICAgfSBjYXRjaCAoZXJyb3IpIHtcbiAgICAgIGVycm9yID0gZXJyb3I7XG4gICAgICBjb25zb2xlLmVycm9yKGVycm9yKTtcbiAgICB9XG4gIH1cbiAgYXN5bmMgZnVuY3Rpb24gZ2V0Q2VsZWJyaXR5KCkge1xuICAgIHZhciB1cmx5ID0gXCJodHRwOi8vbG9jYWxob3N0OjMzMzMvY2VsZWJyaXR5XCI7XG4gICAgdHJ5IHtcbiAgICAgIGxldCByZXNwb25zZSA9IGF3YWl0IHRpbWVvdXRQcm9taXNlKDUwMDAsIGZldGNoKHVybHkpKTtcbiAgICAgIGxldCBkYXRhID0gYXdhaXQgcmVzcG9uc2UuanNvbigpO1xuICAgICAgY29uc29sZS5sb2coZGF0YSk7XG4gICAgICBjZWxlYnJpdHkgPSBkYXRhO1xuICAgIH0gY2F0Y2ggKGVycm9yKSB7XG4gICAgICBlcnJvciA9IGVycm9yO1xuICAgICAgY29uc29sZS5lcnJvcihlcnJvcik7XG4gICAgfVxuICB9XG4gIGFzeW5jIGZ1bmN0aW9uIGhhbmRsZUNsaWNrKGV2ZW50KSB7XG4gICAgZXZlbnQucHJldmVudERlZmF1bHQoKTtcbiAgICBsb2FkaW5nID0gdHJ1ZTtcbiAgICBhd2FpdCBnZXRRdW90ZSgpO1xuICAgIGF3YWl0IGdldENlbGVicml0eSgpO1xuICAgIGxvYWRpbmcgPSBmYWxzZTtcbiAgfVxuXG4gIGZ1bmN0aW9uIHByZWxvYWQoeyBwYXJhbXMsIHF1ZXJ5IH0pIHtcbiAgICAvLyBub3RoaW5nIHRvZG9cbiAgfVxuPC9zY3JpcHQ+XG5cbjxzdHlsZT5cbiAgaDEsXG4gIGZpZ3VyZSxcbiAgZGl2LFxuICBwIHtcbiAgICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gICAgbWFyZ2luOiAwIGF1dG87XG4gIH1cblxuICAuY2FwdGlvbiB7XG4gICAgbWFyZ2luOiAwIGF1dG87XG4gICAgcGFkZGluZy10b3A6IDIuNWVtO1xuICAgIHdpZHRoOiA3MCU7XG4gIH1cblxuICAucXVvdGUge1xuICAgIHdpZHRoOiA3MCU7XG4gICAgZm9udC1zaXplOiAxLjhlbTtcbiAgICBmb250LWZhbWlseTogXCJMaWJyZSBCYXNrZXJ2aWxsZVwiLCBHZW9yZ2lhLCBzZXJpZjtcbiAgICBmb250LXN0eWxlOiBpdGFsaWM7XG4gIH1cblxuICAuY2VsZWJyaXR5IHtcbiAgICB3aWR0aDogNzAlO1xuICAgIHRleHQtYWxpZ246IHJpZ2h0ICFpbXBvcnRhbnQ7XG4gIH1cblxuICAuYnRuUHVzaDpob3ZlciB7XG4gICAgbWFyZ2luLXRvcDogMTVweDtcbiAgICBtYXJnaW4tYm90dG9tOiA1cHg7XG4gIH1cblxuICAuYnRuQmx1ZUdyZWVuLmJ0blB1c2g6aG92ZXIge1xuICAgIGJveC1zaGFkb3c6IDBweCAwcHggMHB4IDBweCAjMDA3MTQ0O1xuICB9XG5cbiAgYSxcbiAgYTp2aXNpdGVkIHtcbiAgICB0ZXh0LWRlY29yYXRpb246IG5vbmU7XG4gICAgY29sb3I6ICMwMGFlNjg7XG4gIH1cblxuICBhLmJ1dHRvbiB7XG4gICAgLyogZGlzcGxheTogYmxvY2s7XG4gICAgcG9zaXRpb246IHJlbGF0aXZlOyBcbiAgICBmbG9hdDogbGVmdDsqL1xuICAgIHdpZHRoOiAxMjBweDtcbiAgICBwYWRkaW5nOiAxMHB4IDUwcHggMTBweCA1MHB4O1xuICAgIGZvbnQtd2VpZ2h0OiA2MDA7XG4gICAgdGV4dC1hbGlnbjogY2VudGVyO1xuICAgIGxpbmUtaGVpZ2h0OiA1MHB4O1xuICAgIGNvbG9yOiAjZmZmO1xuICAgIGJvcmRlci1yYWRpdXM6IDVweDtcbiAgICB0cmFuc2l0aW9uOiBhbGwgMC4ycztcbiAgfVxuXG4gIC5idG5CbHVlR3JlZW4uYnRuUHVzaCB7XG4gICAgYm94LXNoYWRvdzogMHB4IDVweCAwcHggMHB4ICMwMDcxNDQ7XG4gIH1cblxuICAuYnRuQmx1ZUdyZWVuIHtcbiAgICBiYWNrZ3JvdW5kOiAjMDBhZTY4O1xuICB9XG5cbiAgLmJ0bkJsdWVHcmVlbi5idG5QdXNoOmhvdmVyIHtcbiAgICBib3gtc2hhZG93OiAwcHggMHB4IDBweCAwcHggIzAwNzE0NDtcbiAgfVxuXG4gIC5idG5QdXNoOmhvdmVyIHtcbiAgICBtYXJnaW4tdG9wOiAxNXB4O1xuICAgIG1hcmdpbi1ib3R0b206IDVweDtcbiAgfVxuXG4gIGgxIHtcbiAgICBmb250LXNpemU6IDIuOGVtO1xuICAgIGZvbnQtd2VpZ2h0OiA3MDA7XG4gICAgbWFyZ2luOiAwIDAgMC41ZW0gMDtcbiAgfVxuXG4gIGZpZ3VyZSB7XG4gICAgbWFyZ2luOiAwIDAgMWVtIDA7XG4gIH1cblxuICAucXVvdGUtaW1nIHtcbiAgICB3aWR0aDogMTAwJTtcbiAgICBtYXgtd2lkdGg6IDgwcHg7XG4gICAgbWFyZ2luOiAwIDAgMWVtIDA7XG4gIH1cblxuICAubG9hZC1pbWcge1xuICAgIHdpZHRoOiAxMDAlO1xuICAgIG1heC13aWR0aDogMzBweDtcbiAgICBtYXJnaW46IDAgMCAxZW0gMDtcbiAgfVxuXG4gIEBtZWRpYSAobWluLXdpZHRoOiA0ODBweCkge1xuICAgIGgxIHtcbiAgICAgIGZvbnQtc2l6ZTogNGVtO1xuICAgIH1cbiAgfVxuPC9zdHlsZT5cblxuPHN2ZWx0ZTpoZWFkPlxuICA8dGl0bGU+U2FwcGVyIHByb2plY3QgdGVtcGxhdGU8L3RpdGxlPlxuPC9zdmVsdGU6aGVhZD5cbjxkaXYgaWQ9XCJ3cmFwcGVyXCI+XG4gIDxkaXYgaWQ9XCJjb250ZW50XCI+XG4gICAgPGRpdiBpZD1cImNlbnRlclwiPlxuICAgICAgPGRpdiBjbGFzcz1cImNhcHRpb25cIj5cbiAgICAgICAgPGgxPmZhbHNlIHF1b3RlcyBnZW5lcmF0b3I8L2gxPlxuICAgICAgPC9kaXY+XG5cblxuICAgICAgPGRpdj5cbiAgICAgICAgPGZpZ3VyZT5cbiAgICAgICAgICA8aW1nIGNsYXNzPVwicXVvdGUtaW1nXCIgYWx0PVwiUXVvdGVcIiBzcmM9XCJxdW90ZS5wbmdcIiAvPlxuICAgICAgICAgIHsjaWYgbG9hZGluZ31cbiAgICAgICAgICAgIDxmaWdjYXB0aW9uPlxuICAgICAgICAgICAgICA8cD5cbiAgICAgICAgICAgICAgICA8aW1nIGNsYXNzPVwibG9hZC1pbWdcIiBhbHQ9XCJMb2FkaW5nXCIgc3JjPVwiYWpheC1sb2FkZXIuZ2lmXCIgLz5cbiAgICAgICAgICAgICAgPC9wPlxuICAgICAgICAgICAgPC9maWdjYXB0aW9uPlxuICAgICAgICAgIHsvaWZ9XG4gICAgICAgICAgeyNpZiBlcnJvcn1cbiAgICAgICAgICAgIDxmaWdjYXB0aW9uPlxuICAgICAgICAgICAgICA8cD5PVUNIISBTb21ldGhpbmcgd2VudCB3cm9uZy4gOig8L3A+XG4gICAgICAgICAgICA8L2ZpZ2NhcHRpb24+XG4gICAgICAgICAgey9pZn1cbiAgICAgICAgICB7I2lmICFsb2FkaW5nICYmIHF1b3RlICYmIGNlbGVicml0eX1cbiAgICAgICAgICAgIDxmaWdjYXB0aW9uPlxuICAgICAgICAgICAgICA8cCBjbGFzcz1cInF1b3RlXCI+e3F1b3RlfTwvcD5cbiAgICAgICAgICAgICAgPHAgY2xhc3M9XCJjZWxlYnJpdHlcIj4tIHtjZWxlYnJpdHl9PC9wPlxuICAgICAgICAgICAgPC9maWdjYXB0aW9uPlxuICAgICAgICAgIHsvaWZ9XG4gICAgICAgIDwvZmlndXJlPlxuICAgICAgICA8c3Bhbj5cbiAgICAgICAgICA8YVxuICAgICAgICAgICAgb246Y2xpY2s9e2hhbmRsZUNsaWNrfVxuICAgICAgICAgICAgaHJlZj1cImh0dHBzOi8vcmlrZS5kZXZcIlxuICAgICAgICAgICAgdGl0bGU9XCJCdXR0b24gcHVzaCBibHVlL2dyZWVuXCJcbiAgICAgICAgICAgIGNsYXNzPVwiYnV0dG9uIGJ0blB1c2ggYnRuQmx1ZUdyZWVuXCI+XG4gICAgICAgICAgICBHTyFcbiAgICAgICAgICA8L2E+XG4gICAgICAgIDwvc3Bhbj5cbiAgICAgIDwvZGl2PlxuICAgIDwvZGl2PlxuICA8L2Rpdj5cbiAgPGZvb3Rlcj5cbiAgICBNYWRlIHdpdGgg4pmlIGFuZFxuICAgIDxhIGhyZWY9XCJodHRwOi8vc3ZlbHRlLmRldlwiIHRhcmdldD1cIl9ibGFua1wiPlN2ZWx0ZS5qczwvYT5cbiAgICBieVxuICAgIDxhIGhyZWY9XCJodHRwczovL3Jpa2UuZGV2XCIgdGFyZ2V0PVwiX2JsYW5rXCI+UmlrZTwvYT5cbiAgICBpbiAyMDE5LlxuICA8L2Zvb3Rlcj5cbjwvZGl2PlxuIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQWlERSxpQkFBRSxDQUNGLHFCQUFNLENBQ04sa0JBQUcsQ0FDSCxDQUFDLGVBQUMsQ0FBQyxBQUNELFVBQVUsQ0FBRSxNQUFNLENBQ2xCLE1BQU0sQ0FBRSxDQUFDLENBQUMsSUFBSSxBQUNoQixDQUFDLEFBRUQsUUFBUSxlQUFDLENBQUMsQUFDUixNQUFNLENBQUUsQ0FBQyxDQUFDLElBQUksQ0FDZCxXQUFXLENBQUUsS0FBSyxDQUNsQixLQUFLLENBQUUsR0FBRyxBQUNaLENBQUMsQUFFRCxNQUFNLGVBQUMsQ0FBQyxBQUNOLEtBQUssQ0FBRSxHQUFHLENBQ1YsU0FBUyxDQUFFLEtBQUssQ0FDaEIsV0FBVyxDQUFFLG1CQUFtQixDQUFDLENBQUMsT0FBTyxDQUFDLENBQUMsS0FBSyxDQUNoRCxVQUFVLENBQUUsTUFBTSxBQUNwQixDQUFDLEFBRUQsVUFBVSxlQUFDLENBQUMsQUFDVixLQUFLLENBQUUsR0FBRyxDQUNWLFVBQVUsQ0FBRSxLQUFLLENBQUMsVUFBVSxBQUM5QixDQUFDLEFBRUQsdUJBQVEsTUFBTSxBQUFDLENBQUMsQUFDZCxVQUFVLENBQUUsSUFBSSxDQUNoQixhQUFhLENBQUUsR0FBRyxBQUNwQixDQUFDLEFBRUQsYUFBYSx1QkFBUSxNQUFNLEFBQUMsQ0FBQyxBQUMzQixVQUFVLENBQUUsR0FBRyxDQUFDLEdBQUcsQ0FBQyxHQUFHLENBQUMsR0FBRyxDQUFDLE9BQU8sQUFDckMsQ0FBQyxBQUVELGdCQUFDLENBQ0QsZ0JBQUMsUUFBUSxBQUFDLENBQUMsQUFDVCxlQUFlLENBQUUsSUFBSSxDQUNyQixLQUFLLENBQUUsT0FBTyxBQUNoQixDQUFDLEFBRUQsQ0FBQyxPQUFPLGVBQUMsQ0FBQyxBQUlSLEtBQUssQ0FBRSxLQUFLLENBQ1osT0FBTyxDQUFFLElBQUksQ0FBQyxJQUFJLENBQUMsSUFBSSxDQUFDLElBQUksQ0FDNUIsV0FBVyxDQUFFLEdBQUcsQ0FDaEIsVUFBVSxDQUFFLE1BQU0sQ0FDbEIsV0FBVyxDQUFFLElBQUksQ0FDakIsS0FBSyxDQUFFLElBQUksQ0FDWCxhQUFhLENBQUUsR0FBRyxDQUNsQixVQUFVLENBQUUsR0FBRyxDQUFDLElBQUksQUFDdEIsQ0FBQyxBQUVELGFBQWEsUUFBUSxlQUFDLENBQUMsQUFDckIsVUFBVSxDQUFFLEdBQUcsQ0FBQyxHQUFHLENBQUMsR0FBRyxDQUFDLEdBQUcsQ0FBQyxPQUFPLEFBQ3JDLENBQUMsQUFFRCxhQUFhLGVBQUMsQ0FBQyxBQUNiLFVBQVUsQ0FBRSxPQUFPLEFBQ3JCLENBQUMsQUFFRCxhQUFhLHVCQUFRLE1BQU0sQUFBQyxDQUFDLEFBQzNCLFVBQVUsQ0FBRSxHQUFHLENBQUMsR0FBRyxDQUFDLEdBQUcsQ0FBQyxHQUFHLENBQUMsT0FBTyxBQUNyQyxDQUFDLEFBRUQsdUJBQVEsTUFBTSxBQUFDLENBQUMsQUFDZCxVQUFVLENBQUUsSUFBSSxDQUNoQixhQUFhLENBQUUsR0FBRyxBQUNwQixDQUFDLEFBRUQsRUFBRSxlQUFDLENBQUMsQUFDRixTQUFTLENBQUUsS0FBSyxDQUNoQixXQUFXLENBQUUsR0FBRyxDQUNoQixNQUFNLENBQUUsQ0FBQyxDQUFDLENBQUMsQ0FBQyxLQUFLLENBQUMsQ0FBQyxBQUNyQixDQUFDLEFBRUQsTUFBTSxlQUFDLENBQUMsQUFDTixNQUFNLENBQUUsQ0FBQyxDQUFDLENBQUMsQ0FBQyxHQUFHLENBQUMsQ0FBQyxBQUNuQixDQUFDLEFBRUQsVUFBVSxlQUFDLENBQUMsQUFDVixLQUFLLENBQUUsSUFBSSxDQUNYLFNBQVMsQ0FBRSxJQUFJLENBQ2YsTUFBTSxDQUFFLENBQUMsQ0FBQyxDQUFDLENBQUMsR0FBRyxDQUFDLENBQUMsQUFDbkIsQ0FBQyxBQUVELFNBQVMsZUFBQyxDQUFDLEFBQ1QsS0FBSyxDQUFFLElBQUksQ0FDWCxTQUFTLENBQUUsSUFBSSxDQUNmLE1BQU0sQ0FBRSxDQUFDLENBQUMsQ0FBQyxDQUFDLEdBQUcsQ0FBQyxDQUFDLEFBQ25CLENBQUMsQUFFRCxNQUFNLEFBQUMsWUFBWSxLQUFLLENBQUMsQUFBQyxDQUFDLEFBQ3pCLEVBQUUsZUFBQyxDQUFDLEFBQ0YsU0FBUyxDQUFFLEdBQUcsQUFDaEIsQ0FBQyxBQUNILENBQUMifQ== */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(document.head, style);
}

// (165:10) {#if loading}
function create_if_block_2(ctx) {
	var figcaption, p, img;

	return {
		c: function create() {
			figcaption = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("figcaption");
			p = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			img = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			this.h()
		},

		l: function claim(nodes) {
			figcaption = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "FIGCAPTION", {}, false);
			var figcaption_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(figcaption);

			p = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(figcaption_nodes, "P", { class: true }, false);
			var p_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p);

			img = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p_nodes, "IMG", { class: true, alt: true, src: true }, false);
			var img_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(img);

			img_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			p_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			figcaption_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			img.className = "load-img svelte-10zejvu";
			img.alt = "Loading";
			img.src = "ajax-loader.gif";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img, file, 167, 16, 2951);
			p.className = "svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p, file, 166, 14, 2931);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(figcaption, file, 165, 12, 2904);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, figcaption, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figcaption, p);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p, img);
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(figcaption);
			}
		}
	};
}

// (172:10) {#if error}
function create_if_block_1(ctx) {
	var figcaption, p, t;

	return {
		c: function create() {
			figcaption = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("figcaption");
			p = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("OUCH! Something went wrong. :(");
			this.h()
		},

		l: function claim(nodes) {
			figcaption = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "FIGCAPTION", {}, false);
			var figcaption_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(figcaption);

			p = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(figcaption_nodes, "P", { class: true }, false);
			var p_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p);

			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p_nodes, "OUCH! Something went wrong. :(");
			p_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			figcaption_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			p.className = "svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p, file, 173, 14, 3134);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(figcaption, file, 172, 12, 3107);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, figcaption, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figcaption, p);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p, t);
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(figcaption);
			}
		}
	};
}

// (177:10) {#if !loading && quote && celebrity}
function create_if_block(ctx) {
	var figcaption, p0, t0, t1, p1, t2, t3;

	return {
		c: function create() {
			figcaption = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("figcaption");
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(ctx.quote);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("- ");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(ctx.celebrity);
			this.h()
		},

		l: function claim(nodes) {
			figcaption = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "FIGCAPTION", {}, false);
			var figcaption_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(figcaption);

			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(figcaption_nodes, "P", { class: true }, false);
			var p0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p0);

			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, ctx.quote);
			p0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(figcaption_nodes, "\n              ");

			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(figcaption_nodes, "P", { class: true }, false);
			var p1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p1);

			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "- ");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, ctx.celebrity);
			p1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			figcaption_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			p0.className = "quote svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p0, file, 178, 14, 3300);
			p1.className = "celebrity svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p1, file, 179, 14, 3343);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(figcaption, file, 177, 12, 3273);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, figcaption, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figcaption, p0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p0, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figcaption, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figcaption, p1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, t3);
		},

		p: function update(changed, ctx) {
			if (changed.quote) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t0, ctx.quote);
			}

			if (changed.celebrity) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t3, ctx.celebrity);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(figcaption);
			}
		}
	};
}

function create_fragment(ctx) {
	var t0, div4, div3, div2, div0, h1, t1, t2, div1, figure, img, t3, t4, t5, t6, span, a0, t7, t8, footer, t9, a1, t10, t11, a2, t12, t13, dispose;

	var if_block0 = (ctx.loading) && create_if_block_2(ctx);

	var if_block1 = (ctx.error) && create_if_block_1(ctx);

	var if_block2 = (!ctx.loading && ctx.quote && ctx.celebrity) && create_if_block(ctx);

	return {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h1");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("false quotes generator");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			figure = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("figure");
			img = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if (if_block0) if_block0.c();
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if (if_block1) if_block1.c();
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if (if_block2) if_block2.c();
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			a0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("GO!");
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			footer = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("footer");
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Made with ♥ and\n    ");
			a1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Svelte.js");
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\n    by\n    ");
			a2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Rike");
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\n    in 2019.");
			this.h()
		},

		l: function claim(nodes) {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n");

			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { id: true, class: true }, false);
			var div4_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div4);

			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "DIV", { id: true, class: true }, false);
			var div3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div3);

			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div3_nodes, "DIV", { id: true, class: true }, false);
			var div2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div2);

			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "DIV", { class: true }, false);
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);

			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div0_nodes, "H1", { class: true }, false);
			var h1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h1);

			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h1_nodes, "false quotes generator");
			h1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div2_nodes, "\n\n\n      ");

			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "DIV", { class: true }, false);
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);

			figure = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "FIGURE", { class: true }, false);
			var figure_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(figure);

			img = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(figure_nodes, "IMG", { class: true, alt: true, src: true }, false);
			var img_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(img);

			img_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(figure_nodes, "\n          ");
			if (if_block0) if_block0.l(figure_nodes);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(figure_nodes, "\n          ");
			if (if_block1) if_block1.l(figure_nodes);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(figure_nodes, "\n          ");
			if (if_block2) if_block2.l(figure_nodes);
			figure_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div1_nodes, "\n        ");

			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "SPAN", {}, false);
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);

			a0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span_nodes, "A", { href: true, title: true, class: true }, false);
			var a0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a0);

			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a0_nodes, "GO!");
			a0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div4_nodes, "\n  ");

			footer = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "FOOTER", {}, false);
			var footer_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(footer);

			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(footer_nodes, "Made with ♥ and\n    ");

			a1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(footer_nodes, "A", { href: true, target: true, class: true }, false);
			var a1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a1);

			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a1_nodes, "Svelte.js");
			a1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(footer_nodes, "\n    by\n    ");

			a2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(footer_nodes, "A", { href: true, target: true, class: true }, false);
			var a2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a2);

			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a2_nodes, "Rike");
			a2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(footer_nodes, "\n    in 2019.");
			footer_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div4_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			document.title = "Sapper project template";
			h1.className = "svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h1, file, 157, 8, 2728);
			div0.className = "caption svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 156, 6, 2698);
			img.className = "quote-img svelte-10zejvu";
			img.alt = "Quote";
			img.src = "quote.png";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img, file, 163, 10, 2814);
			figure.className = "svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(figure, file, 162, 8, 2795);
			a0.href = "https://rike.dev";
			a0.title = "Button push blue/green";
			a0.className = "button btnPush btnBlueGreen svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a0, file, 184, 10, 3467);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 183, 8, 3450);
			div1.className = "svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 161, 6, 2781);
			div2.id = "center";
			div2.className = "svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div2, file, 155, 4, 2674);
			div3.id = "content";
			div3.className = "svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div3, file, 154, 2, 2651);
			a1.href = "http://svelte.dev";
			a1.target = "_blank";
			a1.className = "svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a1, file, 197, 4, 3748);
			a2.href = "https://rike.dev";
			a2.target = "_blank";
			a2.className = "svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a2, file, 199, 4, 3817);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(footer, file, 195, 2, 3715);
			div4.id = "wrapper";
			div4.className = "svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div4, file, 153, 0, 2630);
			dispose = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen"])(a0, "click", ctx.handleClick);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, div4, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, div3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div3, div2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, div0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div0, h1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(h1, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, div1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, figure);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figure, img);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figure, t3);
			if (if_block0) if_block0.m(figure, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figure, t4);
			if (if_block1) if_block1.m(figure, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figure, t5);
			if (if_block2) if_block2.m(figure, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, span);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span, a0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(a0, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, t8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, footer);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(footer, t9);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(footer, a1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(a1, t10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(footer, t11);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(footer, a2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(a2, t12);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(footer, t13);
		},

		p: function update(changed, ctx) {
			if (ctx.loading) {
				if (!if_block0) {
					if_block0 = create_if_block_2(ctx);
					if_block0.c();
					if_block0.m(figure, t4);
				}
			} else if (if_block0) {
				if_block0.d(1);
				if_block0 = null;
			}

			if (ctx.error) {
				if (!if_block1) {
					if_block1 = create_if_block_1(ctx);
					if_block1.c();
					if_block1.m(figure, t5);
				}
			} else if (if_block1) {
				if_block1.d(1);
				if_block1 = null;
			}

			if (!ctx.loading && ctx.quote && ctx.celebrity) {
				if (if_block2) {
					if_block2.p(changed, ctx);
				} else {
					if_block2 = create_if_block(ctx);
					if_block2.c();
					if_block2.m(figure, null);
				}
			} else if (if_block2) {
				if_block2.d(1);
				if_block2 = null;
			}
		},

		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t0);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(div4);
			}

			if (if_block0) if_block0.d();
			if (if_block1) if_block1.d();
			if (if_block2) if_block2.d();
			dispose();
		}
	};
}

function preload({ params, query }) {
  // nothing todo
}

function instance($$self, $$props, $$invalidate) {
	let quote = "";
  let celebrity = "";
  let loading = false;
  let error = "";

  async function getQuote() {
    $$invalidate('quote', quote = "");
    $$invalidate('celebrity', celebrity = "");
    $$invalidate('error', error = "");
    var urly = "http://localhost:3333/quote";
    try {
      let response = await Object(_helpers__WEBPACK_IMPORTED_MODULE_1__["default"])(10 * 60 * 1000, fetch(urly));
      let data = await response.json();
      console.log(data);
      $$invalidate('quote', quote = data);
    } catch (error) {
      $$invalidate('error', error);
      console.error(error);
    }
  }
  async function getCelebrity() {
    var urly = "http://localhost:3333/celebrity";
    try {
      let response = await Object(_helpers__WEBPACK_IMPORTED_MODULE_1__["default"])(5000, fetch(urly));
      let data = await response.json();
      console.log(data);
      $$invalidate('celebrity', celebrity = data);
    } catch (error) {
      $$invalidate('error', error);
      console.error(error);
    }
  }
  async function handleClick(event) {
    event.preventDefault();
    $$invalidate('loading', loading = true);
    await getQuote();
    await getCelebrity();
    $$invalidate('loading', loading = false);
  }

	return {
		quote,
		celebrity,
		loading,
		error,
		handleClick
	};
}

class Routes extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-10zejvu-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], []);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Routes);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvaGVscGVycy5qcyIsIndlYnBhY2s6Ly8vLi9zcmMvcm91dGVzL2luZGV4LnN2ZWx0ZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7O0FBQUE7QUFBQTtBQUFlO0FBQ2Y7QUFDQTtBQUNBO0FBQ0EsT0FBTztBQUNQO0FBQ0E7QUFDQTtBQUNBO0FBQ0EsU0FBUztBQUNUO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQSxLQUFLO0FBQ0wsRzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt5RUNrS2dDLEtBQUs7Ozs7eUVBQ0MsU0FBUzs7Ozs7Ozs7Ozs7eUZBRGYsS0FBSzs7Ozs7Ozs7eUZBQ0MsU0FBUzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7NkVBRGYsS0FBSzs7Ozs2RUFDQyxTQUFTOzs7Ozs7Ozs7Ozs7Ozs7c0JBZmhDLE9BQU87O3NCQU9QLEtBQUs7O2tCQUtMLEtBQUMsT0FBTyxRQUFJLEtBQUssUUFBSSxTQUFTOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7NkZBU3ZCLFdBQVc7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7V0FyQmxCLE9BQU87Ozs7Ozs7Ozs7O1dBT1AsS0FBSzs7Ozs7Ozs7Ozs7T0FLTCxLQUFDLE9BQU8sUUFBSSxLQUFLLFFBQUksU0FBUzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQXJJM0MsU0FBUyxPQUFPLENBQUMsRUFBRSxNQUFNLEVBQUUsS0FBSyxFQUFFLEVBQUU7QUFDcEM7QUFDQSxDQUFDOzs7Q0ExQ0QsSUFBSSxLQUFLLEdBQUcsRUFBRSxDQUFDO0VBQ2YsSUFBSSxTQUFTLEdBQUcsRUFBRSxDQUFDO0VBQ25CLElBQUksT0FBTyxHQUFHLEtBQUssQ0FBQztFQUNwQixJQUFJLEtBQUssR0FBRyxFQUFFLENBQUM7O0VBRWYsZUFBZSxRQUFRLEdBQUc7MEJBQ3hCLEtBQUssR0FBRyxHQUFFLENBQUM7OEJBQ1gsU0FBUyxHQUFHLEdBQUUsQ0FBQzswQkFDZixLQUFLLEdBQUcsR0FBRSxDQUFDO0lBQ1gsSUFBSSxJQUFJLEdBQUcsNkJBQTZCLENBQUM7SUFDekMsSUFBSTtNQUNGLElBQUksUUFBUSxHQUFHLE1BQU0sd0RBQWMsQ0FBQyxFQUFFLEdBQUcsRUFBRSxHQUFHLElBQUksRUFBRSxLQUFLLENBQUMsSUFBSSxDQUFDLENBQUMsQ0FBQztNQUNqRSxJQUFJLElBQUksR0FBRyxNQUFNLFFBQVEsQ0FBQyxJQUFJLEVBQUUsQ0FBQztNQUNqQyxPQUFPLENBQUMsR0FBRyxDQUFDLElBQUksQ0FBQyxDQUFDOzRCQUNsQixLQUFLLEdBQUcsS0FBSSxDQUFDO0tBQ2QsQ0FBQyxPQUFPLEtBQUssRUFBRTtNQUNkLDRCQUFhLENBQUM7TUFDZCxPQUFPLENBQUMsS0FBSyxDQUFDLEtBQUssQ0FBQyxDQUFDO0tBQ3RCO0dBQ0Y7RUFDRCxlQUFlLFlBQVksR0FBRztJQUM1QixJQUFJLElBQUksR0FBRyxpQ0FBaUMsQ0FBQztJQUM3QyxJQUFJO01BQ0YsSUFBSSxRQUFRLEdBQUcsTUFBTSx3REFBYyxDQUFDLElBQUksRUFBRSxLQUFLLENBQUMsSUFBSSxDQUFDLENBQUMsQ0FBQztNQUN2RCxJQUFJLElBQUksR0FBRyxNQUFNLFFBQVEsQ0FBQyxJQUFJLEVBQUUsQ0FBQztNQUNqQyxPQUFPLENBQUMsR0FBRyxDQUFDLElBQUksQ0FBQyxDQUFDO2dDQUNsQixTQUFTLEdBQUcsS0FBSSxDQUFDO0tBQ2xCLENBQUMsT0FBTyxLQUFLLEVBQUU7TUFDZCw0QkFBYSxDQUFDO01BQ2QsT0FBTyxDQUFDLEtBQUssQ0FBQyxLQUFLLENBQUMsQ0FBQztLQUN0QjtHQUNGO0VBQ0QsZUFBZSxXQUFXLENBQUMsS0FBSyxFQUFFO0lBQ2hDLEtBQUssQ0FBQyxjQUFjLEVBQUUsQ0FBQzs0QkFDdkIsT0FBTyxHQUFHLEtBQUksQ0FBQztJQUNmLE1BQU0sUUFBUSxFQUFFLENBQUM7SUFDakIsTUFBTSxZQUFZLEVBQUUsQ0FBQzs0QkFDckIsT0FBTyxHQUFHLE1BQUssQ0FBQztHQUNqQiIsImZpbGUiOiJhOWJlYjc3YmZlZjYyYzJmMmQyNy9pbmRleC5pbmRleC5qcyIsInNvdXJjZXNDb250ZW50IjpbImV4cG9ydCBkZWZhdWx0IGZ1bmN0aW9uIHRpbWVvdXRQcm9taXNlKG1zLCBwcm9taXNlKSB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IHRpbWVvdXRJZCA9IHNldFRpbWVvdXQoKCkgPT4ge1xuICAgICAgICByZWplY3QobmV3IEVycm9yKFwicHJvbWlzZSB0aW1lb3V0XCIpKVxuICAgICAgfSwgbXMpO1xuICAgICAgcHJvbWlzZS50aGVuKFxuICAgICAgICAocmVzKSA9PiB7XG4gICAgICAgICAgY2xlYXJUaW1lb3V0KHRpbWVvdXRJZCk7XG4gICAgICAgICAgcmVzb2x2ZShyZXMpO1xuICAgICAgICB9LFxuICAgICAgICAoZXJyKSA9PiB7XG4gICAgICAgICAgY2xlYXJUaW1lb3V0KHRpbWVvdXRJZCk7XG4gICAgICAgICAgcmVqZWN0KGVycik7XG4gICAgICAgIH1cbiAgICAgICk7XG4gICAgfSlcbiAgfSIsIjxzY3JpcHQ+XG4gIGltcG9ydCB0aW1lb3V0UHJvbWlzZSBmcm9tIFwiLi4vaGVscGVyc1wiO1xuXG4gIGxldCBxdW90ZSA9IFwiXCI7XG4gIGxldCBjZWxlYnJpdHkgPSBcIlwiO1xuICBsZXQgbG9hZGluZyA9IGZhbHNlO1xuICBsZXQgZXJyb3IgPSBcIlwiO1xuXG4gIGFzeW5jIGZ1bmN0aW9uIGdldFF1b3RlKCkge1xuICAgIHF1b3RlID0gXCJcIjtcbiAgICBjZWxlYnJpdHkgPSBcIlwiO1xuICAgIGVycm9yID0gXCJcIjtcbiAgICB2YXIgdXJseSA9IFwiaHR0cDovL2xvY2FsaG9zdDozMzMzL3F1b3RlXCI7XG4gICAgdHJ5IHtcbiAgICAgIGxldCByZXNwb25zZSA9IGF3YWl0IHRpbWVvdXRQcm9taXNlKDEwICogNjAgKiAxMDAwLCBmZXRjaCh1cmx5KSk7XG4gICAgICBsZXQgZGF0YSA9IGF3YWl0IHJlc3BvbnNlLmpzb24oKTtcbiAgICAgIGNvbnNvbGUubG9nKGRhdGEpO1xuICAgICAgcXVvdGUgPSBkYXRhO1xuICAgIH0gY2F0Y2ggKGVycm9yKSB7XG4gICAgICBlcnJvciA9IGVycm9yO1xuICAgICAgY29uc29sZS5lcnJvcihlcnJvcik7XG4gICAgfVxuICB9XG4gIGFzeW5jIGZ1bmN0aW9uIGdldENlbGVicml0eSgpIHtcbiAgICB2YXIgdXJseSA9IFwiaHR0cDovL2xvY2FsaG9zdDozMzMzL2NlbGVicml0eVwiO1xuICAgIHRyeSB7XG4gICAgICBsZXQgcmVzcG9uc2UgPSBhd2FpdCB0aW1lb3V0UHJvbWlzZSg1MDAwLCBmZXRjaCh1cmx5KSk7XG4gICAgICBsZXQgZGF0YSA9IGF3YWl0IHJlc3BvbnNlLmpzb24oKTtcbiAgICAgIGNvbnNvbGUubG9nKGRhdGEpO1xuICAgICAgY2VsZWJyaXR5ID0gZGF0YTtcbiAgICB9IGNhdGNoIChlcnJvcikge1xuICAgICAgZXJyb3IgPSBlcnJvcjtcbiAgICAgIGNvbnNvbGUuZXJyb3IoZXJyb3IpO1xuICAgIH1cbiAgfVxuICBhc3luYyBmdW5jdGlvbiBoYW5kbGVDbGljayhldmVudCkge1xuICAgIGV2ZW50LnByZXZlbnREZWZhdWx0KCk7XG4gICAgbG9hZGluZyA9IHRydWU7XG4gICAgYXdhaXQgZ2V0UXVvdGUoKTtcbiAgICBhd2FpdCBnZXRDZWxlYnJpdHkoKTtcbiAgICBsb2FkaW5nID0gZmFsc2U7XG4gIH1cblxuICBmdW5jdGlvbiBwcmVsb2FkKHsgcGFyYW1zLCBxdWVyeSB9KSB7XG4gICAgLy8gbm90aGluZyB0b2RvXG4gIH1cbjwvc2NyaXB0PlxuXG48c3R5bGU+XG4gIGgxLFxuICBmaWd1cmUsXG4gIGRpdixcbiAgcCB7XG4gICAgdGV4dC1hbGlnbjogY2VudGVyO1xuICAgIG1hcmdpbjogMCBhdXRvO1xuICB9XG5cbiAgLmNhcHRpb24ge1xuICAgIG1hcmdpbjogMCBhdXRvO1xuICAgIHBhZGRpbmctdG9wOiAyLjVlbTtcbiAgICB3aWR0aDogNzAlO1xuICB9XG5cbiAgLnF1b3RlIHtcbiAgICB3aWR0aDogNzAlO1xuICAgIGZvbnQtc2l6ZTogMS44ZW07XG4gICAgZm9udC1mYW1pbHk6IFwiTGlicmUgQmFza2VydmlsbGVcIiwgR2VvcmdpYSwgc2VyaWY7XG4gICAgZm9udC1zdHlsZTogaXRhbGljO1xuICB9XG5cbiAgLmNlbGVicml0eSB7XG4gICAgd2lkdGg6IDcwJTtcbiAgICB0ZXh0LWFsaWduOiByaWdodCAhaW1wb3J0YW50O1xuICB9XG5cbiAgLmJ0blB1c2g6aG92ZXIge1xuICAgIG1hcmdpbi10b3A6IDE1cHg7XG4gICAgbWFyZ2luLWJvdHRvbTogNXB4O1xuICB9XG5cbiAgLmJ0bkJsdWVHcmVlbi5idG5QdXNoOmhvdmVyIHtcbiAgICBib3gtc2hhZG93OiAwcHggMHB4IDBweCAwcHggIzAwNzE0NDtcbiAgfVxuXG4gIGEsXG4gIGE6dmlzaXRlZCB7XG4gICAgdGV4dC1kZWNvcmF0aW9uOiBub25lO1xuICAgIGNvbG9yOiAjMDBhZTY4O1xuICB9XG5cbiAgYS5idXR0b24ge1xuICAgIC8qIGRpc3BsYXk6IGJsb2NrO1xuICAgIHBvc2l0aW9uOiByZWxhdGl2ZTsgXG4gICAgZmxvYXQ6IGxlZnQ7Ki9cbiAgICB3aWR0aDogMTIwcHg7XG4gICAgcGFkZGluZzogMTBweCA1MHB4IDEwcHggNTBweDtcbiAgICBmb250LXdlaWdodDogNjAwO1xuICAgIHRleHQtYWxpZ246IGNlbnRlcjtcbiAgICBsaW5lLWhlaWdodDogNTBweDtcbiAgICBjb2xvcjogI2ZmZjtcbiAgICBib3JkZXItcmFkaXVzOiA1cHg7XG4gICAgdHJhbnNpdGlvbjogYWxsIDAuMnM7XG4gIH1cblxuICAuYnRuQmx1ZUdyZWVuLmJ0blB1c2gge1xuICAgIGJveC1zaGFkb3c6IDBweCA1cHggMHB4IDBweCAjMDA3MTQ0O1xuICB9XG5cbiAgLmJ0bkJsdWVHcmVlbiB7XG4gICAgYmFja2dyb3VuZDogIzAwYWU2ODtcbiAgfVxuXG4gIC5idG5CbHVlR3JlZW4uYnRuUHVzaDpob3ZlciB7XG4gICAgYm94LXNoYWRvdzogMHB4IDBweCAwcHggMHB4ICMwMDcxNDQ7XG4gIH1cblxuICAuYnRuUHVzaDpob3ZlciB7XG4gICAgbWFyZ2luLXRvcDogMTVweDtcbiAgICBtYXJnaW4tYm90dG9tOiA1cHg7XG4gIH1cblxuICBoMSB7XG4gICAgZm9udC1zaXplOiAyLjhlbTtcbiAgICBmb250LXdlaWdodDogNzAwO1xuICAgIG1hcmdpbjogMCAwIDAuNWVtIDA7XG4gIH1cblxuICBmaWd1cmUge1xuICAgIG1hcmdpbjogMCAwIDFlbSAwO1xuICB9XG5cbiAgLnF1b3RlLWltZyB7XG4gICAgd2lkdGg6IDEwMCU7XG4gICAgbWF4LXdpZHRoOiA4MHB4O1xuICAgIG1hcmdpbjogMCAwIDFlbSAwO1xuICB9XG5cbiAgLmxvYWQtaW1nIHtcbiAgICB3aWR0aDogMTAwJTtcbiAgICBtYXgtd2lkdGg6IDMwcHg7XG4gICAgbWFyZ2luOiAwIDAgMWVtIDA7XG4gIH1cblxuICBAbWVkaWEgKG1pbi13aWR0aDogNDgwcHgpIHtcbiAgICBoMSB7XG4gICAgICBmb250LXNpemU6IDRlbTtcbiAgICB9XG4gIH1cbjwvc3R5bGU+XG5cbjxzdmVsdGU6aGVhZD5cbiAgPHRpdGxlPlNhcHBlciBwcm9qZWN0IHRlbXBsYXRlPC90aXRsZT5cbjwvc3ZlbHRlOmhlYWQ+XG48ZGl2IGlkPVwid3JhcHBlclwiPlxuICA8ZGl2IGlkPVwiY29udGVudFwiPlxuICAgIDxkaXYgaWQ9XCJjZW50ZXJcIj5cbiAgICAgIDxkaXYgY2xhc3M9XCJjYXB0aW9uXCI+XG4gICAgICAgIDxoMT5mYWxzZSBxdW90ZXMgZ2VuZXJhdG9yPC9oMT5cbiAgICAgIDwvZGl2PlxuXG5cbiAgICAgIDxkaXY+XG4gICAgICAgIDxmaWd1cmU+XG4gICAgICAgICAgPGltZyBjbGFzcz1cInF1b3RlLWltZ1wiIGFsdD1cIlF1b3RlXCIgc3JjPVwicXVvdGUucG5nXCIgLz5cbiAgICAgICAgICB7I2lmIGxvYWRpbmd9XG4gICAgICAgICAgICA8ZmlnY2FwdGlvbj5cbiAgICAgICAgICAgICAgPHA+XG4gICAgICAgICAgICAgICAgPGltZyBjbGFzcz1cImxvYWQtaW1nXCIgYWx0PVwiTG9hZGluZ1wiIHNyYz1cImFqYXgtbG9hZGVyLmdpZlwiIC8+XG4gICAgICAgICAgICAgIDwvcD5cbiAgICAgICAgICAgIDwvZmlnY2FwdGlvbj5cbiAgICAgICAgICB7L2lmfVxuICAgICAgICAgIHsjaWYgZXJyb3J9XG4gICAgICAgICAgICA8ZmlnY2FwdGlvbj5cbiAgICAgICAgICAgICAgPHA+T1VDSCEgU29tZXRoaW5nIHdlbnQgd3JvbmcuIDooPC9wPlxuICAgICAgICAgICAgPC9maWdjYXB0aW9uPlxuICAgICAgICAgIHsvaWZ9XG4gICAgICAgICAgeyNpZiAhbG9hZGluZyAmJiBxdW90ZSAmJiBjZWxlYnJpdHl9XG4gICAgICAgICAgICA8ZmlnY2FwdGlvbj5cbiAgICAgICAgICAgICAgPHAgY2xhc3M9XCJxdW90ZVwiPntxdW90ZX08L3A+XG4gICAgICAgICAgICAgIDxwIGNsYXNzPVwiY2VsZWJyaXR5XCI+LSB7Y2VsZWJyaXR5fTwvcD5cbiAgICAgICAgICAgIDwvZmlnY2FwdGlvbj5cbiAgICAgICAgICB7L2lmfVxuICAgICAgICA8L2ZpZ3VyZT5cbiAgICAgICAgPHNwYW4+XG4gICAgICAgICAgPGFcbiAgICAgICAgICAgIG9uOmNsaWNrPXtoYW5kbGVDbGlja31cbiAgICAgICAgICAgIGhyZWY9XCJodHRwczovL3Jpa2UuZGV2XCJcbiAgICAgICAgICAgIHRpdGxlPVwiQnV0dG9uIHB1c2ggYmx1ZS9ncmVlblwiXG4gICAgICAgICAgICBjbGFzcz1cImJ1dHRvbiBidG5QdXNoIGJ0bkJsdWVHcmVlblwiPlxuICAgICAgICAgICAgR08hXG4gICAgICAgICAgPC9hPlxuICAgICAgICA8L3NwYW4+XG4gICAgICA8L2Rpdj5cbiAgICA8L2Rpdj5cbiAgPC9kaXY+XG4gIDxmb290ZXI+XG4gICAgTWFkZSB3aXRoIOKZpSBhbmRcbiAgICA8YSBocmVmPVwiaHR0cDovL3N2ZWx0ZS5kZXZcIiB0YXJnZXQ9XCJfYmxhbmtcIj5TdmVsdGUuanM8L2E+XG4gICAgYnlcbiAgICA8YSBocmVmPVwiaHR0cHM6Ly9yaWtlLmRldlwiIHRhcmdldD1cIl9ibGFua1wiPlJpa2U8L2E+XG4gICAgaW4gMjAxOS5cbiAgPC9mb290ZXI+XG48L2Rpdj5cbiJdLCJzb3VyY2VSb290IjoiIn0=