(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["index"],{

/***/ "./src/helpers.js":
/*!************************!*\
  !*** ./src/helpers.js ***!
  \************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "default", function() { return timeoutPromise; });
function timeoutPromise(ms, promise) {
    return new Promise((resolve, reject) => {
      const timeoutId = setTimeout(() => {
        reject(new Error("promise timeout"))
      }, ms);
      promise.then(
        (res) => {
          clearTimeout(timeoutId);
          resolve(res);
        },
        (err) => {
          clearTimeout(timeoutId);
          reject(err);
        }
      );
    })
  }

/***/ }),

/***/ "./src/routes/index.svelte":
/*!*********************************!*\
  !*** ./src/routes/index.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal.mjs");
/* harmony import */ var _helpers__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../helpers */ "./src/helpers.js");
/* src/routes/index.svelte generated by Svelte v3.2.0 */



const file = "src/routes/index.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = 'svelte-10zejvu-style';
	style.textContent = "h1.svelte-10zejvu,figure.svelte-10zejvu,div.svelte-10zejvu,p.svelte-10zejvu{text-align:center;margin:0 auto}.caption.svelte-10zejvu{margin:0 auto;padding-top:2.5em;width:70%}.quote.svelte-10zejvu{width:70%;font-size:1.8em;font-family:\"Libre Baskerville\", Georgia, serif;font-style:italic}.celebrity.svelte-10zejvu{width:70%;text-align:right !important}.btnPush.svelte-10zejvu:hover{margin-top:15px;margin-bottom:5px}.btnBlueGreen.btnPush.svelte-10zejvu:hover{box-shadow:0px 0px 0px 0px #007144}a.svelte-10zejvu,a.svelte-10zejvu:visited{text-decoration:none;color:#00ae68}a.button.svelte-10zejvu{width:120px;padding:10px 50px 10px 50px;font-weight:600;text-align:center;line-height:50px;color:#fff;border-radius:5px;transition:all 0.2s}.btnBlueGreen.btnPush.svelte-10zejvu{box-shadow:0px 5px 0px 0px #007144}.btnBlueGreen.svelte-10zejvu{background:#00ae68}.btnBlueGreen.btnPush.svelte-10zejvu:hover{box-shadow:0px 0px 0px 0px #007144}.btnPush.svelte-10zejvu:hover{margin-top:15px;margin-bottom:5px}h1.svelte-10zejvu{font-size:2.8em;font-weight:700;margin:0 0 0.5em 0}figure.svelte-10zejvu{margin:0 0 1em 0}.quote-img.svelte-10zejvu{width:100%;max-width:80px;margin:0 0 1em 0}.load-img.svelte-10zejvu{width:100%;max-width:30px;margin:0 0 1em 0}@media(min-width: 480px){h1.svelte-10zejvu{font-size:4em}}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguc3ZlbHRlIiwic291cmNlcyI6WyJpbmRleC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgaW1wb3J0IHRpbWVvdXRQcm9taXNlIGZyb20gXCIuLi9oZWxwZXJzXCI7XG5cbiAgbGV0IHF1b3RlID0gXCJcIjtcbiAgbGV0IGNlbGVicml0eSA9IFwiXCI7XG4gIGxldCBsb2FkaW5nID0gZmFsc2U7XG4gIGxldCBlcnJvciA9IFwiXCI7XG5cbiAgYXN5bmMgZnVuY3Rpb24gZ2V0UXVvdGUoKSB7XG4gICAgcXVvdGUgPSBcIlwiO1xuICAgIGNlbGVicml0eSA9IFwiXCI7XG4gICAgZXJyb3IgPSBcIlwiO1xuICAgIHZhciB1cmx5ID0gXCIvYXBpL3F1b3RlXCI7XG4gICAgdHJ5IHtcbiAgICAgIGxldCByZXNwb25zZSA9IGF3YWl0IHRpbWVvdXRQcm9taXNlKDUwMDAsIGZldGNoKHVybHkpKTtcbiAgICAgIGxldCBkYXRhID0gYXdhaXQgcmVzcG9uc2UuanNvbigpO1xuICAgICAgY29uc29sZS5sb2coZGF0YSk7XG4gICAgICBxdW90ZSA9IGRhdGE7XG4gICAgfSBjYXRjaCAoZXJyb3IpIHtcbiAgICAgIGVycm9yID0gZXJyb3I7XG4gICAgICBjb25zb2xlLmVycm9yKGVycm9yKTtcbiAgICB9XG4gIH1cbiAgYXN5bmMgZnVuY3Rpb24gZ2V0Q2VsZWJyaXR5KCkge1xuICAgIHZhciB1cmx5ID0gXCIvYXBpL2NlbGVicml0eVwiO1xuICAgIHRyeSB7XG4gICAgICBsZXQgcmVzcG9uc2UgPSBhd2FpdCB0aW1lb3V0UHJvbWlzZSg1MDAwLCBmZXRjaCh1cmx5KSk7XG4gICAgICBsZXQgZGF0YSA9IGF3YWl0IHJlc3BvbnNlLmpzb24oKTtcbiAgICAgIGNvbnNvbGUubG9nKGRhdGEpO1xuICAgICAgY2VsZWJyaXR5ID0gZGF0YTtcbiAgICB9IGNhdGNoIChlcnJvcikge1xuICAgICAgZXJyb3IgPSBlcnJvcjtcbiAgICAgIGNvbnNvbGUuZXJyb3IoZXJyb3IpO1xuICAgIH1cbiAgfVxuICBhc3luYyBmdW5jdGlvbiBoYW5kbGVDbGljayhldmVudCkge1xuICAgIGV2ZW50LnByZXZlbnREZWZhdWx0KCk7XG4gICAgbG9hZGluZyA9IHRydWU7XG4gICAgYXdhaXQgZ2V0UXVvdGUoKTtcbiAgICBhd2FpdCBnZXRDZWxlYnJpdHkoKTtcbiAgICBsb2FkaW5nID0gZmFsc2U7XG4gIH1cblxuICBmdW5jdGlvbiBwcmVsb2FkKHsgcGFyYW1zLCBxdWVyeSB9KSB7XG4gICAgLy8gbm90aGluZyB0b2RvXG4gIH1cbjwvc2NyaXB0PlxuXG48c3R5bGU+XG4gIGgxLFxuICBmaWd1cmUsXG4gIGRpdixcbiAgcCB7XG4gICAgdGV4dC1hbGlnbjogY2VudGVyO1xuICAgIG1hcmdpbjogMCBhdXRvO1xuICB9XG5cbiAgLmNhcHRpb24ge1xuICAgIG1hcmdpbjogMCBhdXRvO1xuICAgIHBhZGRpbmctdG9wOiAyLjVlbTtcbiAgICB3aWR0aDogNzAlO1xuICB9XG5cbiAgLnF1b3RlIHtcbiAgICB3aWR0aDogNzAlO1xuICAgIGZvbnQtc2l6ZTogMS44ZW07XG4gICAgZm9udC1mYW1pbHk6IFwiTGlicmUgQmFza2VydmlsbGVcIiwgR2VvcmdpYSwgc2VyaWY7XG4gICAgZm9udC1zdHlsZTogaXRhbGljO1xuICB9XG5cbiAgLmNlbGVicml0eSB7XG4gICAgd2lkdGg6IDcwJTtcbiAgICB0ZXh0LWFsaWduOiByaWdodCAhaW1wb3J0YW50O1xuICB9XG5cbiAgLmJ0blB1c2g6aG92ZXIge1xuICAgIG1hcmdpbi10b3A6IDE1cHg7XG4gICAgbWFyZ2luLWJvdHRvbTogNXB4O1xuICB9XG5cbiAgLmJ0bkJsdWVHcmVlbi5idG5QdXNoOmhvdmVyIHtcbiAgICBib3gtc2hhZG93OiAwcHggMHB4IDBweCAwcHggIzAwNzE0NDtcbiAgfVxuXG4gIGEsXG4gIGE6dmlzaXRlZCB7XG4gICAgdGV4dC1kZWNvcmF0aW9uOiBub25lO1xuICAgIGNvbG9yOiAjMDBhZTY4O1xuICB9XG5cbiAgYS5idXR0b24ge1xuICAgIC8qIGRpc3BsYXk6IGJsb2NrO1xuICAgIHBvc2l0aW9uOiByZWxhdGl2ZTsgXG4gICAgZmxvYXQ6IGxlZnQ7Ki9cbiAgICB3aWR0aDogMTIwcHg7XG4gICAgcGFkZGluZzogMTBweCA1MHB4IDEwcHggNTBweDtcbiAgICBmb250LXdlaWdodDogNjAwO1xuICAgIHRleHQtYWxpZ246IGNlbnRlcjtcbiAgICBsaW5lLWhlaWdodDogNTBweDtcbiAgICBjb2xvcjogI2ZmZjtcbiAgICBib3JkZXItcmFkaXVzOiA1cHg7XG4gICAgdHJhbnNpdGlvbjogYWxsIDAuMnM7XG4gIH1cblxuICAuYnRuQmx1ZUdyZWVuLmJ0blB1c2gge1xuICAgIGJveC1zaGFkb3c6IDBweCA1cHggMHB4IDBweCAjMDA3MTQ0O1xuICB9XG5cbiAgLmJ0bkJsdWVHcmVlbiB7XG4gICAgYmFja2dyb3VuZDogIzAwYWU2ODtcbiAgfVxuXG4gIC5idG5CbHVlR3JlZW4uYnRuUHVzaDpob3ZlciB7XG4gICAgYm94LXNoYWRvdzogMHB4IDBweCAwcHggMHB4ICMwMDcxNDQ7XG4gIH1cblxuICAuYnRuUHVzaDpob3ZlciB7XG4gICAgbWFyZ2luLXRvcDogMTVweDtcbiAgICBtYXJnaW4tYm90dG9tOiA1cHg7XG4gIH1cblxuICBoMSB7XG4gICAgZm9udC1zaXplOiAyLjhlbTtcbiAgICBmb250LXdlaWdodDogNzAwO1xuICAgIG1hcmdpbjogMCAwIDAuNWVtIDA7XG4gIH1cblxuICBmaWd1cmUge1xuICAgIG1hcmdpbjogMCAwIDFlbSAwO1xuICB9XG5cbiAgLnF1b3RlLWltZyB7XG4gICAgd2lkdGg6IDEwMCU7XG4gICAgbWF4LXdpZHRoOiA4MHB4O1xuICAgIG1hcmdpbjogMCAwIDFlbSAwO1xuICB9XG5cbiAgLmxvYWQtaW1nIHtcbiAgICB3aWR0aDogMTAwJTtcbiAgICBtYXgtd2lkdGg6IDMwcHg7XG4gICAgbWFyZ2luOiAwIDAgMWVtIDA7XG4gIH1cblxuICBAbWVkaWEgKG1pbi13aWR0aDogNDgwcHgpIHtcbiAgICBoMSB7XG4gICAgICBmb250LXNpemU6IDRlbTtcbiAgICB9XG4gIH1cbjwvc3R5bGU+XG5cbjxzdmVsdGU6aGVhZD5cbiAgPHRpdGxlPlNhcHBlciBwcm9qZWN0IHRlbXBsYXRlPC90aXRsZT5cbjwvc3ZlbHRlOmhlYWQ+XG48ZGl2IGlkPVwid3JhcHBlclwiPlxuICA8ZGl2IGlkPVwiY29udGVudFwiPlxuICAgIDxkaXYgaWQ9XCJjZW50ZXJcIj5cbiAgICAgIDxkaXYgY2xhc3M9XCJjYXB0aW9uXCI+XG4gICAgICAgIDxoMT5mYWxzZSBxdW90ZXMgZ2VuZXJhdG9yPC9oMT5cbiAgICAgIDwvZGl2PlxuXG5cbiAgICAgIDxkaXY+XG4gICAgICAgIDxmaWd1cmU+XG4gICAgICAgICAgPGltZyBjbGFzcz1cInF1b3RlLWltZ1wiIGFsdD1cIlF1b3RlXCIgc3JjPVwicXVvdGUucG5nXCIgLz5cbiAgICAgICAgICB7I2lmIGxvYWRpbmd9XG4gICAgICAgICAgICA8ZmlnY2FwdGlvbj5cbiAgICAgICAgICAgICAgPHA+XG4gICAgICAgICAgICAgICAgPGltZyBjbGFzcz1cImxvYWQtaW1nXCIgYWx0PVwiTG9hZGluZ1wiIHNyYz1cImFqYXgtbG9hZGVyLmdpZlwiIC8+XG4gICAgICAgICAgICAgIDwvcD5cbiAgICAgICAgICAgIDwvZmlnY2FwdGlvbj5cbiAgICAgICAgICB7L2lmfVxuICAgICAgICAgIHsjaWYgZXJyb3J9XG4gICAgICAgICAgICA8ZmlnY2FwdGlvbj5cbiAgICAgICAgICAgICAgPHA+T1VDSCEgU29tZXRoaW5nIHdlbnQgd3JvbmcuIDooPC9wPlxuICAgICAgICAgICAgPC9maWdjYXB0aW9uPlxuICAgICAgICAgIHsvaWZ9XG4gICAgICAgICAgeyNpZiAhbG9hZGluZyAmJiBxdW90ZSAmJiBjZWxlYnJpdHl9XG4gICAgICAgICAgICA8ZmlnY2FwdGlvbj5cbiAgICAgICAgICAgICAgPHAgY2xhc3M9XCJxdW90ZVwiPntxdW90ZX08L3A+XG4gICAgICAgICAgICAgIDxwIGNsYXNzPVwiY2VsZWJyaXR5XCI+LSB7Y2VsZWJyaXR5fTwvcD5cbiAgICAgICAgICAgIDwvZmlnY2FwdGlvbj5cbiAgICAgICAgICB7L2lmfVxuICAgICAgICA8L2ZpZ3VyZT5cbiAgICAgICAgPHNwYW4+XG4gICAgICAgICAgPGFcbiAgICAgICAgICAgIG9uOmNsaWNrPXtoYW5kbGVDbGlja31cbiAgICAgICAgICAgIGhyZWY9XCJodHRwczovL3Jpa2UuZGV2XCJcbiAgICAgICAgICAgIHRpdGxlPVwiQnV0dG9uIHB1c2ggYmx1ZS9ncmVlblwiXG4gICAgICAgICAgICBjbGFzcz1cImJ1dHRvbiBidG5QdXNoIGJ0bkJsdWVHcmVlblwiPlxuICAgICAgICAgICAgR08hXG4gICAgICAgICAgPC9hPlxuICAgICAgICA8L3NwYW4+XG4gICAgICA8L2Rpdj5cbiAgICA8L2Rpdj5cbiAgPC9kaXY+XG4gIDxmb290ZXI+XG4gICAgTWFkZSB3aXRoIOKZpSBhbmRcbiAgICA8YSBocmVmPVwiaHR0cDovL3N2ZWx0ZS5kZXZcIiB0YXJnZXQ9XCJfYmxhbmtcIj5TdmVsdGUuanM8L2E+XG4gICAgYnlcbiAgICA8YSBocmVmPVwiaHR0cHM6Ly9yaWtlLmRldlwiIHRhcmdldD1cIl9ibGFua1wiPlJpa2U8L2E+XG4gICAgaW4gMjAxOS5cbiAgPC9mb290ZXI+XG48L2Rpdj5cbiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFpREUsaUJBQUUsQ0FDRixxQkFBTSxDQUNOLGtCQUFHLENBQ0gsQ0FBQyxlQUFDLENBQUMsQUFDRCxVQUFVLENBQUUsTUFBTSxDQUNsQixNQUFNLENBQUUsQ0FBQyxDQUFDLElBQUksQUFDaEIsQ0FBQyxBQUVELFFBQVEsZUFBQyxDQUFDLEFBQ1IsTUFBTSxDQUFFLENBQUMsQ0FBQyxJQUFJLENBQ2QsV0FBVyxDQUFFLEtBQUssQ0FDbEIsS0FBSyxDQUFFLEdBQUcsQUFDWixDQUFDLEFBRUQsTUFBTSxlQUFDLENBQUMsQUFDTixLQUFLLENBQUUsR0FBRyxDQUNWLFNBQVMsQ0FBRSxLQUFLLENBQ2hCLFdBQVcsQ0FBRSxtQkFBbUIsQ0FBQyxDQUFDLE9BQU8sQ0FBQyxDQUFDLEtBQUssQ0FDaEQsVUFBVSxDQUFFLE1BQU0sQUFDcEIsQ0FBQyxBQUVELFVBQVUsZUFBQyxDQUFDLEFBQ1YsS0FBSyxDQUFFLEdBQUcsQ0FDVixVQUFVLENBQUUsS0FBSyxDQUFDLFVBQVUsQUFDOUIsQ0FBQyxBQUVELHVCQUFRLE1BQU0sQUFBQyxDQUFDLEFBQ2QsVUFBVSxDQUFFLElBQUksQ0FDaEIsYUFBYSxDQUFFLEdBQUcsQUFDcEIsQ0FBQyxBQUVELGFBQWEsdUJBQVEsTUFBTSxBQUFDLENBQUMsQUFDM0IsVUFBVSxDQUFFLEdBQUcsQ0FBQyxHQUFHLENBQUMsR0FBRyxDQUFDLEdBQUcsQ0FBQyxPQUFPLEFBQ3JDLENBQUMsQUFFRCxnQkFBQyxDQUNELGdCQUFDLFFBQVEsQUFBQyxDQUFDLEFBQ1QsZUFBZSxDQUFFLElBQUksQ0FDckIsS0FBSyxDQUFFLE9BQU8sQUFDaEIsQ0FBQyxBQUVELENBQUMsT0FBTyxlQUFDLENBQUMsQUFJUixLQUFLLENBQUUsS0FBSyxDQUNaLE9BQU8sQ0FBRSxJQUFJLENBQUMsSUFBSSxDQUFDLElBQUksQ0FBQyxJQUFJLENBQzVCLFdBQVcsQ0FBRSxHQUFHLENBQ2hCLFVBQVUsQ0FBRSxNQUFNLENBQ2xCLFdBQVcsQ0FBRSxJQUFJLENBQ2pCLEtBQUssQ0FBRSxJQUFJLENBQ1gsYUFBYSxDQUFFLEdBQUcsQ0FDbEIsVUFBVSxDQUFFLEdBQUcsQ0FBQyxJQUFJLEFBQ3RCLENBQUMsQUFFRCxhQUFhLFFBQVEsZUFBQyxDQUFDLEFBQ3JCLFVBQVUsQ0FBRSxHQUFHLENBQUMsR0FBRyxDQUFDLEdBQUcsQ0FBQyxHQUFHLENBQUMsT0FBTyxBQUNyQyxDQUFDLEFBRUQsYUFBYSxlQUFDLENBQUMsQUFDYixVQUFVLENBQUUsT0FBTyxBQUNyQixDQUFDLEFBRUQsYUFBYSx1QkFBUSxNQUFNLEFBQUMsQ0FBQyxBQUMzQixVQUFVLENBQUUsR0FBRyxDQUFDLEdBQUcsQ0FBQyxHQUFHLENBQUMsR0FBRyxDQUFDLE9BQU8sQUFDckMsQ0FBQyxBQUVELHVCQUFRLE1BQU0sQUFBQyxDQUFDLEFBQ2QsVUFBVSxDQUFFLElBQUksQ0FDaEIsYUFBYSxDQUFFLEdBQUcsQUFDcEIsQ0FBQyxBQUVELEVBQUUsZUFBQyxDQUFDLEFBQ0YsU0FBUyxDQUFFLEtBQUssQ0FDaEIsV0FBVyxDQUFFLEdBQUcsQ0FDaEIsTUFBTSxDQUFFLENBQUMsQ0FBQyxDQUFDLENBQUMsS0FBSyxDQUFDLENBQUMsQUFDckIsQ0FBQyxBQUVELE1BQU0sZUFBQyxDQUFDLEFBQ04sTUFBTSxDQUFFLENBQUMsQ0FBQyxDQUFDLENBQUMsR0FBRyxDQUFDLENBQUMsQUFDbkIsQ0FBQyxBQUVELFVBQVUsZUFBQyxDQUFDLEFBQ1YsS0FBSyxDQUFFLElBQUksQ0FDWCxTQUFTLENBQUUsSUFBSSxDQUNmLE1BQU0sQ0FBRSxDQUFDLENBQUMsQ0FBQyxDQUFDLEdBQUcsQ0FBQyxDQUFDLEFBQ25CLENBQUMsQUFFRCxTQUFTLGVBQUMsQ0FBQyxBQUNULEtBQUssQ0FBRSxJQUFJLENBQ1gsU0FBUyxDQUFFLElBQUksQ0FDZixNQUFNLENBQUUsQ0FBQyxDQUFDLENBQUMsQ0FBQyxHQUFHLENBQUMsQ0FBQyxBQUNuQixDQUFDLEFBRUQsTUFBTSxBQUFDLFlBQVksS0FBSyxDQUFDLEFBQUMsQ0FBQyxBQUN6QixFQUFFLGVBQUMsQ0FBQyxBQUNGLFNBQVMsQ0FBRSxHQUFHLEFBQ2hCLENBQUMsQUFDSCxDQUFDIn0= */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(document.head, style);
}

// (165:10) {#if loading}
function create_if_block_2(ctx) {
	var figcaption, p, img;

	return {
		c: function create() {
			figcaption = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("figcaption");
			p = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			img = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			this.h()
		},

		l: function claim(nodes) {
			figcaption = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "FIGCAPTION", {}, false);
			var figcaption_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(figcaption);

			p = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(figcaption_nodes, "P", { class: true }, false);
			var p_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p);

			img = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p_nodes, "IMG", { class: true, alt: true, src: true }, false);
			var img_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(img);

			img_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			p_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			figcaption_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			img.className = "load-img svelte-10zejvu";
			img.alt = "Loading";
			img.src = "ajax-loader.gif";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img, file, 167, 16, 2907);
			p.className = "svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p, file, 166, 14, 2887);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(figcaption, file, 165, 12, 2860);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, figcaption, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figcaption, p);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p, img);
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(figcaption);
			}
		}
	};
}

// (172:10) {#if error}
function create_if_block_1(ctx) {
	var figcaption, p, t;

	return {
		c: function create() {
			figcaption = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("figcaption");
			p = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("OUCH! Something went wrong. :(");
			this.h()
		},

		l: function claim(nodes) {
			figcaption = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "FIGCAPTION", {}, false);
			var figcaption_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(figcaption);

			p = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(figcaption_nodes, "P", { class: true }, false);
			var p_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p);

			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p_nodes, "OUCH! Something went wrong. :(");
			p_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			figcaption_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			p.className = "svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p, file, 173, 14, 3090);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(figcaption, file, 172, 12, 3063);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, figcaption, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figcaption, p);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p, t);
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(figcaption);
			}
		}
	};
}

// (177:10) {#if !loading && quote && celebrity}
function create_if_block(ctx) {
	var figcaption, p0, t0, t1, p1, t2, t3;

	return {
		c: function create() {
			figcaption = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("figcaption");
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(ctx.quote);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("- ");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(ctx.celebrity);
			this.h()
		},

		l: function claim(nodes) {
			figcaption = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "FIGCAPTION", {}, false);
			var figcaption_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(figcaption);

			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(figcaption_nodes, "P", { class: true }, false);
			var p0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p0);

			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, ctx.quote);
			p0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(figcaption_nodes, "\n              ");

			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(figcaption_nodes, "P", { class: true }, false);
			var p1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p1);

			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "- ");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, ctx.celebrity);
			p1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			figcaption_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			p0.className = "quote svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p0, file, 178, 14, 3256);
			p1.className = "celebrity svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p1, file, 179, 14, 3299);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(figcaption, file, 177, 12, 3229);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, figcaption, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figcaption, p0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p0, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figcaption, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figcaption, p1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, t3);
		},

		p: function update(changed, ctx) {
			if (changed.quote) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t0, ctx.quote);
			}

			if (changed.celebrity) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t3, ctx.celebrity);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(figcaption);
			}
		}
	};
}

function create_fragment(ctx) {
	var t0, div4, div3, div2, div0, h1, t1, t2, div1, figure, img, t3, t4, t5, t6, span, a0, t7, t8, footer, t9, a1, t10, t11, a2, t12, t13, dispose;

	var if_block0 = (ctx.loading) && create_if_block_2(ctx);

	var if_block1 = (ctx.error) && create_if_block_1(ctx);

	var if_block2 = (!ctx.loading && ctx.quote && ctx.celebrity) && create_if_block(ctx);

	return {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h1");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("false quotes generator");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			figure = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("figure");
			img = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if (if_block0) if_block0.c();
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if (if_block1) if_block1.c();
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if (if_block2) if_block2.c();
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			a0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("GO!");
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			footer = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("footer");
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Made with ♥ and\n    ");
			a1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Svelte.js");
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\n    by\n    ");
			a2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Rike");
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\n    in 2019.");
			this.h()
		},

		l: function claim(nodes) {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n");

			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { id: true, class: true }, false);
			var div4_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div4);

			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "DIV", { id: true, class: true }, false);
			var div3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div3);

			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div3_nodes, "DIV", { id: true, class: true }, false);
			var div2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div2);

			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "DIV", { class: true }, false);
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);

			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div0_nodes, "H1", { class: true }, false);
			var h1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h1);

			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h1_nodes, "false quotes generator");
			h1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div2_nodes, "\n\n\n      ");

			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "DIV", { class: true }, false);
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);

			figure = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "FIGURE", { class: true }, false);
			var figure_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(figure);

			img = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(figure_nodes, "IMG", { class: true, alt: true, src: true }, false);
			var img_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(img);

			img_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(figure_nodes, "\n          ");
			if (if_block0) if_block0.l(figure_nodes);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(figure_nodes, "\n          ");
			if (if_block1) if_block1.l(figure_nodes);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(figure_nodes, "\n          ");
			if (if_block2) if_block2.l(figure_nodes);
			figure_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div1_nodes, "\n        ");

			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "SPAN", {}, false);
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);

			a0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span_nodes, "A", { href: true, title: true, class: true }, false);
			var a0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a0);

			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a0_nodes, "GO!");
			a0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div4_nodes, "\n  ");

			footer = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "FOOTER", {}, false);
			var footer_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(footer);

			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(footer_nodes, "Made with ♥ and\n    ");

			a1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(footer_nodes, "A", { href: true, target: true, class: true }, false);
			var a1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a1);

			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a1_nodes, "Svelte.js");
			a1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(footer_nodes, "\n    by\n    ");

			a2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(footer_nodes, "A", { href: true, target: true, class: true }, false);
			var a2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a2);

			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a2_nodes, "Rike");
			a2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(footer_nodes, "\n    in 2019.");
			footer_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div4_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			document.title = "Sapper project template";
			h1.className = "svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h1, file, 157, 8, 2684);
			div0.className = "caption svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 156, 6, 2654);
			img.className = "quote-img svelte-10zejvu";
			img.alt = "Quote";
			img.src = "quote.png";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img, file, 163, 10, 2770);
			figure.className = "svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(figure, file, 162, 8, 2751);
			a0.href = "https://rike.dev";
			a0.title = "Button push blue/green";
			a0.className = "button btnPush btnBlueGreen svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a0, file, 184, 10, 3423);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 183, 8, 3406);
			div1.className = "svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 161, 6, 2737);
			div2.id = "center";
			div2.className = "svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div2, file, 155, 4, 2630);
			div3.id = "content";
			div3.className = "svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div3, file, 154, 2, 2607);
			a1.href = "http://svelte.dev";
			a1.target = "_blank";
			a1.className = "svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a1, file, 197, 4, 3704);
			a2.href = "https://rike.dev";
			a2.target = "_blank";
			a2.className = "svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a2, file, 199, 4, 3773);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(footer, file, 195, 2, 3671);
			div4.id = "wrapper";
			div4.className = "svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div4, file, 153, 0, 2586);
			dispose = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen"])(a0, "click", ctx.handleClick);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, div4, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, div3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div3, div2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, div0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div0, h1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(h1, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, div1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, figure);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figure, img);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figure, t3);
			if (if_block0) if_block0.m(figure, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figure, t4);
			if (if_block1) if_block1.m(figure, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figure, t5);
			if (if_block2) if_block2.m(figure, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, span);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span, a0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(a0, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, t8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, footer);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(footer, t9);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(footer, a1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(a1, t10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(footer, t11);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(footer, a2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(a2, t12);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(footer, t13);
		},

		p: function update(changed, ctx) {
			if (ctx.loading) {
				if (!if_block0) {
					if_block0 = create_if_block_2(ctx);
					if_block0.c();
					if_block0.m(figure, t4);
				}
			} else if (if_block0) {
				if_block0.d(1);
				if_block0 = null;
			}

			if (ctx.error) {
				if (!if_block1) {
					if_block1 = create_if_block_1(ctx);
					if_block1.c();
					if_block1.m(figure, t5);
				}
			} else if (if_block1) {
				if_block1.d(1);
				if_block1 = null;
			}

			if (!ctx.loading && ctx.quote && ctx.celebrity) {
				if (if_block2) {
					if_block2.p(changed, ctx);
				} else {
					if_block2 = create_if_block(ctx);
					if_block2.c();
					if_block2.m(figure, null);
				}
			} else if (if_block2) {
				if_block2.d(1);
				if_block2 = null;
			}
		},

		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t0);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(div4);
			}

			if (if_block0) if_block0.d();
			if (if_block1) if_block1.d();
			if (if_block2) if_block2.d();
			dispose();
		}
	};
}

function preload({ params, query }) {
  // nothing todo
}

function instance($$self, $$props, $$invalidate) {
	let quote = "";
  let celebrity = "";
  let loading = false;
  let error = "";

  async function getQuote() {
    $$invalidate('quote', quote = "");
    $$invalidate('celebrity', celebrity = "");
    $$invalidate('error', error = "");
    var urly = "/api/quote";
    try {
      let response = await Object(_helpers__WEBPACK_IMPORTED_MODULE_1__["default"])(5000, fetch(urly));
      let data = await response.json();
      console.log(data);
      $$invalidate('quote', quote = data);
    } catch (error) {
      $$invalidate('error', error);
      console.error(error);
    }
  }
  async function getCelebrity() {
    var urly = "/api/celebrity";
    try {
      let response = await Object(_helpers__WEBPACK_IMPORTED_MODULE_1__["default"])(5000, fetch(urly));
      let data = await response.json();
      console.log(data);
      $$invalidate('celebrity', celebrity = data);
    } catch (error) {
      $$invalidate('error', error);
      console.error(error);
    }
  }
  async function handleClick(event) {
    event.preventDefault();
    $$invalidate('loading', loading = true);
    await getQuote();
    await getCelebrity();
    $$invalidate('loading', loading = false);
  }

	return {
		quote,
		celebrity,
		loading,
		error,
		handleClick
	};
}

class Routes extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-10zejvu-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], []);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Routes);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvaGVscGVycy5qcyIsIndlYnBhY2s6Ly8vLi9zcmMvcm91dGVzL2luZGV4LnN2ZWx0ZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7O0FBQUE7QUFBQTtBQUFlO0FBQ2Y7QUFDQTtBQUNBO0FBQ0EsT0FBTztBQUNQO0FBQ0E7QUFDQTtBQUNBO0FBQ0EsU0FBUztBQUNUO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQSxLQUFLO0FBQ0wsRzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt5RUNrS2dDLEtBQUs7Ozs7eUVBQ0MsU0FBUzs7Ozs7Ozs7Ozs7eUZBRGYsS0FBSzs7Ozs7Ozs7eUZBQ0MsU0FBUzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7NkVBRGYsS0FBSzs7Ozs2RUFDQyxTQUFTOzs7Ozs7Ozs7Ozs7Ozs7c0JBZmhDLE9BQU87O3NCQU9QLEtBQUs7O2tCQUtMLEtBQUMsT0FBTyxRQUFJLEtBQUssUUFBSSxTQUFTOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7NkZBU3ZCLFdBQVc7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7V0FyQmxCLE9BQU87Ozs7Ozs7Ozs7O1dBT1AsS0FBSzs7Ozs7Ozs7Ozs7T0FLTCxLQUFDLE9BQU8sUUFBSSxLQUFLLFFBQUksU0FBUzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQXJJM0MsU0FBUyxPQUFPLENBQUMsRUFBRSxNQUFNLEVBQUUsS0FBSyxFQUFFLEVBQUU7QUFDcEM7QUFDQSxDQUFDOzs7Q0ExQ0QsSUFBSSxLQUFLLEdBQUcsRUFBRSxDQUFDO0VBQ2YsSUFBSSxTQUFTLEdBQUcsRUFBRSxDQUFDO0VBQ25CLElBQUksT0FBTyxHQUFHLEtBQUssQ0FBQztFQUNwQixJQUFJLEtBQUssR0FBRyxFQUFFLENBQUM7O0VBRWYsZUFBZSxRQUFRLEdBQUc7MEJBQ3hCLEtBQUssR0FBRyxHQUFFLENBQUM7OEJBQ1gsU0FBUyxHQUFHLEdBQUUsQ0FBQzswQkFDZixLQUFLLEdBQUcsR0FBRSxDQUFDO0lBQ1gsSUFBSSxJQUFJLEdBQUcsWUFBWSxDQUFDO0lBQ3hCLElBQUk7TUFDRixJQUFJLFFBQVEsR0FBRyxNQUFNLHdEQUFjLENBQUMsSUFBSSxFQUFFLEtBQUssQ0FBQyxJQUFJLENBQUMsQ0FBQyxDQUFDO01BQ3ZELElBQUksSUFBSSxHQUFHLE1BQU0sUUFBUSxDQUFDLElBQUksRUFBRSxDQUFDO01BQ2pDLE9BQU8sQ0FBQyxHQUFHLENBQUMsSUFBSSxDQUFDLENBQUM7NEJBQ2xCLEtBQUssR0FBRyxLQUFJLENBQUM7S0FDZCxDQUFDLE9BQU8sS0FBSyxFQUFFO01BQ2QsNEJBQWEsQ0FBQztNQUNkLE9BQU8sQ0FBQyxLQUFLLENBQUMsS0FBSyxDQUFDLENBQUM7S0FDdEI7R0FDRjtFQUNELGVBQWUsWUFBWSxHQUFHO0lBQzVCLElBQUksSUFBSSxHQUFHLGdCQUFnQixDQUFDO0lBQzVCLElBQUk7TUFDRixJQUFJLFFBQVEsR0FBRyxNQUFNLHdEQUFjLENBQUMsSUFBSSxFQUFFLEtBQUssQ0FBQyxJQUFJLENBQUMsQ0FBQyxDQUFDO01BQ3ZELElBQUksSUFBSSxHQUFHLE1BQU0sUUFBUSxDQUFDLElBQUksRUFBRSxDQUFDO01BQ2pDLE9BQU8sQ0FBQyxHQUFHLENBQUMsSUFBSSxDQUFDLENBQUM7Z0NBQ2xCLFNBQVMsR0FBRyxLQUFJLENBQUM7S0FDbEIsQ0FBQyxPQUFPLEtBQUssRUFBRTtNQUNkLDRCQUFhLENBQUM7TUFDZCxPQUFPLENBQUMsS0FBSyxDQUFDLEtBQUssQ0FBQyxDQUFDO0tBQ3RCO0dBQ0Y7RUFDRCxlQUFlLFdBQVcsQ0FBQyxLQUFLLEVBQUU7SUFDaEMsS0FBSyxDQUFDLGNBQWMsRUFBRSxDQUFDOzRCQUN2QixPQUFPLEdBQUcsS0FBSSxDQUFDO0lBQ2YsTUFBTSxRQUFRLEVBQUUsQ0FBQztJQUNqQixNQUFNLFlBQVksRUFBRSxDQUFDOzRCQUNyQixPQUFPLEdBQUcsTUFBSyxDQUFDO0dBQ2pCIiwiZmlsZSI6IjhjMzhlMGVmZmY1MGM4MmY0MGM2L2luZGV4LmluZGV4LmpzIiwic291cmNlc0NvbnRlbnQiOlsiZXhwb3J0IGRlZmF1bHQgZnVuY3Rpb24gdGltZW91dFByb21pc2UobXMsIHByb21pc2UpIHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgdGltZW91dElkID0gc2V0VGltZW91dCgoKSA9PiB7XG4gICAgICAgIHJlamVjdChuZXcgRXJyb3IoXCJwcm9taXNlIHRpbWVvdXRcIikpXG4gICAgICB9LCBtcyk7XG4gICAgICBwcm9taXNlLnRoZW4oXG4gICAgICAgIChyZXMpID0+IHtcbiAgICAgICAgICBjbGVhclRpbWVvdXQodGltZW91dElkKTtcbiAgICAgICAgICByZXNvbHZlKHJlcyk7XG4gICAgICAgIH0sXG4gICAgICAgIChlcnIpID0+IHtcbiAgICAgICAgICBjbGVhclRpbWVvdXQodGltZW91dElkKTtcbiAgICAgICAgICByZWplY3QoZXJyKTtcbiAgICAgICAgfVxuICAgICAgKTtcbiAgICB9KVxuICB9IiwiPHNjcmlwdD5cbiAgaW1wb3J0IHRpbWVvdXRQcm9taXNlIGZyb20gXCIuLi9oZWxwZXJzXCI7XG5cbiAgbGV0IHF1b3RlID0gXCJcIjtcbiAgbGV0IGNlbGVicml0eSA9IFwiXCI7XG4gIGxldCBsb2FkaW5nID0gZmFsc2U7XG4gIGxldCBlcnJvciA9IFwiXCI7XG5cbiAgYXN5bmMgZnVuY3Rpb24gZ2V0UXVvdGUoKSB7XG4gICAgcXVvdGUgPSBcIlwiO1xuICAgIGNlbGVicml0eSA9IFwiXCI7XG4gICAgZXJyb3IgPSBcIlwiO1xuICAgIHZhciB1cmx5ID0gXCIvYXBpL3F1b3RlXCI7XG4gICAgdHJ5IHtcbiAgICAgIGxldCByZXNwb25zZSA9IGF3YWl0IHRpbWVvdXRQcm9taXNlKDUwMDAsIGZldGNoKHVybHkpKTtcbiAgICAgIGxldCBkYXRhID0gYXdhaXQgcmVzcG9uc2UuanNvbigpO1xuICAgICAgY29uc29sZS5sb2coZGF0YSk7XG4gICAgICBxdW90ZSA9IGRhdGE7XG4gICAgfSBjYXRjaCAoZXJyb3IpIHtcbiAgICAgIGVycm9yID0gZXJyb3I7XG4gICAgICBjb25zb2xlLmVycm9yKGVycm9yKTtcbiAgICB9XG4gIH1cbiAgYXN5bmMgZnVuY3Rpb24gZ2V0Q2VsZWJyaXR5KCkge1xuICAgIHZhciB1cmx5ID0gXCIvYXBpL2NlbGVicml0eVwiO1xuICAgIHRyeSB7XG4gICAgICBsZXQgcmVzcG9uc2UgPSBhd2FpdCB0aW1lb3V0UHJvbWlzZSg1MDAwLCBmZXRjaCh1cmx5KSk7XG4gICAgICBsZXQgZGF0YSA9IGF3YWl0IHJlc3BvbnNlLmpzb24oKTtcbiAgICAgIGNvbnNvbGUubG9nKGRhdGEpO1xuICAgICAgY2VsZWJyaXR5ID0gZGF0YTtcbiAgICB9IGNhdGNoIChlcnJvcikge1xuICAgICAgZXJyb3IgPSBlcnJvcjtcbiAgICAgIGNvbnNvbGUuZXJyb3IoZXJyb3IpO1xuICAgIH1cbiAgfVxuICBhc3luYyBmdW5jdGlvbiBoYW5kbGVDbGljayhldmVudCkge1xuICAgIGV2ZW50LnByZXZlbnREZWZhdWx0KCk7XG4gICAgbG9hZGluZyA9IHRydWU7XG4gICAgYXdhaXQgZ2V0UXVvdGUoKTtcbiAgICBhd2FpdCBnZXRDZWxlYnJpdHkoKTtcbiAgICBsb2FkaW5nID0gZmFsc2U7XG4gIH1cblxuICBmdW5jdGlvbiBwcmVsb2FkKHsgcGFyYW1zLCBxdWVyeSB9KSB7XG4gICAgLy8gbm90aGluZyB0b2RvXG4gIH1cbjwvc2NyaXB0PlxuXG48c3R5bGU+XG4gIGgxLFxuICBmaWd1cmUsXG4gIGRpdixcbiAgcCB7XG4gICAgdGV4dC1hbGlnbjogY2VudGVyO1xuICAgIG1hcmdpbjogMCBhdXRvO1xuICB9XG5cbiAgLmNhcHRpb24ge1xuICAgIG1hcmdpbjogMCBhdXRvO1xuICAgIHBhZGRpbmctdG9wOiAyLjVlbTtcbiAgICB3aWR0aDogNzAlO1xuICB9XG5cbiAgLnF1b3RlIHtcbiAgICB3aWR0aDogNzAlO1xuICAgIGZvbnQtc2l6ZTogMS44ZW07XG4gICAgZm9udC1mYW1pbHk6IFwiTGlicmUgQmFza2VydmlsbGVcIiwgR2VvcmdpYSwgc2VyaWY7XG4gICAgZm9udC1zdHlsZTogaXRhbGljO1xuICB9XG5cbiAgLmNlbGVicml0eSB7XG4gICAgd2lkdGg6IDcwJTtcbiAgICB0ZXh0LWFsaWduOiByaWdodCAhaW1wb3J0YW50O1xuICB9XG5cbiAgLmJ0blB1c2g6aG92ZXIge1xuICAgIG1hcmdpbi10b3A6IDE1cHg7XG4gICAgbWFyZ2luLWJvdHRvbTogNXB4O1xuICB9XG5cbiAgLmJ0bkJsdWVHcmVlbi5idG5QdXNoOmhvdmVyIHtcbiAgICBib3gtc2hhZG93OiAwcHggMHB4IDBweCAwcHggIzAwNzE0NDtcbiAgfVxuXG4gIGEsXG4gIGE6dmlzaXRlZCB7XG4gICAgdGV4dC1kZWNvcmF0aW9uOiBub25lO1xuICAgIGNvbG9yOiAjMDBhZTY4O1xuICB9XG5cbiAgYS5idXR0b24ge1xuICAgIC8qIGRpc3BsYXk6IGJsb2NrO1xuICAgIHBvc2l0aW9uOiByZWxhdGl2ZTsgXG4gICAgZmxvYXQ6IGxlZnQ7Ki9cbiAgICB3aWR0aDogMTIwcHg7XG4gICAgcGFkZGluZzogMTBweCA1MHB4IDEwcHggNTBweDtcbiAgICBmb250LXdlaWdodDogNjAwO1xuICAgIHRleHQtYWxpZ246IGNlbnRlcjtcbiAgICBsaW5lLWhlaWdodDogNTBweDtcbiAgICBjb2xvcjogI2ZmZjtcbiAgICBib3JkZXItcmFkaXVzOiA1cHg7XG4gICAgdHJhbnNpdGlvbjogYWxsIDAuMnM7XG4gIH1cblxuICAuYnRuQmx1ZUdyZWVuLmJ0blB1c2gge1xuICAgIGJveC1zaGFkb3c6IDBweCA1cHggMHB4IDBweCAjMDA3MTQ0O1xuICB9XG5cbiAgLmJ0bkJsdWVHcmVlbiB7XG4gICAgYmFja2dyb3VuZDogIzAwYWU2ODtcbiAgfVxuXG4gIC5idG5CbHVlR3JlZW4uYnRuUHVzaDpob3ZlciB7XG4gICAgYm94LXNoYWRvdzogMHB4IDBweCAwcHggMHB4ICMwMDcxNDQ7XG4gIH1cblxuICAuYnRuUHVzaDpob3ZlciB7XG4gICAgbWFyZ2luLXRvcDogMTVweDtcbiAgICBtYXJnaW4tYm90dG9tOiA1cHg7XG4gIH1cblxuICBoMSB7XG4gICAgZm9udC1zaXplOiAyLjhlbTtcbiAgICBmb250LXdlaWdodDogNzAwO1xuICAgIG1hcmdpbjogMCAwIDAuNWVtIDA7XG4gIH1cblxuICBmaWd1cmUge1xuICAgIG1hcmdpbjogMCAwIDFlbSAwO1xuICB9XG5cbiAgLnF1b3RlLWltZyB7XG4gICAgd2lkdGg6IDEwMCU7XG4gICAgbWF4LXdpZHRoOiA4MHB4O1xuICAgIG1hcmdpbjogMCAwIDFlbSAwO1xuICB9XG5cbiAgLmxvYWQtaW1nIHtcbiAgICB3aWR0aDogMTAwJTtcbiAgICBtYXgtd2lkdGg6IDMwcHg7XG4gICAgbWFyZ2luOiAwIDAgMWVtIDA7XG4gIH1cblxuICBAbWVkaWEgKG1pbi13aWR0aDogNDgwcHgpIHtcbiAgICBoMSB7XG4gICAgICBmb250LXNpemU6IDRlbTtcbiAgICB9XG4gIH1cbjwvc3R5bGU+XG5cbjxzdmVsdGU6aGVhZD5cbiAgPHRpdGxlPlNhcHBlciBwcm9qZWN0IHRlbXBsYXRlPC90aXRsZT5cbjwvc3ZlbHRlOmhlYWQ+XG48ZGl2IGlkPVwid3JhcHBlclwiPlxuICA8ZGl2IGlkPVwiY29udGVudFwiPlxuICAgIDxkaXYgaWQ9XCJjZW50ZXJcIj5cbiAgICAgIDxkaXYgY2xhc3M9XCJjYXB0aW9uXCI+XG4gICAgICAgIDxoMT5mYWxzZSBxdW90ZXMgZ2VuZXJhdG9yPC9oMT5cbiAgICAgIDwvZGl2PlxuXG5cbiAgICAgIDxkaXY+XG4gICAgICAgIDxmaWd1cmU+XG4gICAgICAgICAgPGltZyBjbGFzcz1cInF1b3RlLWltZ1wiIGFsdD1cIlF1b3RlXCIgc3JjPVwicXVvdGUucG5nXCIgLz5cbiAgICAgICAgICB7I2lmIGxvYWRpbmd9XG4gICAgICAgICAgICA8ZmlnY2FwdGlvbj5cbiAgICAgICAgICAgICAgPHA+XG4gICAgICAgICAgICAgICAgPGltZyBjbGFzcz1cImxvYWQtaW1nXCIgYWx0PVwiTG9hZGluZ1wiIHNyYz1cImFqYXgtbG9hZGVyLmdpZlwiIC8+XG4gICAgICAgICAgICAgIDwvcD5cbiAgICAgICAgICAgIDwvZmlnY2FwdGlvbj5cbiAgICAgICAgICB7L2lmfVxuICAgICAgICAgIHsjaWYgZXJyb3J9XG4gICAgICAgICAgICA8ZmlnY2FwdGlvbj5cbiAgICAgICAgICAgICAgPHA+T1VDSCEgU29tZXRoaW5nIHdlbnQgd3JvbmcuIDooPC9wPlxuICAgICAgICAgICAgPC9maWdjYXB0aW9uPlxuICAgICAgICAgIHsvaWZ9XG4gICAgICAgICAgeyNpZiAhbG9hZGluZyAmJiBxdW90ZSAmJiBjZWxlYnJpdHl9XG4gICAgICAgICAgICA8ZmlnY2FwdGlvbj5cbiAgICAgICAgICAgICAgPHAgY2xhc3M9XCJxdW90ZVwiPntxdW90ZX08L3A+XG4gICAgICAgICAgICAgIDxwIGNsYXNzPVwiY2VsZWJyaXR5XCI+LSB7Y2VsZWJyaXR5fTwvcD5cbiAgICAgICAgICAgIDwvZmlnY2FwdGlvbj5cbiAgICAgICAgICB7L2lmfVxuICAgICAgICA8L2ZpZ3VyZT5cbiAgICAgICAgPHNwYW4+XG4gICAgICAgICAgPGFcbiAgICAgICAgICAgIG9uOmNsaWNrPXtoYW5kbGVDbGlja31cbiAgICAgICAgICAgIGhyZWY9XCJodHRwczovL3Jpa2UuZGV2XCJcbiAgICAgICAgICAgIHRpdGxlPVwiQnV0dG9uIHB1c2ggYmx1ZS9ncmVlblwiXG4gICAgICAgICAgICBjbGFzcz1cImJ1dHRvbiBidG5QdXNoIGJ0bkJsdWVHcmVlblwiPlxuICAgICAgICAgICAgR08hXG4gICAgICAgICAgPC9hPlxuICAgICAgICA8L3NwYW4+XG4gICAgICA8L2Rpdj5cbiAgICA8L2Rpdj5cbiAgPC9kaXY+XG4gIDxmb290ZXI+XG4gICAgTWFkZSB3aXRoIOKZpSBhbmRcbiAgICA8YSBocmVmPVwiaHR0cDovL3N2ZWx0ZS5kZXZcIiB0YXJnZXQ9XCJfYmxhbmtcIj5TdmVsdGUuanM8L2E+XG4gICAgYnlcbiAgICA8YSBocmVmPVwiaHR0cHM6Ly9yaWtlLmRldlwiIHRhcmdldD1cIl9ibGFua1wiPlJpa2U8L2E+XG4gICAgaW4gMjAxOS5cbiAgPC9mb290ZXI+XG48L2Rpdj5cbiJdLCJzb3VyY2VSb290IjoiIn0=