(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["index"],{

/***/ "./src/helpers.js":
/*!************************!*\
  !*** ./src/helpers.js ***!
  \************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "default", function() { return timeoutPromise; });
function timeoutPromise(ms, promise) {
    return new Promise((resolve, reject) => {
      const timeoutId = setTimeout(() => {
        reject(new Error("promise timeout"))
      }, ms);
      promise.then(
        (res) => {
          clearTimeout(timeoutId);
          resolve(res);
        },
        (err) => {
          clearTimeout(timeoutId);
          reject(err);
        }
      );
    })
  }

/***/ }),

/***/ "./src/routes/index.svelte":
/*!*********************************!*\
  !*** ./src/routes/index.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal.mjs");
/* harmony import */ var _helpers__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../helpers */ "./src/helpers.js");
/* src/routes/index.svelte generated by Svelte v3.2.0 */



const file = "src/routes/index.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = 'svelte-10zejvu-style';
	style.textContent = "h1.svelte-10zejvu,figure.svelte-10zejvu,div.svelte-10zejvu,p.svelte-10zejvu{text-align:center;margin:0 auto}.caption.svelte-10zejvu{margin:0 auto;padding-top:2.5em;width:70%}.quote.svelte-10zejvu{width:70%;font-size:1.8em;font-family:\"Libre Baskerville\", Georgia, serif;font-style:italic}.celebrity.svelte-10zejvu{width:70%;text-align:right !important}.btnPush.svelte-10zejvu:hover{margin-top:15px;margin-bottom:5px}.btnBlueGreen.btnPush.svelte-10zejvu:hover{box-shadow:0px 0px 0px 0px #007144}a.svelte-10zejvu,a.svelte-10zejvu:visited{text-decoration:none;color:#00ae68}a.button.svelte-10zejvu{width:120px;padding:10px 50px 10px 50px;font-weight:600;text-align:center;line-height:50px;color:#fff;border-radius:5px;transition:all 0.2s}.btnBlueGreen.btnPush.svelte-10zejvu{box-shadow:0px 5px 0px 0px #007144}.btnBlueGreen.svelte-10zejvu{background:#00ae68}.btnBlueGreen.btnPush.svelte-10zejvu:hover{box-shadow:0px 0px 0px 0px #007144}.btnPush.svelte-10zejvu:hover{margin-top:15px;margin-bottom:5px}h1.svelte-10zejvu{font-size:2.8em;font-weight:700;margin:0 0 0.5em 0}figure.svelte-10zejvu{margin:0 0 1em 0}.quote-img.svelte-10zejvu{width:100%;max-width:80px;margin:0 0 1em 0}.load-img.svelte-10zejvu{width:100%;max-width:30px;margin:0 0 1em 0}@media(min-width: 480px){h1.svelte-10zejvu{font-size:4em}}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguc3ZlbHRlIiwic291cmNlcyI6WyJpbmRleC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgaW1wb3J0IHRpbWVvdXRQcm9taXNlIGZyb20gXCIuLi9oZWxwZXJzXCI7XG5cbiAgbGV0IHF1b3RlID0gXCJcIjtcbiAgbGV0IGNlbGVicml0eSA9IFwiXCI7XG4gIGxldCBsb2FkaW5nID0gZmFsc2U7XG4gIGxldCBlcnJvciA9IFwiXCI7XG5cbiAgYXN5bmMgZnVuY3Rpb24gZ2V0UXVvdGUoKSB7XG4gICAgcXVvdGUgPSBcIlwiO1xuICAgIGNlbGVicml0eSA9IFwiXCI7XG4gICAgZXJyb3IgPSBcIlwiO1xuICAgIHZhciB1cmx5ID0gXCJodHRwOi8vbG9jYWxob3N0OjMzMzMvcXVvdGVcIjtcbiAgICB0cnkge1xuICAgICAgbGV0IHJlc3BvbnNlID0gYXdhaXQgdGltZW91dFByb21pc2UoMTAgKiA2MCAqIDEwMDAsIGZldGNoKHVybHkpKTtcbiAgICAgIGxldCBkYXRhID0gYXdhaXQgcmVzcG9uc2UuanNvbigpO1xuICAgICAgY29uc29sZS5sb2coZGF0YSk7XG4gICAgICBxdW90ZSA9IGRhdGE7XG4gICAgfSBjYXRjaCAoZXJyb3IpIHtcbiAgICAgIGVycm9yID0gZXJyb3I7XG4gICAgICBjb25zb2xlLmVycm9yKGVycm9yKTtcbiAgICB9XG4gIH1cbiAgYXN5bmMgZnVuY3Rpb24gZ2V0Q2VsZWJyaXR5KCkge1xuICAgIHZhciB1cmx5ID0gXCJodHRwOi8vbG9jYWxob3N0OjMzMzMvY2VsZWJyaXR5XCI7XG4gICAgdHJ5IHtcbiAgICAgIGxldCByZXNwb25zZSA9IGF3YWl0IHRpbWVvdXRQcm9taXNlKDEgKiA1ICogMTAwMCwgZmV0Y2godXJseSkpO1xuICAgICAgbGV0IGRhdGEgPSBhd2FpdCByZXNwb25zZS5qc29uKCk7XG4gICAgICBjb25zb2xlLmxvZyhkYXRhKTtcbiAgICAgIGNlbGVicml0eSA9IGRhdGE7XG4gICAgfSBjYXRjaCAoZXJyb3IpIHtcbiAgICAgIGVycm9yID0gZXJyb3I7XG4gICAgICBjb25zb2xlLmVycm9yKGVycm9yKTtcbiAgICB9XG4gIH1cbiAgYXN5bmMgZnVuY3Rpb24gaGFuZGxlQ2xpY2soZXZlbnQpIHtcbiAgICBldmVudC5wcmV2ZW50RGVmYXVsdCgpO1xuICAgIGxvYWRpbmcgPSB0cnVlO1xuICAgIGF3YWl0IGdldFF1b3RlKCk7XG4gICAgYXdhaXQgZ2V0Q2VsZWJyaXR5KCk7XG4gICAgbG9hZGluZyA9IGZhbHNlO1xuICB9XG5cbiAgZnVuY3Rpb24gcHJlbG9hZCh7IHBhcmFtcywgcXVlcnkgfSkge1xuICAgIC8vIG5vdGhpbmcgdG9kb1xuICB9XG48L3NjcmlwdD5cblxuPHN0eWxlPlxuICBoMSxcbiAgZmlndXJlLFxuICBkaXYsXG4gIHAge1xuICAgIHRleHQtYWxpZ246IGNlbnRlcjtcbiAgICBtYXJnaW46IDAgYXV0bztcbiAgfVxuXG4gIC5jYXB0aW9uIHtcbiAgICBtYXJnaW46IDAgYXV0bztcbiAgICBwYWRkaW5nLXRvcDogMi41ZW07XG4gICAgd2lkdGg6IDcwJTtcbiAgfVxuXG4gIC5xdW90ZSB7XG4gICAgd2lkdGg6IDcwJTtcbiAgICBmb250LXNpemU6IDEuOGVtO1xuICAgIGZvbnQtZmFtaWx5OiBcIkxpYnJlIEJhc2tlcnZpbGxlXCIsIEdlb3JnaWEsIHNlcmlmO1xuICAgIGZvbnQtc3R5bGU6IGl0YWxpYztcbiAgfVxuXG4gIC5jZWxlYnJpdHkge1xuICAgIHdpZHRoOiA3MCU7XG4gICAgdGV4dC1hbGlnbjogcmlnaHQgIWltcG9ydGFudDtcbiAgfVxuXG4gIC5idG5QdXNoOmhvdmVyIHtcbiAgICBtYXJnaW4tdG9wOiAxNXB4O1xuICAgIG1hcmdpbi1ib3R0b206IDVweDtcbiAgfVxuXG4gIC5idG5CbHVlR3JlZW4uYnRuUHVzaDpob3ZlciB7XG4gICAgYm94LXNoYWRvdzogMHB4IDBweCAwcHggMHB4ICMwMDcxNDQ7XG4gIH1cblxuICBhLFxuICBhOnZpc2l0ZWQge1xuICAgIHRleHQtZGVjb3JhdGlvbjogbm9uZTtcbiAgICBjb2xvcjogIzAwYWU2ODtcbiAgfVxuXG4gIGEuYnV0dG9uIHtcbiAgICAvKiBkaXNwbGF5OiBibG9jaztcbiAgICBwb3NpdGlvbjogcmVsYXRpdmU7IFxuICAgIGZsb2F0OiBsZWZ0OyovXG4gICAgd2lkdGg6IDEyMHB4O1xuICAgIHBhZGRpbmc6IDEwcHggNTBweCAxMHB4IDUwcHg7XG4gICAgZm9udC13ZWlnaHQ6IDYwMDtcbiAgICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gICAgbGluZS1oZWlnaHQ6IDUwcHg7XG4gICAgY29sb3I6ICNmZmY7XG4gICAgYm9yZGVyLXJhZGl1czogNXB4O1xuICAgIHRyYW5zaXRpb246IGFsbCAwLjJzO1xuICB9XG5cbiAgLmJ0bkJsdWVHcmVlbi5idG5QdXNoIHtcbiAgICBib3gtc2hhZG93OiAwcHggNXB4IDBweCAwcHggIzAwNzE0NDtcbiAgfVxuXG4gIC5idG5CbHVlR3JlZW4ge1xuICAgIGJhY2tncm91bmQ6ICMwMGFlNjg7XG4gIH1cblxuICAuYnRuQmx1ZUdyZWVuLmJ0blB1c2g6aG92ZXIge1xuICAgIGJveC1zaGFkb3c6IDBweCAwcHggMHB4IDBweCAjMDA3MTQ0O1xuICB9XG5cbiAgLmJ0blB1c2g6aG92ZXIge1xuICAgIG1hcmdpbi10b3A6IDE1cHg7XG4gICAgbWFyZ2luLWJvdHRvbTogNXB4O1xuICB9XG5cbiAgaDEge1xuICAgIGZvbnQtc2l6ZTogMi44ZW07XG4gICAgZm9udC13ZWlnaHQ6IDcwMDtcbiAgICBtYXJnaW46IDAgMCAwLjVlbSAwO1xuICB9XG5cbiAgZmlndXJlIHtcbiAgICBtYXJnaW46IDAgMCAxZW0gMDtcbiAgfVxuXG4gIC5xdW90ZS1pbWcge1xuICAgIHdpZHRoOiAxMDAlO1xuICAgIG1heC13aWR0aDogODBweDtcbiAgICBtYXJnaW46IDAgMCAxZW0gMDtcbiAgfVxuXG4gIC5sb2FkLWltZyB7XG4gICAgd2lkdGg6IDEwMCU7XG4gICAgbWF4LXdpZHRoOiAzMHB4O1xuICAgIG1hcmdpbjogMCAwIDFlbSAwO1xuICB9XG5cbiAgQG1lZGlhIChtaW4td2lkdGg6IDQ4MHB4KSB7XG4gICAgaDEge1xuICAgICAgZm9udC1zaXplOiA0ZW07XG4gICAgfVxuICB9XG48L3N0eWxlPlxuXG48c3ZlbHRlOmhlYWQ+XG4gIDx0aXRsZT5TYXBwZXIgcHJvamVjdCB0ZW1wbGF0ZTwvdGl0bGU+XG48L3N2ZWx0ZTpoZWFkPlxuPGRpdiBpZD1cIndyYXBwZXJcIj5cbiAgPGRpdiBpZD1cImNvbnRlbnRcIj5cbiAgICA8ZGl2IGlkPVwiY2VudGVyXCI+XG4gICAgICA8ZGl2IGNsYXNzPVwiY2FwdGlvblwiPlxuICAgICAgICA8aDE+ZmFsc2UgcXVvdGVzIGdlbmVyYXRvcjwvaDE+XG4gICAgICA8L2Rpdj5cblxuXG4gICAgICA8ZGl2PlxuICAgICAgICA8ZmlndXJlPlxuICAgICAgICAgIDxpbWcgY2xhc3M9XCJxdW90ZS1pbWdcIiBhbHQ9XCJRdW90ZVwiIHNyYz1cInF1b3RlLnBuZ1wiIC8+XG4gICAgICAgICAgeyNpZiBsb2FkaW5nfVxuICAgICAgICAgICAgPGZpZ2NhcHRpb24+XG4gICAgICAgICAgICAgIDxwPlxuICAgICAgICAgICAgICAgIDxpbWcgY2xhc3M9XCJsb2FkLWltZ1wiIGFsdD1cIkxvYWRpbmdcIiBzcmM9XCJhamF4LWxvYWRlci5naWZcIiAvPlxuICAgICAgICAgICAgICA8L3A+XG4gICAgICAgICAgICA8L2ZpZ2NhcHRpb24+XG4gICAgICAgICAgey9pZn1cbiAgICAgICAgICB7I2lmIGVycm9yfVxuICAgICAgICAgICAgPGZpZ2NhcHRpb24+XG4gICAgICAgICAgICAgIDxwPk9VQ0ghIFNvbWV0aGluZyB3ZW50IHdyb25nLiA6KDwvcD5cbiAgICAgICAgICAgIDwvZmlnY2FwdGlvbj5cbiAgICAgICAgICB7L2lmfVxuICAgICAgICAgIHsjaWYgIWxvYWRpbmcgJiYgcXVvdGUgJiYgY2VsZWJyaXR5fVxuICAgICAgICAgICAgPGZpZ2NhcHRpb24+XG4gICAgICAgICAgICAgIDxwIGNsYXNzPVwicXVvdGVcIj57cXVvdGV9PC9wPlxuICAgICAgICAgICAgICA8cCBjbGFzcz1cImNlbGVicml0eVwiPi0ge2NlbGVicml0eX08L3A+XG4gICAgICAgICAgICA8L2ZpZ2NhcHRpb24+XG4gICAgICAgICAgey9pZn1cbiAgICAgICAgPC9maWd1cmU+XG4gICAgICAgIDxzcGFuPlxuICAgICAgICAgIDxhXG4gICAgICAgICAgICBvbjpjbGljaz17aGFuZGxlQ2xpY2t9XG4gICAgICAgICAgICBocmVmPVwiaHR0cHM6Ly9yaWtlLmRldlwiXG4gICAgICAgICAgICB0aXRsZT1cIkJ1dHRvbiBwdXNoIGJsdWUvZ3JlZW5cIlxuICAgICAgICAgICAgY2xhc3M9XCJidXR0b24gYnRuUHVzaCBidG5CbHVlR3JlZW5cIj5cbiAgICAgICAgICAgIEdPIVxuICAgICAgICAgIDwvYT5cbiAgICAgICAgPC9zcGFuPlxuICAgICAgPC9kaXY+XG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuICA8Zm9vdGVyPlxuICAgIE1hZGUgd2l0aCDimaUgYW5kXG4gICAgPGEgaHJlZj1cImh0dHA6Ly9zdmVsdGUuZGV2XCIgdGFyZ2V0PVwiX2JsYW5rXCI+U3ZlbHRlLmpzPC9hPlxuICAgIGJ5XG4gICAgPGEgaHJlZj1cImh0dHBzOi8vcmlrZS5kZXZcIiB0YXJnZXQ9XCJfYmxhbmtcIj5SaWtlPC9hPlxuICAgIGluIDIwMTkuXG4gIDwvZm9vdGVyPlxuPC9kaXY+XG4iXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBaURFLGlCQUFFLENBQ0YscUJBQU0sQ0FDTixrQkFBRyxDQUNILENBQUMsZUFBQyxDQUFDLEFBQ0QsVUFBVSxDQUFFLE1BQU0sQ0FDbEIsTUFBTSxDQUFFLENBQUMsQ0FBQyxJQUFJLEFBQ2hCLENBQUMsQUFFRCxRQUFRLGVBQUMsQ0FBQyxBQUNSLE1BQU0sQ0FBRSxDQUFDLENBQUMsSUFBSSxDQUNkLFdBQVcsQ0FBRSxLQUFLLENBQ2xCLEtBQUssQ0FBRSxHQUFHLEFBQ1osQ0FBQyxBQUVELE1BQU0sZUFBQyxDQUFDLEFBQ04sS0FBSyxDQUFFLEdBQUcsQ0FDVixTQUFTLENBQUUsS0FBSyxDQUNoQixXQUFXLENBQUUsbUJBQW1CLENBQUMsQ0FBQyxPQUFPLENBQUMsQ0FBQyxLQUFLLENBQ2hELFVBQVUsQ0FBRSxNQUFNLEFBQ3BCLENBQUMsQUFFRCxVQUFVLGVBQUMsQ0FBQyxBQUNWLEtBQUssQ0FBRSxHQUFHLENBQ1YsVUFBVSxDQUFFLEtBQUssQ0FBQyxVQUFVLEFBQzlCLENBQUMsQUFFRCx1QkFBUSxNQUFNLEFBQUMsQ0FBQyxBQUNkLFVBQVUsQ0FBRSxJQUFJLENBQ2hCLGFBQWEsQ0FBRSxHQUFHLEFBQ3BCLENBQUMsQUFFRCxhQUFhLHVCQUFRLE1BQU0sQUFBQyxDQUFDLEFBQzNCLFVBQVUsQ0FBRSxHQUFHLENBQUMsR0FBRyxDQUFDLEdBQUcsQ0FBQyxHQUFHLENBQUMsT0FBTyxBQUNyQyxDQUFDLEFBRUQsZ0JBQUMsQ0FDRCxnQkFBQyxRQUFRLEFBQUMsQ0FBQyxBQUNULGVBQWUsQ0FBRSxJQUFJLENBQ3JCLEtBQUssQ0FBRSxPQUFPLEFBQ2hCLENBQUMsQUFFRCxDQUFDLE9BQU8sZUFBQyxDQUFDLEFBSVIsS0FBSyxDQUFFLEtBQUssQ0FDWixPQUFPLENBQUUsSUFBSSxDQUFDLElBQUksQ0FBQyxJQUFJLENBQUMsSUFBSSxDQUM1QixXQUFXLENBQUUsR0FBRyxDQUNoQixVQUFVLENBQUUsTUFBTSxDQUNsQixXQUFXLENBQUUsSUFBSSxDQUNqQixLQUFLLENBQUUsSUFBSSxDQUNYLGFBQWEsQ0FBRSxHQUFHLENBQ2xCLFVBQVUsQ0FBRSxHQUFHLENBQUMsSUFBSSxBQUN0QixDQUFDLEFBRUQsYUFBYSxRQUFRLGVBQUMsQ0FBQyxBQUNyQixVQUFVLENBQUUsR0FBRyxDQUFDLEdBQUcsQ0FBQyxHQUFHLENBQUMsR0FBRyxDQUFDLE9BQU8sQUFDckMsQ0FBQyxBQUVELGFBQWEsZUFBQyxDQUFDLEFBQ2IsVUFBVSxDQUFFLE9BQU8sQUFDckIsQ0FBQyxBQUVELGFBQWEsdUJBQVEsTUFBTSxBQUFDLENBQUMsQUFDM0IsVUFBVSxDQUFFLEdBQUcsQ0FBQyxHQUFHLENBQUMsR0FBRyxDQUFDLEdBQUcsQ0FBQyxPQUFPLEFBQ3JDLENBQUMsQUFFRCx1QkFBUSxNQUFNLEFBQUMsQ0FBQyxBQUNkLFVBQVUsQ0FBRSxJQUFJLENBQ2hCLGFBQWEsQ0FBRSxHQUFHLEFBQ3BCLENBQUMsQUFFRCxFQUFFLGVBQUMsQ0FBQyxBQUNGLFNBQVMsQ0FBRSxLQUFLLENBQ2hCLFdBQVcsQ0FBRSxHQUFHLENBQ2hCLE1BQU0sQ0FBRSxDQUFDLENBQUMsQ0FBQyxDQUFDLEtBQUssQ0FBQyxDQUFDLEFBQ3JCLENBQUMsQUFFRCxNQUFNLGVBQUMsQ0FBQyxBQUNOLE1BQU0sQ0FBRSxDQUFDLENBQUMsQ0FBQyxDQUFDLEdBQUcsQ0FBQyxDQUFDLEFBQ25CLENBQUMsQUFFRCxVQUFVLGVBQUMsQ0FBQyxBQUNWLEtBQUssQ0FBRSxJQUFJLENBQ1gsU0FBUyxDQUFFLElBQUksQ0FDZixNQUFNLENBQUUsQ0FBQyxDQUFDLENBQUMsQ0FBQyxHQUFHLENBQUMsQ0FBQyxBQUNuQixDQUFDLEFBRUQsU0FBUyxlQUFDLENBQUMsQUFDVCxLQUFLLENBQUUsSUFBSSxDQUNYLFNBQVMsQ0FBRSxJQUFJLENBQ2YsTUFBTSxDQUFFLENBQUMsQ0FBQyxDQUFDLENBQUMsR0FBRyxDQUFDLENBQUMsQUFDbkIsQ0FBQyxBQUVELE1BQU0sQUFBQyxZQUFZLEtBQUssQ0FBQyxBQUFDLENBQUMsQUFDekIsRUFBRSxlQUFDLENBQUMsQUFDRixTQUFTLENBQUUsR0FBRyxBQUNoQixDQUFDLEFBQ0gsQ0FBQyJ9 */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(document.head, style);
}

// (165:10) {#if loading}
function create_if_block_2(ctx) {
	var figcaption, p, img;

	return {
		c: function create() {
			figcaption = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("figcaption");
			p = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			img = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			this.h()
		},

		l: function claim(nodes) {
			figcaption = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "FIGCAPTION", {}, false);
			var figcaption_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(figcaption);

			p = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(figcaption_nodes, "P", { class: true }, false);
			var p_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p);

			img = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p_nodes, "IMG", { class: true, alt: true, src: true }, false);
			var img_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(img);

			img_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			p_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			figcaption_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			img.className = "load-img svelte-10zejvu";
			img.alt = "Loading";
			img.src = "ajax-loader.gif";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img, file, 167, 16, 2959);
			p.className = "svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p, file, 166, 14, 2939);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(figcaption, file, 165, 12, 2912);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, figcaption, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figcaption, p);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p, img);
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(figcaption);
			}
		}
	};
}

// (172:10) {#if error}
function create_if_block_1(ctx) {
	var figcaption, p, t;

	return {
		c: function create() {
			figcaption = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("figcaption");
			p = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("OUCH! Something went wrong. :(");
			this.h()
		},

		l: function claim(nodes) {
			figcaption = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "FIGCAPTION", {}, false);
			var figcaption_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(figcaption);

			p = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(figcaption_nodes, "P", { class: true }, false);
			var p_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p);

			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p_nodes, "OUCH! Something went wrong. :(");
			p_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			figcaption_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			p.className = "svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p, file, 173, 14, 3142);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(figcaption, file, 172, 12, 3115);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, figcaption, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figcaption, p);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p, t);
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(figcaption);
			}
		}
	};
}

// (177:10) {#if !loading && quote && celebrity}
function create_if_block(ctx) {
	var figcaption, p0, t0, t1, p1, t2, t3;

	return {
		c: function create() {
			figcaption = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("figcaption");
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(ctx.quote);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("- ");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(ctx.celebrity);
			this.h()
		},

		l: function claim(nodes) {
			figcaption = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "FIGCAPTION", {}, false);
			var figcaption_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(figcaption);

			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(figcaption_nodes, "P", { class: true }, false);
			var p0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p0);

			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, ctx.quote);
			p0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(figcaption_nodes, "\n              ");

			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(figcaption_nodes, "P", { class: true }, false);
			var p1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p1);

			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "- ");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, ctx.celebrity);
			p1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			figcaption_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			p0.className = "quote svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p0, file, 178, 14, 3308);
			p1.className = "celebrity svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p1, file, 179, 14, 3351);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(figcaption, file, 177, 12, 3281);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, figcaption, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figcaption, p0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p0, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figcaption, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figcaption, p1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, t3);
		},

		p: function update(changed, ctx) {
			if (changed.quote) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t0, ctx.quote);
			}

			if (changed.celebrity) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t3, ctx.celebrity);
			}
		},

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(figcaption);
			}
		}
	};
}

function create_fragment(ctx) {
	var t0, div4, div3, div2, div0, h1, t1, t2, div1, figure, img, t3, t4, t5, t6, span, a0, t7, t8, footer, t9, a1, t10, t11, a2, t12, t13, dispose;

	var if_block0 = (ctx.loading) && create_if_block_2(ctx);

	var if_block1 = (ctx.error) && create_if_block_1(ctx);

	var if_block2 = (!ctx.loading && ctx.quote && ctx.celebrity) && create_if_block(ctx);

	return {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h1");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("false quotes generator");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			figure = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("figure");
			img = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if (if_block0) if_block0.c();
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if (if_block1) if_block1.c();
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			if (if_block2) if_block2.c();
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			a0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("GO!");
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			footer = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("footer");
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Made with ♥ and\n    ");
			a1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Svelte.js");
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\n    by\n    ");
			a2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Rike");
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\n    in 2019.");
			this.h()
		},

		l: function claim(nodes) {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n");

			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { id: true, class: true }, false);
			var div4_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div4);

			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "DIV", { id: true, class: true }, false);
			var div3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div3);

			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div3_nodes, "DIV", { id: true, class: true }, false);
			var div2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div2);

			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "DIV", { class: true }, false);
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);

			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div0_nodes, "H1", { class: true }, false);
			var h1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h1);

			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h1_nodes, "false quotes generator");
			h1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div2_nodes, "\n\n\n      ");

			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "DIV", { class: true }, false);
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);

			figure = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "FIGURE", { class: true }, false);
			var figure_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(figure);

			img = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(figure_nodes, "IMG", { class: true, alt: true, src: true }, false);
			var img_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(img);

			img_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(figure_nodes, "\n          ");
			if (if_block0) if_block0.l(figure_nodes);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(figure_nodes, "\n          ");
			if (if_block1) if_block1.l(figure_nodes);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(figure_nodes, "\n          ");
			if (if_block2) if_block2.l(figure_nodes);
			figure_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div1_nodes, "\n        ");

			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "SPAN", {}, false);
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);

			a0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span_nodes, "A", { href: true, title: true, class: true }, false);
			var a0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a0);

			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a0_nodes, "GO!");
			a0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div4_nodes, "\n  ");

			footer = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "FOOTER", {}, false);
			var footer_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(footer);

			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(footer_nodes, "Made with ♥ and\n    ");

			a1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(footer_nodes, "A", { href: true, target: true, class: true }, false);
			var a1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a1);

			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a1_nodes, "Svelte.js");
			a1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(footer_nodes, "\n    by\n    ");

			a2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(footer_nodes, "A", { href: true, target: true, class: true }, false);
			var a2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a2);

			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a2_nodes, "Rike");
			a2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(footer_nodes, "\n    in 2019.");
			footer_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div4_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			document.title = "Sapper project template";
			h1.className = "svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h1, file, 157, 8, 2736);
			div0.className = "caption svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 156, 6, 2706);
			img.className = "quote-img svelte-10zejvu";
			img.alt = "Quote";
			img.src = "quote.png";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img, file, 163, 10, 2822);
			figure.className = "svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(figure, file, 162, 8, 2803);
			a0.href = "https://rike.dev";
			a0.title = "Button push blue/green";
			a0.className = "button btnPush btnBlueGreen svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a0, file, 184, 10, 3475);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 183, 8, 3458);
			div1.className = "svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 161, 6, 2789);
			div2.id = "center";
			div2.className = "svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div2, file, 155, 4, 2682);
			div3.id = "content";
			div3.className = "svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div3, file, 154, 2, 2659);
			a1.href = "http://svelte.dev";
			a1.target = "_blank";
			a1.className = "svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a1, file, 197, 4, 3756);
			a2.href = "https://rike.dev";
			a2.target = "_blank";
			a2.className = "svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a2, file, 199, 4, 3825);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(footer, file, 195, 2, 3723);
			div4.id = "wrapper";
			div4.className = "svelte-10zejvu";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div4, file, 153, 0, 2638);
			dispose = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen"])(a0, "click", ctx.handleClick);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, div4, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, div3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div3, div2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, div0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div0, h1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(h1, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, div1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, figure);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figure, img);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figure, t3);
			if (if_block0) if_block0.m(figure, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figure, t4);
			if (if_block1) if_block1.m(figure, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figure, t5);
			if (if_block2) if_block2.m(figure, null);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, span);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(span, a0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(a0, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, t8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, footer);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(footer, t9);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(footer, a1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(a1, t10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(footer, t11);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(footer, a2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(a2, t12);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(footer, t13);
		},

		p: function update(changed, ctx) {
			if (ctx.loading) {
				if (!if_block0) {
					if_block0 = create_if_block_2(ctx);
					if_block0.c();
					if_block0.m(figure, t4);
				}
			} else if (if_block0) {
				if_block0.d(1);
				if_block0 = null;
			}

			if (ctx.error) {
				if (!if_block1) {
					if_block1 = create_if_block_1(ctx);
					if_block1.c();
					if_block1.m(figure, t5);
				}
			} else if (if_block1) {
				if_block1.d(1);
				if_block1 = null;
			}

			if (!ctx.loading && ctx.quote && ctx.celebrity) {
				if (if_block2) {
					if_block2.p(changed, ctx);
				} else {
					if_block2 = create_if_block(ctx);
					if_block2.c();
					if_block2.m(figure, null);
				}
			} else if (if_block2) {
				if_block2.d(1);
				if_block2 = null;
			}
		},

		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t0);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(div4);
			}

			if (if_block0) if_block0.d();
			if (if_block1) if_block1.d();
			if (if_block2) if_block2.d();
			dispose();
		}
	};
}

function preload({ params, query }) {
  // nothing todo
}

function instance($$self, $$props, $$invalidate) {
	let quote = "";
  let celebrity = "";
  let loading = false;
  let error = "";

  async function getQuote() {
    $$invalidate('quote', quote = "");
    $$invalidate('celebrity', celebrity = "");
    $$invalidate('error', error = "");
    var urly = "http://localhost:3333/quote";
    try {
      let response = await Object(_helpers__WEBPACK_IMPORTED_MODULE_1__["default"])(10 * 60 * 1000, fetch(urly));
      let data = await response.json();
      console.log(data);
      $$invalidate('quote', quote = data);
    } catch (error) {
      $$invalidate('error', error);
      console.error(error);
    }
  }
  async function getCelebrity() {
    var urly = "http://localhost:3333/celebrity";
    try {
      let response = await Object(_helpers__WEBPACK_IMPORTED_MODULE_1__["default"])(1 * 5 * 1000, fetch(urly));
      let data = await response.json();
      console.log(data);
      $$invalidate('celebrity', celebrity = data);
    } catch (error) {
      $$invalidate('error', error);
      console.error(error);
    }
  }
  async function handleClick(event) {
    event.preventDefault();
    $$invalidate('loading', loading = true);
    await getQuote();
    await getCelebrity();
    $$invalidate('loading', loading = false);
  }

	return {
		quote,
		celebrity,
		loading,
		error,
		handleClick
	};
}

class Routes extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-10zejvu-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], []);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Routes);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvaGVscGVycy5qcyIsIndlYnBhY2s6Ly8vLi9zcmMvcm91dGVzL2luZGV4LnN2ZWx0ZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7O0FBQUE7QUFBQTtBQUFlO0FBQ2Y7QUFDQTtBQUNBO0FBQ0EsT0FBTztBQUNQO0FBQ0E7QUFDQTtBQUNBO0FBQ0EsU0FBUztBQUNUO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQSxLQUFLO0FBQ0wsRzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt5RUNrS2dDLEtBQUs7Ozs7eUVBQ0MsU0FBUzs7Ozs7Ozs7Ozs7eUZBRGYsS0FBSzs7Ozs7Ozs7eUZBQ0MsU0FBUzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7NkVBRGYsS0FBSzs7Ozs2RUFDQyxTQUFTOzs7Ozs7Ozs7Ozs7Ozs7c0JBZmhDLE9BQU87O3NCQU9QLEtBQUs7O2tCQUtMLEtBQUMsT0FBTyxRQUFJLEtBQUssUUFBSSxTQUFTOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7NkZBU3ZCLFdBQVc7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7V0FyQmxCLE9BQU87Ozs7Ozs7Ozs7O1dBT1AsS0FBSzs7Ozs7Ozs7Ozs7T0FLTCxLQUFDLE9BQU8sUUFBSSxLQUFLLFFBQUksU0FBUzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQXJJM0MsU0FBUyxPQUFPLENBQUMsRUFBRSxNQUFNLEVBQUUsS0FBSyxFQUFFLEVBQUU7QUFDcEM7QUFDQSxDQUFDOzs7Q0ExQ0QsSUFBSSxLQUFLLEdBQUcsRUFBRSxDQUFDO0VBQ2YsSUFBSSxTQUFTLEdBQUcsRUFBRSxDQUFDO0VBQ25CLElBQUksT0FBTyxHQUFHLEtBQUssQ0FBQztFQUNwQixJQUFJLEtBQUssR0FBRyxFQUFFLENBQUM7O0VBRWYsZUFBZSxRQUFRLEdBQUc7MEJBQ3hCLEtBQUssR0FBRyxHQUFFLENBQUM7OEJBQ1gsU0FBUyxHQUFHLEdBQUUsQ0FBQzswQkFDZixLQUFLLEdBQUcsR0FBRSxDQUFDO0lBQ1gsSUFBSSxJQUFJLEdBQUcsNkJBQTZCLENBQUM7SUFDekMsSUFBSTtNQUNGLElBQUksUUFBUSxHQUFHLE1BQU0sd0RBQWMsQ0FBQyxFQUFFLEdBQUcsRUFBRSxHQUFHLElBQUksRUFBRSxLQUFLLENBQUMsSUFBSSxDQUFDLENBQUMsQ0FBQztNQUNqRSxJQUFJLElBQUksR0FBRyxNQUFNLFFBQVEsQ0FBQyxJQUFJLEVBQUUsQ0FBQztNQUNqQyxPQUFPLENBQUMsR0FBRyxDQUFDLElBQUksQ0FBQyxDQUFDOzRCQUNsQixLQUFLLEdBQUcsS0FBSSxDQUFDO0tBQ2QsQ0FBQyxPQUFPLEtBQUssRUFBRTtNQUNkLDRCQUFhLENBQUM7TUFDZCxPQUFPLENBQUMsS0FBSyxDQUFDLEtBQUssQ0FBQyxDQUFDO0tBQ3RCO0dBQ0Y7RUFDRCxlQUFlLFlBQVksR0FBRztJQUM1QixJQUFJLElBQUksR0FBRyxpQ0FBaUMsQ0FBQztJQUM3QyxJQUFJO01BQ0YsSUFBSSxRQUFRLEdBQUcsTUFBTSx3REFBYyxDQUFDLENBQUMsR0FBRyxDQUFDLEdBQUcsSUFBSSxFQUFFLEtBQUssQ0FBQyxJQUFJLENBQUMsQ0FBQyxDQUFDO01BQy9ELElBQUksSUFBSSxHQUFHLE1BQU0sUUFBUSxDQUFDLElBQUksRUFBRSxDQUFDO01BQ2pDLE9BQU8sQ0FBQyxHQUFHLENBQUMsSUFBSSxDQUFDLENBQUM7Z0NBQ2xCLFNBQVMsR0FBRyxLQUFJLENBQUM7S0FDbEIsQ0FBQyxPQUFPLEtBQUssRUFBRTtNQUNkLDRCQUFhLENBQUM7TUFDZCxPQUFPLENBQUMsS0FBSyxDQUFDLEtBQUssQ0FBQyxDQUFDO0tBQ3RCO0dBQ0Y7RUFDRCxlQUFlLFdBQVcsQ0FBQyxLQUFLLEVBQUU7SUFDaEMsS0FBSyxDQUFDLGNBQWMsRUFBRSxDQUFDOzRCQUN2QixPQUFPLEdBQUcsS0FBSSxDQUFDO0lBQ2YsTUFBTSxRQUFRLEVBQUUsQ0FBQztJQUNqQixNQUFNLFlBQVksRUFBRSxDQUFDOzRCQUNyQixPQUFPLEdBQUcsTUFBSyxDQUFDO0dBQ2pCIiwiZmlsZSI6ImU5ZmNiNTllY2I3NTBiMDJiNjFiL2luZGV4LmluZGV4LmpzIiwic291cmNlc0NvbnRlbnQiOlsiZXhwb3J0IGRlZmF1bHQgZnVuY3Rpb24gdGltZW91dFByb21pc2UobXMsIHByb21pc2UpIHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgdGltZW91dElkID0gc2V0VGltZW91dCgoKSA9PiB7XG4gICAgICAgIHJlamVjdChuZXcgRXJyb3IoXCJwcm9taXNlIHRpbWVvdXRcIikpXG4gICAgICB9LCBtcyk7XG4gICAgICBwcm9taXNlLnRoZW4oXG4gICAgICAgIChyZXMpID0+IHtcbiAgICAgICAgICBjbGVhclRpbWVvdXQodGltZW91dElkKTtcbiAgICAgICAgICByZXNvbHZlKHJlcyk7XG4gICAgICAgIH0sXG4gICAgICAgIChlcnIpID0+IHtcbiAgICAgICAgICBjbGVhclRpbWVvdXQodGltZW91dElkKTtcbiAgICAgICAgICByZWplY3QoZXJyKTtcbiAgICAgICAgfVxuICAgICAgKTtcbiAgICB9KVxuICB9IiwiPHNjcmlwdD5cbiAgaW1wb3J0IHRpbWVvdXRQcm9taXNlIGZyb20gXCIuLi9oZWxwZXJzXCI7XG5cbiAgbGV0IHF1b3RlID0gXCJcIjtcbiAgbGV0IGNlbGVicml0eSA9IFwiXCI7XG4gIGxldCBsb2FkaW5nID0gZmFsc2U7XG4gIGxldCBlcnJvciA9IFwiXCI7XG5cbiAgYXN5bmMgZnVuY3Rpb24gZ2V0UXVvdGUoKSB7XG4gICAgcXVvdGUgPSBcIlwiO1xuICAgIGNlbGVicml0eSA9IFwiXCI7XG4gICAgZXJyb3IgPSBcIlwiO1xuICAgIHZhciB1cmx5ID0gXCJodHRwOi8vbG9jYWxob3N0OjMzMzMvcXVvdGVcIjtcbiAgICB0cnkge1xuICAgICAgbGV0IHJlc3BvbnNlID0gYXdhaXQgdGltZW91dFByb21pc2UoMTAgKiA2MCAqIDEwMDAsIGZldGNoKHVybHkpKTtcbiAgICAgIGxldCBkYXRhID0gYXdhaXQgcmVzcG9uc2UuanNvbigpO1xuICAgICAgY29uc29sZS5sb2coZGF0YSk7XG4gICAgICBxdW90ZSA9IGRhdGE7XG4gICAgfSBjYXRjaCAoZXJyb3IpIHtcbiAgICAgIGVycm9yID0gZXJyb3I7XG4gICAgICBjb25zb2xlLmVycm9yKGVycm9yKTtcbiAgICB9XG4gIH1cbiAgYXN5bmMgZnVuY3Rpb24gZ2V0Q2VsZWJyaXR5KCkge1xuICAgIHZhciB1cmx5ID0gXCJodHRwOi8vbG9jYWxob3N0OjMzMzMvY2VsZWJyaXR5XCI7XG4gICAgdHJ5IHtcbiAgICAgIGxldCByZXNwb25zZSA9IGF3YWl0IHRpbWVvdXRQcm9taXNlKDEgKiA1ICogMTAwMCwgZmV0Y2godXJseSkpO1xuICAgICAgbGV0IGRhdGEgPSBhd2FpdCByZXNwb25zZS5qc29uKCk7XG4gICAgICBjb25zb2xlLmxvZyhkYXRhKTtcbiAgICAgIGNlbGVicml0eSA9IGRhdGE7XG4gICAgfSBjYXRjaCAoZXJyb3IpIHtcbiAgICAgIGVycm9yID0gZXJyb3I7XG4gICAgICBjb25zb2xlLmVycm9yKGVycm9yKTtcbiAgICB9XG4gIH1cbiAgYXN5bmMgZnVuY3Rpb24gaGFuZGxlQ2xpY2soZXZlbnQpIHtcbiAgICBldmVudC5wcmV2ZW50RGVmYXVsdCgpO1xuICAgIGxvYWRpbmcgPSB0cnVlO1xuICAgIGF3YWl0IGdldFF1b3RlKCk7XG4gICAgYXdhaXQgZ2V0Q2VsZWJyaXR5KCk7XG4gICAgbG9hZGluZyA9IGZhbHNlO1xuICB9XG5cbiAgZnVuY3Rpb24gcHJlbG9hZCh7IHBhcmFtcywgcXVlcnkgfSkge1xuICAgIC8vIG5vdGhpbmcgdG9kb1xuICB9XG48L3NjcmlwdD5cblxuPHN0eWxlPlxuICBoMSxcbiAgZmlndXJlLFxuICBkaXYsXG4gIHAge1xuICAgIHRleHQtYWxpZ246IGNlbnRlcjtcbiAgICBtYXJnaW46IDAgYXV0bztcbiAgfVxuXG4gIC5jYXB0aW9uIHtcbiAgICBtYXJnaW46IDAgYXV0bztcbiAgICBwYWRkaW5nLXRvcDogMi41ZW07XG4gICAgd2lkdGg6IDcwJTtcbiAgfVxuXG4gIC5xdW90ZSB7XG4gICAgd2lkdGg6IDcwJTtcbiAgICBmb250LXNpemU6IDEuOGVtO1xuICAgIGZvbnQtZmFtaWx5OiBcIkxpYnJlIEJhc2tlcnZpbGxlXCIsIEdlb3JnaWEsIHNlcmlmO1xuICAgIGZvbnQtc3R5bGU6IGl0YWxpYztcbiAgfVxuXG4gIC5jZWxlYnJpdHkge1xuICAgIHdpZHRoOiA3MCU7XG4gICAgdGV4dC1hbGlnbjogcmlnaHQgIWltcG9ydGFudDtcbiAgfVxuXG4gIC5idG5QdXNoOmhvdmVyIHtcbiAgICBtYXJnaW4tdG9wOiAxNXB4O1xuICAgIG1hcmdpbi1ib3R0b206IDVweDtcbiAgfVxuXG4gIC5idG5CbHVlR3JlZW4uYnRuUHVzaDpob3ZlciB7XG4gICAgYm94LXNoYWRvdzogMHB4IDBweCAwcHggMHB4ICMwMDcxNDQ7XG4gIH1cblxuICBhLFxuICBhOnZpc2l0ZWQge1xuICAgIHRleHQtZGVjb3JhdGlvbjogbm9uZTtcbiAgICBjb2xvcjogIzAwYWU2ODtcbiAgfVxuXG4gIGEuYnV0dG9uIHtcbiAgICAvKiBkaXNwbGF5OiBibG9jaztcbiAgICBwb3NpdGlvbjogcmVsYXRpdmU7IFxuICAgIGZsb2F0OiBsZWZ0OyovXG4gICAgd2lkdGg6IDEyMHB4O1xuICAgIHBhZGRpbmc6IDEwcHggNTBweCAxMHB4IDUwcHg7XG4gICAgZm9udC13ZWlnaHQ6IDYwMDtcbiAgICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gICAgbGluZS1oZWlnaHQ6IDUwcHg7XG4gICAgY29sb3I6ICNmZmY7XG4gICAgYm9yZGVyLXJhZGl1czogNXB4O1xuICAgIHRyYW5zaXRpb246IGFsbCAwLjJzO1xuICB9XG5cbiAgLmJ0bkJsdWVHcmVlbi5idG5QdXNoIHtcbiAgICBib3gtc2hhZG93OiAwcHggNXB4IDBweCAwcHggIzAwNzE0NDtcbiAgfVxuXG4gIC5idG5CbHVlR3JlZW4ge1xuICAgIGJhY2tncm91bmQ6ICMwMGFlNjg7XG4gIH1cblxuICAuYnRuQmx1ZUdyZWVuLmJ0blB1c2g6aG92ZXIge1xuICAgIGJveC1zaGFkb3c6IDBweCAwcHggMHB4IDBweCAjMDA3MTQ0O1xuICB9XG5cbiAgLmJ0blB1c2g6aG92ZXIge1xuICAgIG1hcmdpbi10b3A6IDE1cHg7XG4gICAgbWFyZ2luLWJvdHRvbTogNXB4O1xuICB9XG5cbiAgaDEge1xuICAgIGZvbnQtc2l6ZTogMi44ZW07XG4gICAgZm9udC13ZWlnaHQ6IDcwMDtcbiAgICBtYXJnaW46IDAgMCAwLjVlbSAwO1xuICB9XG5cbiAgZmlndXJlIHtcbiAgICBtYXJnaW46IDAgMCAxZW0gMDtcbiAgfVxuXG4gIC5xdW90ZS1pbWcge1xuICAgIHdpZHRoOiAxMDAlO1xuICAgIG1heC13aWR0aDogODBweDtcbiAgICBtYXJnaW46IDAgMCAxZW0gMDtcbiAgfVxuXG4gIC5sb2FkLWltZyB7XG4gICAgd2lkdGg6IDEwMCU7XG4gICAgbWF4LXdpZHRoOiAzMHB4O1xuICAgIG1hcmdpbjogMCAwIDFlbSAwO1xuICB9XG5cbiAgQG1lZGlhIChtaW4td2lkdGg6IDQ4MHB4KSB7XG4gICAgaDEge1xuICAgICAgZm9udC1zaXplOiA0ZW07XG4gICAgfVxuICB9XG48L3N0eWxlPlxuXG48c3ZlbHRlOmhlYWQ+XG4gIDx0aXRsZT5TYXBwZXIgcHJvamVjdCB0ZW1wbGF0ZTwvdGl0bGU+XG48L3N2ZWx0ZTpoZWFkPlxuPGRpdiBpZD1cIndyYXBwZXJcIj5cbiAgPGRpdiBpZD1cImNvbnRlbnRcIj5cbiAgICA8ZGl2IGlkPVwiY2VudGVyXCI+XG4gICAgICA8ZGl2IGNsYXNzPVwiY2FwdGlvblwiPlxuICAgICAgICA8aDE+ZmFsc2UgcXVvdGVzIGdlbmVyYXRvcjwvaDE+XG4gICAgICA8L2Rpdj5cblxuXG4gICAgICA8ZGl2PlxuICAgICAgICA8ZmlndXJlPlxuICAgICAgICAgIDxpbWcgY2xhc3M9XCJxdW90ZS1pbWdcIiBhbHQ9XCJRdW90ZVwiIHNyYz1cInF1b3RlLnBuZ1wiIC8+XG4gICAgICAgICAgeyNpZiBsb2FkaW5nfVxuICAgICAgICAgICAgPGZpZ2NhcHRpb24+XG4gICAgICAgICAgICAgIDxwPlxuICAgICAgICAgICAgICAgIDxpbWcgY2xhc3M9XCJsb2FkLWltZ1wiIGFsdD1cIkxvYWRpbmdcIiBzcmM9XCJhamF4LWxvYWRlci5naWZcIiAvPlxuICAgICAgICAgICAgICA8L3A+XG4gICAgICAgICAgICA8L2ZpZ2NhcHRpb24+XG4gICAgICAgICAgey9pZn1cbiAgICAgICAgICB7I2lmIGVycm9yfVxuICAgICAgICAgICAgPGZpZ2NhcHRpb24+XG4gICAgICAgICAgICAgIDxwPk9VQ0ghIFNvbWV0aGluZyB3ZW50IHdyb25nLiA6KDwvcD5cbiAgICAgICAgICAgIDwvZmlnY2FwdGlvbj5cbiAgICAgICAgICB7L2lmfVxuICAgICAgICAgIHsjaWYgIWxvYWRpbmcgJiYgcXVvdGUgJiYgY2VsZWJyaXR5fVxuICAgICAgICAgICAgPGZpZ2NhcHRpb24+XG4gICAgICAgICAgICAgIDxwIGNsYXNzPVwicXVvdGVcIj57cXVvdGV9PC9wPlxuICAgICAgICAgICAgICA8cCBjbGFzcz1cImNlbGVicml0eVwiPi0ge2NlbGVicml0eX08L3A+XG4gICAgICAgICAgICA8L2ZpZ2NhcHRpb24+XG4gICAgICAgICAgey9pZn1cbiAgICAgICAgPC9maWd1cmU+XG4gICAgICAgIDxzcGFuPlxuICAgICAgICAgIDxhXG4gICAgICAgICAgICBvbjpjbGljaz17aGFuZGxlQ2xpY2t9XG4gICAgICAgICAgICBocmVmPVwiaHR0cHM6Ly9yaWtlLmRldlwiXG4gICAgICAgICAgICB0aXRsZT1cIkJ1dHRvbiBwdXNoIGJsdWUvZ3JlZW5cIlxuICAgICAgICAgICAgY2xhc3M9XCJidXR0b24gYnRuUHVzaCBidG5CbHVlR3JlZW5cIj5cbiAgICAgICAgICAgIEdPIVxuICAgICAgICAgIDwvYT5cbiAgICAgICAgPC9zcGFuPlxuICAgICAgPC9kaXY+XG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuICA8Zm9vdGVyPlxuICAgIE1hZGUgd2l0aCDimaUgYW5kXG4gICAgPGEgaHJlZj1cImh0dHA6Ly9zdmVsdGUuZGV2XCIgdGFyZ2V0PVwiX2JsYW5rXCI+U3ZlbHRlLmpzPC9hPlxuICAgIGJ5XG4gICAgPGEgaHJlZj1cImh0dHBzOi8vcmlrZS5kZXZcIiB0YXJnZXQ9XCJfYmxhbmtcIj5SaWtlPC9hPlxuICAgIGluIDIwMTkuXG4gIDwvZm9vdGVyPlxuPC9kaXY+XG4iXSwic291cmNlUm9vdCI6IiJ9