(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["index"],{

/***/ "./src/routes/index.svelte":
/*!*********************************!*\
  !*** ./src/routes/index.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal.mjs");
/* src/routes/index.svelte generated by Svelte v3.2.0 */


const file = "src/routes/index.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = 'svelte-va4q69-style';
	style.textContent = "h1.svelte-va4q69,figure.svelte-va4q69,p.svelte-va4q69{text-align:center;margin:0 auto}.caption.svelte-va4q69{margin:0 auto;padding-top:200px;width:70%}.quote.svelte-va4q69{font-family:\"Libre Baskerville\", Georgia, serif}.btnBlueGreen.btnPush.svelte-va4q69{box-shadow:0px 5px 0px 0px #007144}.btnBlueGreen.svelte-va4q69{background:#00ae68}a.button.svelte-va4q69{display:block;position:relative;float:left;width:120px;padding:0;margin:10px 20px 10px 0;font-weight:600;text-align:center;line-height:50px;color:#fff;border-radius:5px;transition:all 0.2s}.btnPush.svelte-va4q69:hover{margin-top:15px;margin-bottom:5px}.btnBlueGreen.btnPush.svelte-va4q69:hover{box-shadow:0px 0px 0px 0px #007144}h1.svelte-va4q69{font-size:2.8em;font-weight:700;margin:0 0 0.5em 0}figure.svelte-va4q69{margin:0 0 1em 0}img.svelte-va4q69{width:100%;max-width:400px;margin:0 0 1em 0}p.svelte-va4q69{margin:1em auto}@media(min-width: 480px){h1.svelte-va4q69{font-size:4em}}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguc3ZlbHRlIiwic291cmNlcyI6WyJpbmRleC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgbGV0IGNvdW50ID0gMDtcbiAgbGV0IHF1b3RlID0gXCJcIjtcblxuICBhc3luYyBmdW5jdGlvbiBnZXRRdW90ZSgpIHtcbiAgICAvLyBjb3VudCArPSAxO1xuICAgIHZhciB1cmx5ID0gXCJodHRwOi8vbG9jYWxob3N0OjMzMzMvcXVvdGVcIjtcbiAgICBsZXQgcmVzcG9uc2UgPSBhd2FpdCBmZXRjaCh1cmx5KTtcbiAgICBsZXQgZGF0YSA9IGF3YWl0IHJlc3BvbnNlLmpzb24oKTtcbiAgICBjb25zb2xlLmxvZyhkYXRhKTtcbiAgICByZXR1cm4geyBxdW90ZTogcmVzcG9uc2UgfTsgLy8gPCEtLSBhbmQgd2UncmUgcmV0dXJuaW5nIHRoZSByZXN1bHQsIHJhdGhlciB0aGFuIHRoaXMuc2V0KC4uLilcbiAgfVxuICBhc3luYyBmdW5jdGlvbiBnZXRDZWxlYnJpdHkoKSB7XG4gICAgdmFyIHVybHkgPSBcImh0dHA6Ly9sb2NhbGhvc3Q6MzMzMy9jZWxlYnJpdHlcIjtcbiAgICBsZXQgcmVzcG9uc2UgPSBhd2FpdCBmZXRjaCh1cmx5KTtcbiAgICBsZXQgZGF0YSA9IGF3YWl0IHJlc3BvbnNlLmpzb24oKTtcbiAgICBjb25zb2xlLmxvZyhkYXRhKTtcbiAgICByZXR1cm4geyBjZWxlYnJpdHk6IHJlc3BvbnNlIH07XG4gIH1cbiAgYXN5bmMgZnVuY3Rpb24gaGFuZGxlQ2xpY2soZXZlbnQpIHtcbiAgICBnZXRRdW90ZSgpO1xuICAgIGdldENlbGVicml0eSgpO1xuICB9XG5cbiAgZnVuY3Rpb24gcHJlbG9hZCh7IHBhcmFtcywgcXVlcnkgfSkge1xuICAgIC8vIG5vdGhpbmcgdG9kb1xuICB9XG48L3NjcmlwdD5cblxuPHN0eWxlPlxuICBoMSxcbiAgZmlndXJlLFxuICBwIHtcbiAgICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gICAgbWFyZ2luOiAwIGF1dG87XG4gIH1cblxuICAuY2FwdGlvbiB7XG4gICAgbWFyZ2luOiAwIGF1dG87XG4gICAgcGFkZGluZy10b3A6IDIwMHB4O1xuICAgIHdpZHRoOiA3MCU7XG4gIH1cblxuICAucXVvdGUge1xuICAgIGZvbnQtZmFtaWx5OiBcIkxpYnJlIEJhc2tlcnZpbGxlXCIsIEdlb3JnaWEsIHNlcmlmO1xuICB9XG5cbiAgLyogM0QgKi9cbiAgLmJ0bkJsdWVHcmVlbi5idG5QdXNoIHtcbiAgICBib3gtc2hhZG93OiAwcHggNXB4IDBweCAwcHggIzAwNzE0NDtcbiAgfVxuXG4gIC5idG5CbHVlR3JlZW4ge1xuICAgIGJhY2tncm91bmQ6ICMwMGFlNjg7XG4gIH1cblxuICBhLmJ1dHRvbiB7XG4gICAgZGlzcGxheTogYmxvY2s7XG4gICAgcG9zaXRpb246IHJlbGF0aXZlO1xuICAgIGZsb2F0OiBsZWZ0O1xuICAgIHdpZHRoOiAxMjBweDtcbiAgICBwYWRkaW5nOiAwO1xuICAgIG1hcmdpbjogMTBweCAyMHB4IDEwcHggMDtcbiAgICBmb250LXdlaWdodDogNjAwO1xuICAgIHRleHQtYWxpZ246IGNlbnRlcjtcbiAgICBsaW5lLWhlaWdodDogNTBweDtcbiAgICBjb2xvcjogI2ZmZjtcbiAgICBib3JkZXItcmFkaXVzOiA1cHg7XG4gICAgdHJhbnNpdGlvbjogYWxsIDAuMnM7XG4gIH1cblxuICAuYnRuUHVzaDpob3ZlciB7XG4gICAgbWFyZ2luLXRvcDogMTVweDtcbiAgICBtYXJnaW4tYm90dG9tOiA1cHg7XG4gIH1cblxuICAuYnRuQmx1ZUdyZWVuLmJ0blB1c2g6aG92ZXIge1xuICAgIGJveC1zaGFkb3c6IDBweCAwcHggMHB4IDBweCAjMDA3MTQ0O1xuICB9XG5cbiAgaDEge1xuICAgIGZvbnQtc2l6ZTogMi44ZW07XG4gICAgZm9udC13ZWlnaHQ6IDcwMDtcbiAgICBtYXJnaW46IDAgMCAwLjVlbSAwO1xuICB9XG5cbiAgZmlndXJlIHtcbiAgICBtYXJnaW46IDAgMCAxZW0gMDtcbiAgfVxuXG4gIGltZyB7XG4gICAgd2lkdGg6IDEwMCU7XG4gICAgbWF4LXdpZHRoOiA0MDBweDtcbiAgICBtYXJnaW46IDAgMCAxZW0gMDtcbiAgfVxuXG4gIHAge1xuICAgIG1hcmdpbjogMWVtIGF1dG87XG4gIH1cblxuICBAbWVkaWEgKG1pbi13aWR0aDogNDgwcHgpIHtcbiAgICBoMSB7XG4gICAgICBmb250LXNpemU6IDRlbTtcbiAgICB9XG4gIH1cbjwvc3R5bGU+XG5cbjxzdmVsdGU6aGVhZD5cbiAgPHRpdGxlPlNhcHBlciBwcm9qZWN0IHRlbXBsYXRlPC90aXRsZT5cbjwvc3ZlbHRlOmhlYWQ+XG48ZGl2IGNsYXNzPVwiY2FwdGlvblwiPlxuICA8aDE+ZmFsc2UgcXVvdGVzIGdlbmVyYXRvcjwvaDE+XG48L2Rpdj5cblxuPGRpdj5cbiAgPGZpZ3VyZT5cbiAgICA8aW1nIGFsdD1cIkJvcmF0XCIgc3JjPVwiZ3JlYXQtc3VjY2Vzcy5wbmdcIiAvPlxuICAgIDxmaWdjYXB0aW9uPkhJR0ggRklWRSE8L2ZpZ2NhcHRpb24+XG4gIDwvZmlndXJlPlxuXG4gIDxwPlxuICAgIDxzdHJvbmc+XG4gICAgICBUcnkgZWRpdGluZyB0aGlzIGZpbGUgKHJvdXRlcy9pbmRleC5odG1sKSB0byB0ZXN0IGxpdmUgcmVsb2FkaW5nLlxuICAgIDwvc3Ryb25nPlxuXG4gICAgPGJ1dHRvbiBvbjpjbGljaz17aGFuZGxlQ2xpY2t9PlxuICAgICAgPGEgaHJlZj1cIlwiIHRpdGxlPVwiQnV0dG9uIHB1c2ggYmx1ZS9ncmVlblwiIGNsYXNzPVwiYnV0dG9uIGJ0blB1c2ggYnRuQmx1ZUdyZWVuXCI+XG4gICAgICAgIFB1c2hcbiAgICAgIDwvYT5cbiAgICA8L2J1dHRvbj5cbiAgPC9wPlxuXG4gIDxwIGNsYXNzPVwicXVvdGVcIj5kc2Zkc2ZzZjwvcD5cbjwvZGl2PlxuIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQThCRSxnQkFBRSxDQUNGLG9CQUFNLENBQ04sQ0FBQyxjQUFDLENBQUMsQUFDRCxVQUFVLENBQUUsTUFBTSxDQUNsQixNQUFNLENBQUUsQ0FBQyxDQUFDLElBQUksQUFDaEIsQ0FBQyxBQUVELFFBQVEsY0FBQyxDQUFDLEFBQ1IsTUFBTSxDQUFFLENBQUMsQ0FBQyxJQUFJLENBQ2QsV0FBVyxDQUFFLEtBQUssQ0FDbEIsS0FBSyxDQUFFLEdBQUcsQUFDWixDQUFDLEFBRUQsTUFBTSxjQUFDLENBQUMsQUFDTixXQUFXLENBQUUsbUJBQW1CLENBQUMsQ0FBQyxPQUFPLENBQUMsQ0FBQyxLQUFLLEFBQ2xELENBQUMsQUFHRCxhQUFhLFFBQVEsY0FBQyxDQUFDLEFBQ3JCLFVBQVUsQ0FBRSxHQUFHLENBQUMsR0FBRyxDQUFDLEdBQUcsQ0FBQyxHQUFHLENBQUMsT0FBTyxBQUNyQyxDQUFDLEFBRUQsYUFBYSxjQUFDLENBQUMsQUFDYixVQUFVLENBQUUsT0FBTyxBQUNyQixDQUFDLEFBRUQsQ0FBQyxPQUFPLGNBQUMsQ0FBQyxBQUNSLE9BQU8sQ0FBRSxLQUFLLENBQ2QsUUFBUSxDQUFFLFFBQVEsQ0FDbEIsS0FBSyxDQUFFLElBQUksQ0FDWCxLQUFLLENBQUUsS0FBSyxDQUNaLE9BQU8sQ0FBRSxDQUFDLENBQ1YsTUFBTSxDQUFFLElBQUksQ0FBQyxJQUFJLENBQUMsSUFBSSxDQUFDLENBQUMsQ0FDeEIsV0FBVyxDQUFFLEdBQUcsQ0FDaEIsVUFBVSxDQUFFLE1BQU0sQ0FDbEIsV0FBVyxDQUFFLElBQUksQ0FDakIsS0FBSyxDQUFFLElBQUksQ0FDWCxhQUFhLENBQUUsR0FBRyxDQUNsQixVQUFVLENBQUUsR0FBRyxDQUFDLElBQUksQUFDdEIsQ0FBQyxBQUVELHNCQUFRLE1BQU0sQUFBQyxDQUFDLEFBQ2QsVUFBVSxDQUFFLElBQUksQ0FDaEIsYUFBYSxDQUFFLEdBQUcsQUFDcEIsQ0FBQyxBQUVELGFBQWEsc0JBQVEsTUFBTSxBQUFDLENBQUMsQUFDM0IsVUFBVSxDQUFFLEdBQUcsQ0FBQyxHQUFHLENBQUMsR0FBRyxDQUFDLEdBQUcsQ0FBQyxPQUFPLEFBQ3JDLENBQUMsQUFFRCxFQUFFLGNBQUMsQ0FBQyxBQUNGLFNBQVMsQ0FBRSxLQUFLLENBQ2hCLFdBQVcsQ0FBRSxHQUFHLENBQ2hCLE1BQU0sQ0FBRSxDQUFDLENBQUMsQ0FBQyxDQUFDLEtBQUssQ0FBQyxDQUFDLEFBQ3JCLENBQUMsQUFFRCxNQUFNLGNBQUMsQ0FBQyxBQUNOLE1BQU0sQ0FBRSxDQUFDLENBQUMsQ0FBQyxDQUFDLEdBQUcsQ0FBQyxDQUFDLEFBQ25CLENBQUMsQUFFRCxHQUFHLGNBQUMsQ0FBQyxBQUNILEtBQUssQ0FBRSxJQUFJLENBQ1gsU0FBUyxDQUFFLEtBQUssQ0FDaEIsTUFBTSxDQUFFLENBQUMsQ0FBQyxDQUFDLENBQUMsR0FBRyxDQUFDLENBQUMsQUFDbkIsQ0FBQyxBQUVELENBQUMsY0FBQyxDQUFDLEFBQ0QsTUFBTSxDQUFFLEdBQUcsQ0FBQyxJQUFJLEFBQ2xCLENBQUMsQUFFRCxNQUFNLEFBQUMsWUFBWSxLQUFLLENBQUMsQUFBQyxDQUFDLEFBQ3pCLEVBQUUsY0FBQyxDQUFDLEFBQ0YsU0FBUyxDQUFFLEdBQUcsQUFDaEIsQ0FBQyxBQUNILENBQUMifQ== */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(document.head, style);
}

function create_fragment(ctx) {
	var t0, div0, h1, t1, t2, div1, figure, img, t3, figcaption, t4, t5, p0, strong, t6, t7, button, a, t8, t9, p1, t10, dispose;

	return {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h1");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("false quotes generator");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			figure = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("figure");
			img = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			figcaption = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("figcaption");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("HIGH FIVE!");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			strong = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("strong");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Try editing this file (routes/index.html) to test live reloading.");
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			button = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("button");
			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Push");
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("dsfdsfsf");
			this.h()
		},

		l: function claim(nodes) {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n");

			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true }, false);
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);

			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div0_nodes, "H1", { class: true }, false);
			var h1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h1);

			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h1_nodes, "false quotes generator");
			h1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n\n");

			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", {}, false);
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);

			figure = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "FIGURE", { class: true }, false);
			var figure_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(figure);

			img = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(figure_nodes, "IMG", { alt: true, src: true, class: true }, false);
			var img_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(img);

			img_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(figure_nodes, "\n    ");

			figcaption = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(figure_nodes, "FIGCAPTION", {}, false);
			var figcaption_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(figcaption);

			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(figcaption_nodes, "HIGH FIVE!");
			figcaption_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			figure_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div1_nodes, "\n\n  ");

			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "P", { class: true }, false);
			var p0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p0);

			strong = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p0_nodes, "STRONG", {}, false);
			var strong_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(strong);

			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(strong_nodes, "Try editing this file (routes/index.html) to test live reloading.");
			strong_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "\n\n    ");

			button = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p0_nodes, "BUTTON", {}, false);
			var button_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(button);

			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(button_nodes, "A", { href: true, title: true, class: true }, false);
			var a_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a);

			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a_nodes, "Push");
			a_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			button_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			p0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div1_nodes, "\n\n  ");

			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "P", { class: true }, false);
			var p1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p1);

			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "dsfdsfsf");
			p1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			document.title = "Sapper project template";
			h1.className = "svelte-va4q69";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h1, file, 111, 2, 1906);
			div0.className = "caption svelte-va4q69";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 110, 0, 1882);
			img.alt = "Borat";
			img.src = "great-success.png";
			img.className = "svelte-va4q69";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img, file, 116, 4, 1967);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(figcaption, file, 117, 4, 2015);
			figure.className = "svelte-va4q69";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(figure, file, 115, 2, 1954);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(strong, file, 121, 4, 2074);
			a.href = "";
			a.title = "Button push blue/green";
			a.className = "button btnPush btnBlueGreen svelte-va4q69";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a, file, 126, 6, 2212);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(button, file, 125, 4, 2174);
			p0.className = "svelte-va4q69";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p0, file, 120, 2, 2066);
			p1.className = "quote svelte-va4q69";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p1, file, 132, 2, 2339);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 114, 0, 1946);
			dispose = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen"])(button, "click", handleClick);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, div0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div0, h1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(h1, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t2, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, div1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, figure);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figure, img);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figure, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figure, figcaption);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figcaption, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, p0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p0, strong);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(strong, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p0, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p0, button);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(button, a);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(a, t8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, t9);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, p1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, t10);
		},

		p: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t0);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(div0);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t2);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(div1);
			}

			dispose();
		}
	};
}

let count = 0;

let quote = "";

async function getQuote() {
  // count += 1;
  var urly = "http://localhost:3333/quote";
  let response = await fetch(urly);
  let data = await response.json();
  console.log(data);
  return { quote: response }; // <!-- and we're returning the result, rather than this.set(...)
}

async function getCelebrity() {
  var urly = "http://localhost:3333/celebrity";
  let response = await fetch(urly);
  let data = await response.json();
  console.log(data);
  return { celebrity: response };
}

async function handleClick(event) {
  getQuote();
  getCelebrity();
}

function preload({ params, query }) {
  // nothing todo
}

class Routes extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-va4q69-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, null, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], []);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Routes);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvcm91dGVzL2luZGV4LnN2ZWx0ZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs2RkE2SHNCLFdBQVc7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQTVIL0IsSUFBSSxLQUFLLEdBQUcsQ0FBQyxDQUFDOztBQUNkLElBQUksS0FBSyxHQUFHLEVBQUUsQ0FBQzs7QUFFZixlQUFlLFFBQVEsR0FBRztBQUMxQjtBQUNBLEVBQUUsSUFBSSxJQUFJLEdBQUcsNkJBQTZCLENBQUM7QUFDM0MsRUFBRSxJQUFJLFFBQVEsR0FBRyxNQUFNLEtBQUssQ0FBQyxJQUFJLENBQUMsQ0FBQztBQUNuQyxFQUFFLElBQUksSUFBSSxHQUFHLE1BQU0sUUFBUSxDQUFDLElBQUksRUFBRSxDQUFDO0FBQ25DLEVBQUUsT0FBTyxDQUFDLEdBQUcsQ0FBQyxJQUFJLENBQUMsQ0FBQztBQUNwQixFQUFFLE9BQU8sRUFBRSxLQUFLLEVBQUUsUUFBUSxFQUFFLENBQUM7QUFDN0IsQ0FBQzs7QUFDRCxlQUFlLFlBQVksR0FBRztBQUM5QixFQUFFLElBQUksSUFBSSxHQUFHLGlDQUFpQyxDQUFDO0FBQy9DLEVBQUUsSUFBSSxRQUFRLEdBQUcsTUFBTSxLQUFLLENBQUMsSUFBSSxDQUFDLENBQUM7QUFDbkMsRUFBRSxJQUFJLElBQUksR0FBRyxNQUFNLFFBQVEsQ0FBQyxJQUFJLEVBQUUsQ0FBQztBQUNuQyxFQUFFLE9BQU8sQ0FBQyxHQUFHLENBQUMsSUFBSSxDQUFDLENBQUM7QUFDcEIsRUFBRSxPQUFPLEVBQUUsU0FBUyxFQUFFLFFBQVEsRUFBRSxDQUFDO0FBQ2pDLENBQUM7O0FBQ0QsZUFBZSxXQUFXLENBQUMsS0FBSyxFQUFFO0FBQ2xDLEVBQUUsUUFBUSxFQUFFLENBQUM7QUFDYixFQUFFLFlBQVksRUFBRSxDQUFDO0FBQ2pCLENBQUM7O0FBRUQsU0FBUyxPQUFPLENBQUMsRUFBRSxNQUFNLEVBQUUsS0FBSyxFQUFFLEVBQUU7QUFDcEM7QUFDQSxDQUFDIiwiZmlsZSI6IjI5MTllNDAyMzA0ZjcwM2ZlZmY4L2luZGV4LmluZGV4LmpzIiwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgbGV0IGNvdW50ID0gMDtcbiAgbGV0IHF1b3RlID0gXCJcIjtcblxuICBhc3luYyBmdW5jdGlvbiBnZXRRdW90ZSgpIHtcbiAgICAvLyBjb3VudCArPSAxO1xuICAgIHZhciB1cmx5ID0gXCJodHRwOi8vbG9jYWxob3N0OjMzMzMvcXVvdGVcIjtcbiAgICBsZXQgcmVzcG9uc2UgPSBhd2FpdCBmZXRjaCh1cmx5KTtcbiAgICBsZXQgZGF0YSA9IGF3YWl0IHJlc3BvbnNlLmpzb24oKTtcbiAgICBjb25zb2xlLmxvZyhkYXRhKTtcbiAgICByZXR1cm4geyBxdW90ZTogcmVzcG9uc2UgfTsgLy8gPCEtLSBhbmQgd2UncmUgcmV0dXJuaW5nIHRoZSByZXN1bHQsIHJhdGhlciB0aGFuIHRoaXMuc2V0KC4uLilcbiAgfVxuICBhc3luYyBmdW5jdGlvbiBnZXRDZWxlYnJpdHkoKSB7XG4gICAgdmFyIHVybHkgPSBcImh0dHA6Ly9sb2NhbGhvc3Q6MzMzMy9jZWxlYnJpdHlcIjtcbiAgICBsZXQgcmVzcG9uc2UgPSBhd2FpdCBmZXRjaCh1cmx5KTtcbiAgICBsZXQgZGF0YSA9IGF3YWl0IHJlc3BvbnNlLmpzb24oKTtcbiAgICBjb25zb2xlLmxvZyhkYXRhKTtcbiAgICByZXR1cm4geyBjZWxlYnJpdHk6IHJlc3BvbnNlIH07XG4gIH1cbiAgYXN5bmMgZnVuY3Rpb24gaGFuZGxlQ2xpY2soZXZlbnQpIHtcbiAgICBnZXRRdW90ZSgpO1xuICAgIGdldENlbGVicml0eSgpO1xuICB9XG5cbiAgZnVuY3Rpb24gcHJlbG9hZCh7IHBhcmFtcywgcXVlcnkgfSkge1xuICAgIC8vIG5vdGhpbmcgdG9kb1xuICB9XG48L3NjcmlwdD5cblxuPHN0eWxlPlxuICBoMSxcbiAgZmlndXJlLFxuICBwIHtcbiAgICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gICAgbWFyZ2luOiAwIGF1dG87XG4gIH1cblxuICAuY2FwdGlvbiB7XG4gICAgbWFyZ2luOiAwIGF1dG87XG4gICAgcGFkZGluZy10b3A6IDIwMHB4O1xuICAgIHdpZHRoOiA3MCU7XG4gIH1cblxuICAucXVvdGUge1xuICAgIGZvbnQtZmFtaWx5OiBcIkxpYnJlIEJhc2tlcnZpbGxlXCIsIEdlb3JnaWEsIHNlcmlmO1xuICB9XG5cbiAgLyogM0QgKi9cbiAgLmJ0bkJsdWVHcmVlbi5idG5QdXNoIHtcbiAgICBib3gtc2hhZG93OiAwcHggNXB4IDBweCAwcHggIzAwNzE0NDtcbiAgfVxuXG4gIC5idG5CbHVlR3JlZW4ge1xuICAgIGJhY2tncm91bmQ6ICMwMGFlNjg7XG4gIH1cblxuICBhLmJ1dHRvbiB7XG4gICAgZGlzcGxheTogYmxvY2s7XG4gICAgcG9zaXRpb246IHJlbGF0aXZlO1xuICAgIGZsb2F0OiBsZWZ0O1xuICAgIHdpZHRoOiAxMjBweDtcbiAgICBwYWRkaW5nOiAwO1xuICAgIG1hcmdpbjogMTBweCAyMHB4IDEwcHggMDtcbiAgICBmb250LXdlaWdodDogNjAwO1xuICAgIHRleHQtYWxpZ246IGNlbnRlcjtcbiAgICBsaW5lLWhlaWdodDogNTBweDtcbiAgICBjb2xvcjogI2ZmZjtcbiAgICBib3JkZXItcmFkaXVzOiA1cHg7XG4gICAgdHJhbnNpdGlvbjogYWxsIDAuMnM7XG4gIH1cblxuICAuYnRuUHVzaDpob3ZlciB7XG4gICAgbWFyZ2luLXRvcDogMTVweDtcbiAgICBtYXJnaW4tYm90dG9tOiA1cHg7XG4gIH1cblxuICAuYnRuQmx1ZUdyZWVuLmJ0blB1c2g6aG92ZXIge1xuICAgIGJveC1zaGFkb3c6IDBweCAwcHggMHB4IDBweCAjMDA3MTQ0O1xuICB9XG5cbiAgaDEge1xuICAgIGZvbnQtc2l6ZTogMi44ZW07XG4gICAgZm9udC13ZWlnaHQ6IDcwMDtcbiAgICBtYXJnaW46IDAgMCAwLjVlbSAwO1xuICB9XG5cbiAgZmlndXJlIHtcbiAgICBtYXJnaW46IDAgMCAxZW0gMDtcbiAgfVxuXG4gIGltZyB7XG4gICAgd2lkdGg6IDEwMCU7XG4gICAgbWF4LXdpZHRoOiA0MDBweDtcbiAgICBtYXJnaW46IDAgMCAxZW0gMDtcbiAgfVxuXG4gIHAge1xuICAgIG1hcmdpbjogMWVtIGF1dG87XG4gIH1cblxuICBAbWVkaWEgKG1pbi13aWR0aDogNDgwcHgpIHtcbiAgICBoMSB7XG4gICAgICBmb250LXNpemU6IDRlbTtcbiAgICB9XG4gIH1cbjwvc3R5bGU+XG5cbjxzdmVsdGU6aGVhZD5cbiAgPHRpdGxlPlNhcHBlciBwcm9qZWN0IHRlbXBsYXRlPC90aXRsZT5cbjwvc3ZlbHRlOmhlYWQ+XG48ZGl2IGNsYXNzPVwiY2FwdGlvblwiPlxuICA8aDE+ZmFsc2UgcXVvdGVzIGdlbmVyYXRvcjwvaDE+XG48L2Rpdj5cblxuPGRpdj5cbiAgPGZpZ3VyZT5cbiAgICA8aW1nIGFsdD1cIkJvcmF0XCIgc3JjPVwiZ3JlYXQtc3VjY2Vzcy5wbmdcIiAvPlxuICAgIDxmaWdjYXB0aW9uPkhJR0ggRklWRSE8L2ZpZ2NhcHRpb24+XG4gIDwvZmlndXJlPlxuXG4gIDxwPlxuICAgIDxzdHJvbmc+XG4gICAgICBUcnkgZWRpdGluZyB0aGlzIGZpbGUgKHJvdXRlcy9pbmRleC5odG1sKSB0byB0ZXN0IGxpdmUgcmVsb2FkaW5nLlxuICAgIDwvc3Ryb25nPlxuXG4gICAgPGJ1dHRvbiBvbjpjbGljaz17aGFuZGxlQ2xpY2t9PlxuICAgICAgPGEgaHJlZj1cIlwiIHRpdGxlPVwiQnV0dG9uIHB1c2ggYmx1ZS9ncmVlblwiIGNsYXNzPVwiYnV0dG9uIGJ0blB1c2ggYnRuQmx1ZUdyZWVuXCI+XG4gICAgICAgIFB1c2hcbiAgICAgIDwvYT5cbiAgICA8L2J1dHRvbj5cbiAgPC9wPlxuXG4gIDxwIGNsYXNzPVwicXVvdGVcIj5kc2Zkc2ZzZjwvcD5cbjwvZGl2PlxuIl0sInNvdXJjZVJvb3QiOiIifQ==