(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["index"],{

/***/ "./src/routes/index.svelte":
/*!*********************************!*\
  !*** ./src/routes/index.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal.mjs");
/* src/routes/index.svelte generated by Svelte v3.2.0 */


const file = "src/routes/index.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = 'svelte-1dfhqou-style';
	style.textContent = "h1.svelte-1dfhqou,figure.svelte-1dfhqou,p.svelte-1dfhqou{text-align:center;margin:0 auto}.caption.svelte-1dfhqou{margin:0 auto;padding-top:200px;width:70%}.quote.svelte-1dfhqou{font-family:\"Libre Baskerville\", Georgia, serif}.btnBlueGreen.btnPush.svelte-1dfhqou{box-shadow:0px 5px 0px 0px #007144}h1.svelte-1dfhqou{font-size:2.8em;font-weight:700;margin:0 0 0.5em 0}figure.svelte-1dfhqou{margin:0 0 1em 0}img.svelte-1dfhqou{width:100%;max-width:400px;margin:0 0 1em 0}p.svelte-1dfhqou{margin:1em auto}@media(min-width: 480px){h1.svelte-1dfhqou{font-size:4em}}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguc3ZlbHRlIiwic291cmNlcyI6WyJpbmRleC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgbGV0IGNvdW50ID0gMDtcbiAgbGV0IHF1b3RlID0gXCJcIjtcblxuICBhc3luYyBmdW5jdGlvbiBnZXRRdW90ZSgpIHtcbiAgICAvLyBjb3VudCArPSAxO1xuICAgIHZhciB1cmx5ID0gXCJodHRwOi8vbG9jYWxob3N0OjMzMzMvcXVvdGVcIjtcbiAgICBsZXQgcmVzcG9uc2UgPSBhd2FpdCBmZXRjaCh1cmx5KTtcbiAgICBsZXQgZGF0YSA9IGF3YWl0IHJlc3BvbnNlLmpzb24oKTtcbiAgICBjb25zb2xlLmxvZyhkYXRhKTtcbiAgICByZXR1cm4geyBxdW90ZTogcmVzcG9uc2UgfTsgLy8gPCEtLSBhbmQgd2UncmUgcmV0dXJuaW5nIHRoZSByZXN1bHQsIHJhdGhlciB0aGFuIHRoaXMuc2V0KC4uLilcbiAgfVxuICBhc3luYyBmdW5jdGlvbiBnZXRDZWxlYnJpdHkoKSB7XG4gICAgdmFyIHVybHkgPSBcImh0dHA6Ly9sb2NhbGhvc3Q6MzMzMy9jZWxlYnJpdHlcIjtcbiAgICBsZXQgcmVzcG9uc2UgPSBhd2FpdCBmZXRjaCh1cmx5KTtcbiAgICBsZXQgZGF0YSA9IGF3YWl0IHJlc3BvbnNlLmpzb24oKTtcbiAgICBjb25zb2xlLmxvZyhkYXRhKTtcbiAgICByZXR1cm4geyBjZWxlYnJpdHk6IHJlc3BvbnNlIH07XG4gIH1cbiAgYXN5bmMgZnVuY3Rpb24gaGFuZGxlQ2xpY2soZXZlbnQpIHtcbiAgICBnZXRRdW90ZSgpO1xuICAgIGdldENlbGVicml0eSgpO1xuICB9XG5cbiAgZnVuY3Rpb24gcHJlbG9hZCh7IHBhcmFtcywgcXVlcnkgfSkge1xuICAgIC8vIG5vdGhpbmcgdG9kb1xuICB9XG48L3NjcmlwdD5cblxuPHN0eWxlPlxuICBoMSxcbiAgZmlndXJlLFxuICBwIHtcbiAgICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gICAgbWFyZ2luOiAwIGF1dG87XG4gIH1cblxuICAuY2FwdGlvbiB7XG4gICAgbWFyZ2luOiAwIGF1dG87XG4gICAgcGFkZGluZy10b3A6IDIwMHB4O1xuICAgIHdpZHRoOiA3MCU7XG4gIH1cblxuICAucXVvdGUge1xuICAgIGZvbnQtZmFtaWx5OiBcIkxpYnJlIEJhc2tlcnZpbGxlXCIsIEdlb3JnaWEsIHNlcmlmO1xuICB9XG5cbiAgLyogM0QgKi9cbiAgLmJ0bkJsdWVHcmVlbi5idG5QdXNoIHtcbiAgICBib3gtc2hhZG93OiAwcHggNXB4IDBweCAwcHggIzAwNzE0NDtcbiAgfVxuXG4gIGgxIHtcbiAgICBmb250LXNpemU6IDIuOGVtO1xuICAgIGZvbnQtd2VpZ2h0OiA3MDA7XG4gICAgbWFyZ2luOiAwIDAgMC41ZW0gMDtcbiAgfVxuXG4gIGZpZ3VyZSB7XG4gICAgbWFyZ2luOiAwIDAgMWVtIDA7XG4gIH1cblxuICBpbWcge1xuICAgIHdpZHRoOiAxMDAlO1xuICAgIG1heC13aWR0aDogNDAwcHg7XG4gICAgbWFyZ2luOiAwIDAgMWVtIDA7XG4gIH1cblxuICBwIHtcbiAgICBtYXJnaW46IDFlbSBhdXRvO1xuICB9XG5cbiAgQG1lZGlhIChtaW4td2lkdGg6IDQ4MHB4KSB7XG4gICAgaDEge1xuICAgICAgZm9udC1zaXplOiA0ZW07XG4gICAgfVxuICB9XG48L3N0eWxlPlxuXG48c3ZlbHRlOmhlYWQ+XG4gIDx0aXRsZT5TYXBwZXIgcHJvamVjdCB0ZW1wbGF0ZTwvdGl0bGU+XG48L3N2ZWx0ZTpoZWFkPlxuPGRpdiBjbGFzcz1cImNhcHRpb25cIj5cbiAgPGgxPmZhbHNlIHF1b3RlcyBnZW5lcmF0b3I8L2gxPlxuPC9kaXY+XG5cbjxkaXY+XG4gIDxmaWd1cmU+XG4gICAgPGltZyBhbHQ9XCJCb3JhdFwiIHNyYz1cImdyZWF0LXN1Y2Nlc3MucG5nXCIgLz5cbiAgICA8ZmlnY2FwdGlvbj5ISUdIIEZJVkUhPC9maWdjYXB0aW9uPlxuICA8L2ZpZ3VyZT5cblxuICA8cD5cbiAgICA8c3Ryb25nPlxuICAgICAgVHJ5IGVkaXRpbmcgdGhpcyBmaWxlIChyb3V0ZXMvaW5kZXguaHRtbCkgdG8gdGVzdCBsaXZlIHJlbG9hZGluZy5cbiAgICA8L3N0cm9uZz5cblxuICAgIDxidXR0b24gb246Y2xpY2s9e2hhbmRsZUNsaWNrfT5jb3VudDoge2NvdW50fTwvYnV0dG9uPlxuICAgIDxhXG4gICAgICBocmVmPVwiXCJcbiAgICAgIHRpdGxlPVwiQnV0dG9uIHB1c2ggYmx1ZS9ncmVlblwiXG4gICAgICBjbGFzcz1cImJ1dHRvbiBidG5QdXNoIGJ0bkJsdWVHcmVlblwiPlxuICAgICAgUHVzaFxuICAgIDwvYT5cbiAgPC9wPlxuXG4gIDxwIGNsYXNzPVwicXVvdGVcIj5kc2Zkc2ZzZjwvcD5cbjwvZGl2PlxuIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQThCRSxpQkFBRSxDQUNGLHFCQUFNLENBQ04sQ0FBQyxlQUFDLENBQUMsQUFDRCxVQUFVLENBQUUsTUFBTSxDQUNsQixNQUFNLENBQUUsQ0FBQyxDQUFDLElBQUksQUFDaEIsQ0FBQyxBQUVELFFBQVEsZUFBQyxDQUFDLEFBQ1IsTUFBTSxDQUFFLENBQUMsQ0FBQyxJQUFJLENBQ2QsV0FBVyxDQUFFLEtBQUssQ0FDbEIsS0FBSyxDQUFFLEdBQUcsQUFDWixDQUFDLEFBRUQsTUFBTSxlQUFDLENBQUMsQUFDTixXQUFXLENBQUUsbUJBQW1CLENBQUMsQ0FBQyxPQUFPLENBQUMsQ0FBQyxLQUFLLEFBQ2xELENBQUMsQUFHRCxhQUFhLFFBQVEsZUFBQyxDQUFDLEFBQ3JCLFVBQVUsQ0FBRSxHQUFHLENBQUMsR0FBRyxDQUFDLEdBQUcsQ0FBQyxHQUFHLENBQUMsT0FBTyxBQUNyQyxDQUFDLEFBRUQsRUFBRSxlQUFDLENBQUMsQUFDRixTQUFTLENBQUUsS0FBSyxDQUNoQixXQUFXLENBQUUsR0FBRyxDQUNoQixNQUFNLENBQUUsQ0FBQyxDQUFDLENBQUMsQ0FBQyxLQUFLLENBQUMsQ0FBQyxBQUNyQixDQUFDLEFBRUQsTUFBTSxlQUFDLENBQUMsQUFDTixNQUFNLENBQUUsQ0FBQyxDQUFDLENBQUMsQ0FBQyxHQUFHLENBQUMsQ0FBQyxBQUNuQixDQUFDLEFBRUQsR0FBRyxlQUFDLENBQUMsQUFDSCxLQUFLLENBQUUsSUFBSSxDQUNYLFNBQVMsQ0FBRSxLQUFLLENBQ2hCLE1BQU0sQ0FBRSxDQUFDLENBQUMsQ0FBQyxDQUFDLEdBQUcsQ0FBQyxDQUFDLEFBQ25CLENBQUMsQUFFRCxDQUFDLGVBQUMsQ0FBQyxBQUNELE1BQU0sQ0FBRSxHQUFHLENBQUMsSUFBSSxBQUNsQixDQUFDLEFBRUQsTUFBTSxBQUFDLFlBQVksS0FBSyxDQUFDLEFBQUMsQ0FBQyxBQUN6QixFQUFFLGVBQUMsQ0FBQyxBQUNGLFNBQVMsQ0FBRSxHQUFHLEFBQ2hCLENBQUMsQUFDSCxDQUFDIn0= */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(document.head, style);
}

function create_fragment(ctx) {
	var t0, div0, h1, t1, t2, div1, figure, img, t3, figcaption, t4, t5, p0, strong, t6, t7, button, t8, t9, t10, a, t11, t12, p1, t13, dispose;

	return {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h1");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("false quotes generator");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			figure = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("figure");
			img = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			figcaption = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("figcaption");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("HIGH FIVE!");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			strong = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("strong");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Try editing this file (routes/index.html) to test live reloading.");
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			button = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("button");
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("count: ");
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(count);
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Push");
			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("dsfdsfsf");
			this.h()
		},

		l: function claim(nodes) {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n");

			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true }, false);
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);

			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div0_nodes, "H1", { class: true }, false);
			var h1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h1);

			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h1_nodes, "false quotes generator");
			h1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(nodes, "\n\n");

			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", {}, false);
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);

			figure = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "FIGURE", { class: true }, false);
			var figure_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(figure);

			img = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(figure_nodes, "IMG", { alt: true, src: true, class: true }, false);
			var img_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(img);

			img_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(figure_nodes, "\n    ");

			figcaption = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(figure_nodes, "FIGCAPTION", {}, false);
			var figcaption_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(figcaption);

			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(figcaption_nodes, "HIGH FIVE!");
			figcaption_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			figure_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div1_nodes, "\n\n  ");

			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "P", { class: true }, false);
			var p0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p0);

			strong = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p0_nodes, "STRONG", {}, false);
			var strong_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(strong);

			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(strong_nodes, "Try editing this file (routes/index.html) to test live reloading.");
			strong_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "\n\n    ");

			button = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p0_nodes, "BUTTON", {}, false);
			var button_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(button);

			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(button_nodes, "count: ");
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(button_nodes, count);
			button_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "\n    ");

			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p0_nodes, "A", { href: true, title: true, class: true }, false);
			var a_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a);

			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a_nodes, "Push");
			a_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			p0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div1_nodes, "\n\n  ");

			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "P", { class: true }, false);
			var p1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p1);

			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "dsfdsfsf");
			p1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			document.title = "Sapper project template";
			h1.className = "svelte-1dfhqou";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h1, file, 83, 2, 1431);
			div0.className = "caption svelte-1dfhqou";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 82, 0, 1407);
			img.alt = "Borat";
			img.src = "great-success.png";
			img.className = "svelte-1dfhqou";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img, file, 88, 4, 1492);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(figcaption, file, 89, 4, 1540);
			figure.className = "svelte-1dfhqou";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(figure, file, 87, 2, 1479);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(strong, file, 93, 4, 1599);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(button, file, 97, 4, 1699);
			a.href = "";
			a.title = "Button push blue/green";
			a.className = "button btnPush btnBlueGreen svelte-1dfhqou";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a, file, 98, 4, 1758);
			p0.className = "svelte-1dfhqou";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p0, file, 92, 2, 1591);
			p1.className = "quote svelte-1dfhqou";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p1, file, 106, 2, 1885);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 86, 0, 1471);
			dispose = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen"])(button, "click", handleClick);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, div0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div0, h1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(h1, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, t2, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, div1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, figure);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figure, img);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figure, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figure, figcaption);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(figcaption, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, p0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p0, strong);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(strong, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p0, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p0, button);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(button, t8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(button, t9);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p0, t10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p0, a);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(a, t11);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, t12);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, p1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p1, t13);
		},

		p: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t0);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(div0);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(t2);
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(div1);
			}

			dispose();
		}
	};
}

let count = 0;

let quote = "";

async function getQuote() {
  // count += 1;
  var urly = "http://localhost:3333/quote";
  let response = await fetch(urly);
  let data = await response.json();
  console.log(data);
  return { quote: response }; // <!-- and we're returning the result, rather than this.set(...)
}

async function getCelebrity() {
  var urly = "http://localhost:3333/celebrity";
  let response = await fetch(urly);
  let data = await response.json();
  console.log(data);
  return { celebrity: response };
}

async function handleClick(event) {
  getQuote();
  getCelebrity();
}

function preload({ params, query }) {
  // nothing todo
}

class Routes extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-1dfhqou-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, null, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], []);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Routes);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvcm91dGVzL2luZGV4LnN2ZWx0ZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztxRUFpRzJDLEtBQUs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7eUZBQUwsS0FBSzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzZGQUExQixXQUFXOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUFoRy9CLElBQUksS0FBSyxHQUFHLENBQUMsQ0FBQzs7QUFDZCxJQUFJLEtBQUssR0FBRyxFQUFFLENBQUM7O0FBRWYsZUFBZSxRQUFRLEdBQUc7QUFDMUI7QUFDQSxFQUFFLElBQUksSUFBSSxHQUFHLDZCQUE2QixDQUFDO0FBQzNDLEVBQUUsSUFBSSxRQUFRLEdBQUcsTUFBTSxLQUFLLENBQUMsSUFBSSxDQUFDLENBQUM7QUFDbkMsRUFBRSxJQUFJLElBQUksR0FBRyxNQUFNLFFBQVEsQ0FBQyxJQUFJLEVBQUUsQ0FBQztBQUNuQyxFQUFFLE9BQU8sQ0FBQyxHQUFHLENBQUMsSUFBSSxDQUFDLENBQUM7QUFDcEIsRUFBRSxPQUFPLEVBQUUsS0FBSyxFQUFFLFFBQVEsRUFBRSxDQUFDO0FBQzdCLENBQUM7O0FBQ0QsZUFBZSxZQUFZLEdBQUc7QUFDOUIsRUFBRSxJQUFJLElBQUksR0FBRyxpQ0FBaUMsQ0FBQztBQUMvQyxFQUFFLElBQUksUUFBUSxHQUFHLE1BQU0sS0FBSyxDQUFDLElBQUksQ0FBQyxDQUFDO0FBQ25DLEVBQUUsSUFBSSxJQUFJLEdBQUcsTUFBTSxRQUFRLENBQUMsSUFBSSxFQUFFLENBQUM7QUFDbkMsRUFBRSxPQUFPLENBQUMsR0FBRyxDQUFDLElBQUksQ0FBQyxDQUFDO0FBQ3BCLEVBQUUsT0FBTyxFQUFFLFNBQVMsRUFBRSxRQUFRLEVBQUUsQ0FBQztBQUNqQyxDQUFDOztBQUNELGVBQWUsV0FBVyxDQUFDLEtBQUssRUFBRTtBQUNsQyxFQUFFLFFBQVEsRUFBRSxDQUFDO0FBQ2IsRUFBRSxZQUFZLEVBQUUsQ0FBQztBQUNqQixDQUFDOztBQUVELFNBQVMsT0FBTyxDQUFDLEVBQUUsTUFBTSxFQUFFLEtBQUssRUFBRSxFQUFFO0FBQ3BDO0FBQ0EsQ0FBQyIsImZpbGUiOiI3ZjYyODczY2YyNmM0OTY4MTljYi9pbmRleC5pbmRleC5qcyIsInNvdXJjZXNDb250ZW50IjpbIjxzY3JpcHQ+XG4gIGxldCBjb3VudCA9IDA7XG4gIGxldCBxdW90ZSA9IFwiXCI7XG5cbiAgYXN5bmMgZnVuY3Rpb24gZ2V0UXVvdGUoKSB7XG4gICAgLy8gY291bnQgKz0gMTtcbiAgICB2YXIgdXJseSA9IFwiaHR0cDovL2xvY2FsaG9zdDozMzMzL3F1b3RlXCI7XG4gICAgbGV0IHJlc3BvbnNlID0gYXdhaXQgZmV0Y2godXJseSk7XG4gICAgbGV0IGRhdGEgPSBhd2FpdCByZXNwb25zZS5qc29uKCk7XG4gICAgY29uc29sZS5sb2coZGF0YSk7XG4gICAgcmV0dXJuIHsgcXVvdGU6IHJlc3BvbnNlIH07IC8vIDwhLS0gYW5kIHdlJ3JlIHJldHVybmluZyB0aGUgcmVzdWx0LCByYXRoZXIgdGhhbiB0aGlzLnNldCguLi4pXG4gIH1cbiAgYXN5bmMgZnVuY3Rpb24gZ2V0Q2VsZWJyaXR5KCkge1xuICAgIHZhciB1cmx5ID0gXCJodHRwOi8vbG9jYWxob3N0OjMzMzMvY2VsZWJyaXR5XCI7XG4gICAgbGV0IHJlc3BvbnNlID0gYXdhaXQgZmV0Y2godXJseSk7XG4gICAgbGV0IGRhdGEgPSBhd2FpdCByZXNwb25zZS5qc29uKCk7XG4gICAgY29uc29sZS5sb2coZGF0YSk7XG4gICAgcmV0dXJuIHsgY2VsZWJyaXR5OiByZXNwb25zZSB9O1xuICB9XG4gIGFzeW5jIGZ1bmN0aW9uIGhhbmRsZUNsaWNrKGV2ZW50KSB7XG4gICAgZ2V0UXVvdGUoKTtcbiAgICBnZXRDZWxlYnJpdHkoKTtcbiAgfVxuXG4gIGZ1bmN0aW9uIHByZWxvYWQoeyBwYXJhbXMsIHF1ZXJ5IH0pIHtcbiAgICAvLyBub3RoaW5nIHRvZG9cbiAgfVxuPC9zY3JpcHQ+XG5cbjxzdHlsZT5cbiAgaDEsXG4gIGZpZ3VyZSxcbiAgcCB7XG4gICAgdGV4dC1hbGlnbjogY2VudGVyO1xuICAgIG1hcmdpbjogMCBhdXRvO1xuICB9XG5cbiAgLmNhcHRpb24ge1xuICAgIG1hcmdpbjogMCBhdXRvO1xuICAgIHBhZGRpbmctdG9wOiAyMDBweDtcbiAgICB3aWR0aDogNzAlO1xuICB9XG5cbiAgLnF1b3RlIHtcbiAgICBmb250LWZhbWlseTogXCJMaWJyZSBCYXNrZXJ2aWxsZVwiLCBHZW9yZ2lhLCBzZXJpZjtcbiAgfVxuXG4gIC8qIDNEICovXG4gIC5idG5CbHVlR3JlZW4uYnRuUHVzaCB7XG4gICAgYm94LXNoYWRvdzogMHB4IDVweCAwcHggMHB4ICMwMDcxNDQ7XG4gIH1cblxuICBoMSB7XG4gICAgZm9udC1zaXplOiAyLjhlbTtcbiAgICBmb250LXdlaWdodDogNzAwO1xuICAgIG1hcmdpbjogMCAwIDAuNWVtIDA7XG4gIH1cblxuICBmaWd1cmUge1xuICAgIG1hcmdpbjogMCAwIDFlbSAwO1xuICB9XG5cbiAgaW1nIHtcbiAgICB3aWR0aDogMTAwJTtcbiAgICBtYXgtd2lkdGg6IDQwMHB4O1xuICAgIG1hcmdpbjogMCAwIDFlbSAwO1xuICB9XG5cbiAgcCB7XG4gICAgbWFyZ2luOiAxZW0gYXV0bztcbiAgfVxuXG4gIEBtZWRpYSAobWluLXdpZHRoOiA0ODBweCkge1xuICAgIGgxIHtcbiAgICAgIGZvbnQtc2l6ZTogNGVtO1xuICAgIH1cbiAgfVxuPC9zdHlsZT5cblxuPHN2ZWx0ZTpoZWFkPlxuICA8dGl0bGU+U2FwcGVyIHByb2plY3QgdGVtcGxhdGU8L3RpdGxlPlxuPC9zdmVsdGU6aGVhZD5cbjxkaXYgY2xhc3M9XCJjYXB0aW9uXCI+XG4gIDxoMT5mYWxzZSBxdW90ZXMgZ2VuZXJhdG9yPC9oMT5cbjwvZGl2PlxuXG48ZGl2PlxuICA8ZmlndXJlPlxuICAgIDxpbWcgYWx0PVwiQm9yYXRcIiBzcmM9XCJncmVhdC1zdWNjZXNzLnBuZ1wiIC8+XG4gICAgPGZpZ2NhcHRpb24+SElHSCBGSVZFITwvZmlnY2FwdGlvbj5cbiAgPC9maWd1cmU+XG5cbiAgPHA+XG4gICAgPHN0cm9uZz5cbiAgICAgIFRyeSBlZGl0aW5nIHRoaXMgZmlsZSAocm91dGVzL2luZGV4Lmh0bWwpIHRvIHRlc3QgbGl2ZSByZWxvYWRpbmcuXG4gICAgPC9zdHJvbmc+XG5cbiAgICA8YnV0dG9uIG9uOmNsaWNrPXtoYW5kbGVDbGlja30+Y291bnQ6IHtjb3VudH08L2J1dHRvbj5cbiAgICA8YVxuICAgICAgaHJlZj1cIlwiXG4gICAgICB0aXRsZT1cIkJ1dHRvbiBwdXNoIGJsdWUvZ3JlZW5cIlxuICAgICAgY2xhc3M9XCJidXR0b24gYnRuUHVzaCBidG5CbHVlR3JlZW5cIj5cbiAgICAgIFB1c2hcbiAgICA8L2E+XG4gIDwvcD5cblxuICA8cCBjbGFzcz1cInF1b3RlXCI+ZHNmZHNmc2Y8L3A+XG48L2Rpdj5cbiJdLCJzb3VyY2VSb290IjoiIn0=